# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_smoothing1_Reg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.982984,133.560560,84.333357,119.247642,126.638966,148.562773,110.722468,138.696769,99.956627,119.273901,...,102.652784,98.945830,103.730214,87.557353,128.183525,113.539393,104.024715,128.997656,76.477720,117.812548
1,103.488858,133.717227,83.317185,119.205559,126.364151,148.660444,110.700989,138.977721,99.830644,119.337471,...,102.239460,98.661034,104.013378,87.475098,128.278028,113.175103,104.057682,128.929703,76.629126,117.340545
2,103.473886,133.057716,83.262537,119.514364,126.186366,148.600043,110.017163,138.502851,100.279702,118.985034,...,101.732656,98.729623,104.018735,86.635147,128.028026,113.236628,103.380443,129.108607,76.483848,117.594687
3,103.396488,132.973989,83.709463,119.535511,126.321585,148.252406,109.800436,138.419657,99.836885,118.780639,...,101.123674,98.497436,103.781200,86.565180,128.082891,112.866625,103.408086,128.926933,76.586519,117.342649
4,103.738140,132.932504,83.545695,119.508053,126.417684,148.012685,109.915656,138.206884,99.719747,118.684361,...,101.342881,98.668108,104.031972,86.812436,127.946784,112.590099,103.423829,129.791533,75.907798,117.119249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,129.064898,113.665335,105.104003,77.766603,151.382854,137.508501,134.060579,116.170088,116.861417,109.069828,...,109.218227,120.099410,108.608338,67.998597,137.539877,113.340129,132.253458,115.127941,107.403174,80.314707
2439,128.900720,114.054569,105.420061,77.974865,151.105050,137.857697,133.877317,116.133446,117.408857,108.069766,...,108.855827,119.922440,108.215137,67.680771,137.476144,113.494367,132.548317,115.076734,107.542107,80.357671
2440,128.666577,113.614407,105.353262,78.258592,151.002801,137.753080,133.866964,116.140722,117.624351,108.016646,...,108.632494,119.987584,107.875185,68.087338,137.549827,113.817483,132.575790,115.074207,107.134390,80.601779
2441,128.254882,114.017200,104.692428,78.046336,151.167832,137.766311,134.472211,116.265133,117.374517,107.971510,...,108.819438,120.082408,107.605719,67.944453,137.072203,113.553850,132.689469,115.198062,107.852113,80.485939
2442,128.476041,113.975170,105.053616,77.853386,150.959478,137.718909,134.929389,116.284381,116.758218,107.863613,...,108.880692,119.676487,107.956403,67.705645,136.844673,113.797469,132.360806,115.072537,108.089913,80.263814

In [4]:
position_data = pd.read_excel('real_positions_Reg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.982984,133.560560,84.333357,119.247642,126.638966,148.562773,110.722468,138.696769,99.956627,119.273901,...,102.652784,98.945830,103.730214,87.557353,128.183525,113.539393,104.024715,128.997656,76.477720,117.812548
1,103.488858,133.717227,83.317185,119.205559,126.364151,148.660444,110.700989,138.977721,99.830644,119.337471,...,102.239460,98.661034,104.013378,87.475098,128.278028,113.175103,104.057682,128.929703,76.629126,117.340545
2,103.473886,133.057716,83.262537,119.514364,126.186366,148.600043,110.017163,138.502851,100.279702,118.985034,...,101.732656,98.729623,104.018735,86.635147,128.028026,113.236628,103.380443,129.108607,76.483848,117.594687
3,103.396488,132.973989,83.709463,119.535511,126.321585,148.252406,109.800436,138.419657,99.836885,118.780639,...,101.123674,98.497436,103.781200,86.565180,128.082891,112.866625,103.408086,128.926933,76.586519,117.342649
4,103.738140,132.932504,83.545695,119.508053,126.417684,148.012685,109.915656,138.206884,99.719747,118.684361,...,101.342881,98.668108,104.031972,86.812436,127.946784,112.590099,103.423829,129.791533,75.907798,117.119249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,129.064898,113.665335,105.104003,77.766603,151.382854,137.508501,134.060579,116.170088,116.861417,109.069828,...,109.218227,120.099410,108.608338,67.998597,137.539877,113.340129,132.253458,115.127941,107.403174,80.314707
2439,128.900720,114.054569,105.420061,77.974865,151.105050,137.857697,133.877317,116.133446,117.408857,108.069766,...,108.855827,119.922440,108.215137,67.680771,137.476144,113.494367,132.548317,115.076734,107.542107,80.357671
2440,128.666577,113.614407,105.353262,78.258592,151.002801,137.753080,133.866964,116.140722,117.624351,108.016646,...,108.632494,119.987584,107.875185,68.087338,137.549827,113.817483,132.575790,115.074207,107.134390,80.601779
2441,128.254882,114.017200,104.692428,78.046336,151.167832,137.766311,134.472211,116.265133,117.374517,107.971510,...,108.819438,120.082408,107.605719,67.944453,137.072203,113.553850,132.689469,115.198062,107.852113,80.485939
2442,128.476041,113.975170,105.053616,77.853386,150.959478,137.718909,134.929389,116.284381,116.758218,107.863613,...,108.880692,119.676487,107.956403,67.705645,136.844673,113.797469,132.360806,115.072537,108.089913,80.263814

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [ ]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.43
Fold 1 - Mean Absolute Error (MAE): 0.50
Fold 1 - Root Mean Squared Error (RMSE): 0.65
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.45
Fold 2 - Mean Absolute Error (MAE): 0.52
Fold 2 - Root Mean Squared Error (RMSE): 0.67
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.43
Fold 3 - Mean Absolute Error (MAE): 0.51
Fold 3 - Root Mean Squared Error (RMSE): 0.66
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.44
Fold 4 - Mean Absolute Error (MAE): 0.51
Fold 4 - Root Mean Squared Error (RMSE): 0.66
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.41
Fold 5 - Mean Absolute Error (MAE): 0.50
Fold 5 - Root Mean Squared Error (RMSE): 0.64
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.43
Mean - Mean Absolute Error (MAE): 0.51
Mean - Root Mean Squared Error (RMSE): 0.66
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 0.49
Fold 1 - Mean Absolute Error (MAE): 0.42
Fold 1 - Root Mean Squared Error (RMSE): 0.70
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 1.44
Fold 2 - Mean Absolute Error (MAE): 0.51
Fold 2 - Root Mean Squared Error (RMSE): 1.20
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 1.81
Fold 3 - Mean Absolute Error (MAE): 0.53
Fold 3 - Root Mean Squared Error (RMSE): 1.35
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 2.04
Fold 4 - Mean Absolute Error (MAE): 0.52
Fold 4 - Root Mean Squared Error (RMSE): 1.43
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 3.07
Fold 5 - Mean Absolute Error (MAE): 0.54
Fold 5 - Root Mean Squared Error (RMSE): 1.75
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 1.77
Mean - Mean Absolute Error (MAE): 0.50
Mean - Root Mean Squared Error (RMSE): 1.29
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.15
Fold 1 - Mean Absolute Error (MAE): 0.16
Fold 1 - Root Mean Squared Error (RMSE): 0.38
Fold 1 - Time taken: 2.31 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.25
Fold 2 - Mean Absolute Error (MAE): 0.21
Fold 2 - Root Mean Squared Error (RMSE): 0.50
Fold 2 - Time taken: 2.27 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.66
Fold 3 - Mean Absolute Error (MAE): 0.26
Fold 3 - Root Mean Squared Error (RMSE): 0.81
Fold 3 - Time taken: 3.40 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.37
Fold 4 - Mean Absolute Error (MAE): 0.21
Fold 4 - Root Mean Squared Error (RMSE): 0.61
Fold 4 - Time taken: 3.62 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.11
Fold 5 - Mean Absolute Error (MAE): 0.19
Fold 5 - Root Mean Squared Error (RMSE): 0.33
Fold 5 - Time taken: 3.77 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.31
Mean - Mean Absolute Error (MAE): 0.21
Mean - Root Mean Squared Error (RMSE): 0.53
Mean - Time taken: 3.07 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.04
Fold 1 - Mean Absolute Error (MAE): 0.14
Fold 1 - Root Mean Squared Error (RMSE): 0.21
Fold 1 - Time taken: 0.11 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.05
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.22
Fold 2 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.06
Fold 3 - Mean Absolute Error (MAE): 0.15
Fold 3 - Root Mean Squared Error (RMSE): 0.24
Fold 3 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.06
Fold 4 - Mean Absolute Error (MAE): 0.15
Fold 4 - Root Mean Squared Error (RMSE): 0.25
Fold 4 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.06
Fold 5 - Mean Absolute Error (MAE): 0.16
Fold 5 - Root Mean Squared Error (RMSE): 0.25
Fold 5 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.05
Mean - Mean Absolute Error (MAE): 0.15
Mean - Root Mean Squared Error (RMSE): 0.23
Mean - Time taken: 0.06 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.83
Fold 1 - Mean Absolute Error (MAE): 0.50
Fold 1 - Root Mean Squared Error (RMSE): 0.91
Fold 1 - Time taken: 4.81 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.94
Fold 2 - Mean Absolute Error (MAE): 0.51
Fold 2 - Root Mean Squared Error (RMSE): 0.97
Fold 2 - Time taken: 5.22 seconds

# Saving the results to an Excel file

In [ ]:
results_df.to_excel("Results__PL_model_1_smoothing1_Reg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_1_smoothing1_Reg1.xlsx file")