# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_Scattered1_Reg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,99.343526,132.086973,81.738024,120.226650,127.621983,141.734180,104.808368,135.708107,100.574201,121.172680,...,100.001333,93.030358,108.610318,80.971633,127.068253,113.273672,102.118525,120.868728,81.395424,119.242231
1,104.733610,136.739848,85.595980,121.531174,128.150768,146.754292,112.456378,142.308630,99.220561,113.623552,...,94.944468,92.532748,102.178885,85.745827,127.498364,101.891695,100.754638,132.995837,81.702073,109.877760
2,102.503893,122.812742,79.306588,116.294374,121.246788,147.866563,114.673974,145.754454,98.140959,113.898725,...,106.442714,104.297185,109.932826,83.496819,130.000814,106.665402,100.613200,124.160411,71.817836,119.550575
3,105.439048,128.212611,91.820230,108.778849,126.667009,154.660799,114.044773,138.616554,103.117246,119.596471,...,102.668226,97.500489,103.068480,85.886335,135.283285,109.376512,105.742410,129.627503,75.726365,114.868672
4,104.124270,136.003305,84.028696,124.663682,135.153193,143.579315,110.567758,136.614045,99.838684,120.974244,...,105.042089,105.829707,104.026800,91.996143,128.574882,114.729913,107.554774,130.510348,72.869732,117.584639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,123.531786,111.827755,107.779643,82.168949,160.639754,141.197845,140.466814,118.054020,115.311765,108.883964,...,105.092582,116.499181,108.017102,63.983262,136.902008,119.899001,129.392320,115.266232,108.386809,75.319480
2439,123.851078,116.655550,108.100194,74.078485,145.023257,137.365691,132.357551,125.922760,113.876599,105.546221,...,115.201369,120.309415,107.178216,66.857463,129.040700,112.293239,126.342438,119.304489,102.924841,80.198171
2440,124.844037,107.987896,112.489683,79.497709,144.453616,139.741209,131.974434,112.734939,115.106630,101.798861,...,107.010916,123.180474,115.516488,68.961718,138.727408,117.477414,132.911279,115.787103,112.693310,92.181445
2441,121.997334,111.025481,110.218214,80.971138,153.382936,137.157752,145.942473,103.728702,115.493008,109.567823,...,105.686902,111.360597,108.686738,72.850986,137.977188,115.350605,134.436456,117.627324,112.260333,82.313619
2442,135.537949,113.579156,101.360531,74.057339,147.118505,139.976279,136.489963,116.466831,118.252801,103.166842,...,105.027692,119.419711,106.443638,69.086185,140.365965,119.729570,139.456786,116.487862,108.080218,84.064615

In [4]:
position_data = pd.read_excel('real_positions_Reg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,99.343526,132.086973,81.738024,120.226650,127.621983,141.734180,104.808368,135.708107,100.574201,121.172680,...,100.001333,93.030358,108.610318,80.971633,127.068253,113.273672,102.118525,120.868728,81.395424,119.242231
1,104.733610,136.739848,85.595980,121.531174,128.150768,146.754292,112.456378,142.308630,99.220561,113.623552,...,94.944468,92.532748,102.178885,85.745827,127.498364,101.891695,100.754638,132.995837,81.702073,109.877760
2,102.503893,122.812742,79.306588,116.294374,121.246788,147.866563,114.673974,145.754454,98.140959,113.898725,...,106.442714,104.297185,109.932826,83.496819,130.000814,106.665402,100.613200,124.160411,71.817836,119.550575
3,105.439048,128.212611,91.820230,108.778849,126.667009,154.660799,114.044773,138.616554,103.117246,119.596471,...,102.668226,97.500489,103.068480,85.886335,135.283285,109.376512,105.742410,129.627503,75.726365,114.868672
4,104.124270,136.003305,84.028696,124.663682,135.153193,143.579315,110.567758,136.614045,99.838684,120.974244,...,105.042089,105.829707,104.026800,91.996143,128.574882,114.729913,107.554774,130.510348,72.869732,117.584639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,123.531786,111.827755,107.779643,82.168949,160.639754,141.197845,140.466814,118.054020,115.311765,108.883964,...,105.092582,116.499181,108.017102,63.983262,136.902008,119.899001,129.392320,115.266232,108.386809,75.319480
2439,123.851078,116.655550,108.100194,74.078485,145.023257,137.365691,132.357551,125.922760,113.876599,105.546221,...,115.201369,120.309415,107.178216,66.857463,129.040700,112.293239,126.342438,119.304489,102.924841,80.198171
2440,124.844037,107.987896,112.489683,79.497709,144.453616,139.741209,131.974434,112.734939,115.106630,101.798861,...,107.010916,123.180474,115.516488,68.961718,138.727408,117.477414,132.911279,115.787103,112.693310,92.181445
2441,121.997334,111.025481,110.218214,80.971138,153.382936,137.157752,145.942473,103.728702,115.493008,109.567823,...,105.686902,111.360597,108.686738,72.850986,137.977188,115.350605,134.436456,117.627324,112.260333,82.313619
2442,135.537949,113.579156,101.360531,74.057339,147.118505,139.976279,136.489963,116.466831,118.252801,103.166842,...,105.027692,119.419711,106.443638,69.086185,140.365965,119.729570,139.456786,116.487862,108.080218,84.064615

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 8.66
Fold 1 - Mean Absolute Error (MAE): 2.32
Fold 1 - Root Mean Squared Error (RMSE): 2.94
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 9.48
Fold 2 - Mean Absolute Error (MAE): 2.41
Fold 2 - Root Mean Squared Error (RMSE): 3.08
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 8.61
Fold 3 - Mean Absolute Error (MAE): 2.32
Fold 3 - Root Mean Squared Error (RMSE): 2.93
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 9.60
Fold 4 - Mean Absolute Error (MAE): 2.40
Fold 4 - Root Mean Squared Error (RMSE): 3.10
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 8.81
Fold 5 - Mean Absolute Error (MAE): 2.33
Fold 5 - Root Mean Squared Error (RMSE): 2.97
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 9.03
Mean - Mean Absolute Error (MAE): 2.35
Mean - Root Mean Squared Error (RMSE): 3.00
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 90.80
Fold 1 - Mean Absolute Error (MAE): 6.02
Fold 1 - Root Mean Squared Error (RMSE): 9.53
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 101.99
Fold 2 - Mean Absolute Error (MAE): 6.50
Fold 2 - Root Mean Squared Error (RMSE): 10.10
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 102.99
Fold 3 - Mean Absolute Error (MAE): 6.46
Fold 3 - Root Mean Squared Error (RMSE): 10.15
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 88.41
Fold 4 - Mean Absolute Error (MAE): 5.96
Fold 4 - Root Mean Squared Error (RMSE): 9.40
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 90.28
Fold 5 - Mean Absolute Error (MAE): 5.97
Fold 5 - Root Mean Squared Error (RMSE): 9.50
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 94.89
Mean - Mean Absolute Error (MAE): 6.18
Mean - Root Mean Squared Error (RMSE): 9.74
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 16.84
Fold 1 - Mean Absolute Error (MAE): 3.27
Fold 1 - Root Mean Squared Error (RMSE): 4.10
Fold 1 - Time taken: 2.47 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 18.09
Fold 2 - Mean Absolute Error (MAE): 3.38
Fold 2 - Root Mean Squared Error (RMSE): 4.25
Fold 2 - Time taken: 2.52 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 18.92
Fold 3 - Mean Absolute Error (MAE): 3.44
Fold 3 - Root Mean Squared Error (RMSE): 4.35
Fold 3 - Time taken: 2.51 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 19.17
Fold 4 - Mean Absolute Error (MAE): 3.49
Fold 4 - Root Mean Squared Error (RMSE): 4.38
Fold 4 - Time taken: 2.51 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 19.23
Fold 5 - Mean Absolute Error (MAE): 3.43
Fold 5 - Root Mean Squared Error (RMSE): 4.39
Fold 5 - Time taken: 3.48 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 18.45
Mean - Mean Absolute Error (MAE): 3.40
Mean - Root Mean Squared Error (RMSE): 4.29
Mean - Time taken: 2.70 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 5.11
Fold 1 - Mean Absolute Error (MAE): 1.46
Fold 1 - Root Mean Squared Error (RMSE): 2.26
Fold 1 - Time taken: 0.13 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 5.93
Fold 2 - Mean Absolute Error (MAE): 1.56
Fold 2 - Root Mean Squared Error (RMSE): 2.44
Fold 2 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 5.68
Fold 3 - Mean Absolute Error (MAE): 1.52
Fold 3 - Root Mean Squared Error (RMSE): 2.38
Fold 3 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 6.35
Fold 4 - Mean Absolute Error (MAE): 1.67
Fold 4 - Root Mean Squared Error (RMSE): 2.52
Fold 4 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 5.44
Fold 5 - Mean Absolute Error (MAE): 1.52
Fold 5 - Root Mean Squared Error (RMSE): 2.33
Fold 5 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 5.70
Mean - Mean Absolute Error (MAE): 1.55
Mean - Root Mean Squared Error (RMSE): 2.39
Mean - Time taken: 0.08 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 17.51
Fold 1 - Mean Absolute Error (MAE): 3.08
Fold 1 - Root Mean Squared Error (RMSE): 4.18
Fold 1 - Time taken: 6.12 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 21.69
Fold 2 - Mean Absolute Error (MAE): 3.41
Fold 2 - Root Mean Squared Error (RMSE): 4.66
Fold 2 - Time taken: 6.09 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 21.59
Fold 3 - Mean Absolute Error (MAE): 3.41
Fold 3 - Root Mean Squared Error (RMSE): 4.65
Fold 3 - Time taken: 4.11 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 22.14
Fold 4 - Mean Absolute Error (MAE): 3.45
Fold 4 - Root Mean Squared Error (RMSE): 4.71
Fold 4 - Time taken: 3.42 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 21.57
Fold 5 - Mean Absolute Error (MAE): 3.33
Fold 5 - Root Mean Squared Error (RMSE): 4.64
Fold 5 - Time taken: 1.94 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 20.90
Mean - Mean Absolute Error (MAE): 3.34
Mean - Root Mean Squared Error (RMSE): 4.57
Mean - Time taken: 4.34 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_1_Scattered1_Reg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_1_Scattered1_Reg1.xlsx file")

Results saved to Results__PL_model_1_Scattered1_Reg1.xlsx file