# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_Scattered_Reg2.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,65.730466,89.453682,87.785620,76.587601,84.851017,69.058642,87.202550,71.783088,83.486579,67.510694,...,84.877108,82.619467,79.588797,63.378421,87.883257,81.792326,88.326395,80.556565,65.969870,79.732339
1,66.102980,87.224094,82.082242,81.680587,101.897605,89.818785,81.507159,81.829383,73.644202,84.450240,...,73.485170,91.161226,87.614333,60.744124,102.136423,73.765738,75.956533,76.056711,60.898188,77.393442
2,87.631890,66.257220,80.969001,72.930668,71.620128,94.681804,74.722719,80.515246,87.898047,83.039718,...,67.781748,78.291026,79.990390,70.183516,90.568165,69.355478,85.019282,79.626234,75.902175,84.732731
3,78.862885,70.386298,66.226441,67.022090,82.123529,91.918278,81.225184,81.979229,87.241442,77.722305,...,94.550404,81.172616,72.587516,85.425354,94.797779,84.446558,75.434557,93.011442,69.124145,79.875870
4,78.798557,82.741690,74.042955,94.149286,100.908840,95.783576,79.224920,67.167455,79.834331,80.872271,...,81.381189,69.274949,85.586719,63.042794,83.646354,82.237603,90.288501,81.855912,76.998217,84.330471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,82.108784,81.584543,86.016942,71.404227,101.371020,76.765853,77.869570,88.196777,77.081792,66.228624,...,77.961784,85.777203,84.200662,64.667301,75.258813,77.262059,85.273278,81.702915,68.892345,71.753840
2439,99.805372,85.037790,88.887016,76.925746,96.647426,83.254785,81.911410,77.866264,84.494610,73.992921,...,66.455703,73.287247,68.975757,59.690427,97.523042,72.543085,78.237935,86.620870,82.222681,60.468085
2440,81.841964,78.246787,78.208780,64.264379,78.449603,91.034501,83.279032,71.713930,89.748354,77.469063,...,81.866078,68.809098,72.848124,64.968223,70.571008,83.034651,83.789545,87.322471,70.519879,59.172377
2441,81.833020,81.762443,64.707536,70.649944,82.197035,76.806120,61.982283,97.342958,86.903924,84.735880,...,85.081986,81.865454,96.068783,73.198179,86.111218,88.545774,80.169550,76.045810,74.291673,56.386748
2442,81.962929,85.052762,71.584087,68.405848,73.879542,105.246037,80.553156,87.584474,90.150839,84.384220,...,85.666249,91.608497,69.734030,65.366162,85.565140,91.927970,81.254355,84.759455,74.441114,68.843831

In [4]:
position_data = pd.read_excel('real_positions_Reg2_3.xlsx', header=None)

In [5]:
position_data

              0          1       2
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,65.730466,89.453682,87.785620,76.587601,84.851017,69.058642,87.202550,71.783088,83.486579,67.510694,...,84.877108,82.619467,79.588797,63.378421,87.883257,81.792326,88.326395,80.556565,65.969870,79.732339
1,66.102980,87.224094,82.082242,81.680587,101.897605,89.818785,81.507159,81.829383,73.644202,84.450240,...,73.485170,91.161226,87.614333,60.744124,102.136423,73.765738,75.956533,76.056711,60.898188,77.393442
2,87.631890,66.257220,80.969001,72.930668,71.620128,94.681804,74.722719,80.515246,87.898047,83.039718,...,67.781748,78.291026,79.990390,70.183516,90.568165,69.355478,85.019282,79.626234,75.902175,84.732731
3,78.862885,70.386298,66.226441,67.022090,82.123529,91.918278,81.225184,81.979229,87.241442,77.722305,...,94.550404,81.172616,72.587516,85.425354,94.797779,84.446558,75.434557,93.011442,69.124145,79.875870
4,78.798557,82.741690,74.042955,94.149286,100.908840,95.783576,79.224920,67.167455,79.834331,80.872271,...,81.381189,69.274949,85.586719,63.042794,83.646354,82.237603,90.288501,81.855912,76.998217,84.330471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,82.108784,81.584543,86.016942,71.404227,101.371020,76.765853,77.869570,88.196777,77.081792,66.228624,...,77.961784,85.777203,84.200662,64.667301,75.258813,77.262059,85.273278,81.702915,68.892345,71.753840
2439,99.805372,85.037790,88.887016,76.925746,96.647426,83.254785,81.911410,77.866264,84.494610,73.992921,...,66.455703,73.287247,68.975757,59.690427,97.523042,72.543085,78.237935,86.620870,82.222681,60.468085
2440,81.841964,78.246787,78.208780,64.264379,78.449603,91.034501,83.279032,71.713930,89.748354,77.469063,...,81.866078,68.809098,72.848124,64.968223,70.571008,83.034651,83.789545,87.322471,70.519879,59.172377
2441,81.833020,81.762443,64.707536,70.649944,82.197035,76.806120,61.982283,97.342958,86.903924,84.735880,...,85.081986,81.865454,96.068783,73.198179,86.111218,88.545774,80.169550,76.045810,74.291673,56.386748
2442,81.962929,85.052762,71.584087,68.405848,73.879542,105.246037,80.553156,87.584474,90.150839,84.384220,...,85.666249,91.608497,69.734030,65.366162,85.565140,91.927970,81.254355,84.759455,74.441114,68.843831

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y   Pos Z
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 634.61
Fold 1 - Mean Absolute Error (MAE): 18.97
Fold 1 - Root Mean Squared Error (RMSE): 25.19
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 666.55
Fold 2 - Mean Absolute Error (MAE): 19.37
Fold 2 - Root Mean Squared Error (RMSE): 25.82
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 656.56
Fold 3 - Mean Absolute Error (MAE): 19.20
Fold 3 - Root Mean Squared Error (RMSE): 25.62
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 677.84
Fold 4 - Mean Absolute Error (MAE): 19.24
Fold 4 - Root Mean Squared Error (RMSE): 26.04
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 625.86
Fold 5 - Mean Absolute Error (MAE): 18.70
Fold 5 - Root Mean Squared Error (RMSE): 25.02
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 652.28
Mean - Mean Absolute Error (MAE): 19.10
Mean - Root Mean Squared Error (RMSE): 25.54
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 2383.07
Fold 1 - Mean Absolute Error (MAE): 34.89
Fold 1 - Root Mean Squared Error (RMSE): 48.82
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 2384.95
Fold 2 - Mean Absolute Error (MAE): 34.54
Fold 2 - Root Mean Squared Error (RMSE): 48.84
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 2351.43
Fold 3 - Mean Absolute Error (MAE): 34.88
Fold 3 - Root Mean Squared Error (RMSE): 48.49
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 2257.27
Fold 4 - Mean Absolute Error (MAE): 33.55
Fold 4 - Root Mean Squared Error (RMSE): 47.51
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 2448.12
Fold 5 - Mean Absolute Error (MAE): 35.52
Fold 5 - Root Mean Squared Error (RMSE): 49.48
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 2364.97
Mean - Mean Absolute Error (MAE): 34.68
Mean - Root Mean Squared Error (RMSE): 48.63
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 928.73
Fold 1 - Mean Absolute Error (MAE): 24.12
Fold 1 - Root Mean Squared Error (RMSE): 30.48
Fold 1 - Time taken: 2.76 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 1078.04
Fold 2 - Mean Absolute Error (MAE): 26.06
Fold 2 - Root Mean Squared Error (RMSE): 32.83
Fold 2 - Time taken: 3.20 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 943.56
Fold 3 - Mean Absolute Error (MAE): 24.16
Fold 3 - Root Mean Squared Error (RMSE): 30.72
Fold 3 - Time taken: 4.61 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 938.11
Fold 4 - Mean Absolute Error (MAE): 23.99
Fold 4 - Root Mean Squared Error (RMSE): 30.63
Fold 4 - Time taken: 4.69 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 915.70
Fold 5 - Mean Absolute Error (MAE): 23.73
Fold 5 - Root Mean Squared Error (RMSE): 30.26
Fold 5 - Time taken: 4.66 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 960.83
Mean - Mean Absolute Error (MAE): 24.41
Mean - Root Mean Squared Error (RMSE): 30.98
Mean - Time taken: 3.98 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 888.15
Fold 1 - Mean Absolute Error (MAE): 22.64
Fold 1 - Root Mean Squared Error (RMSE): 29.80
Fold 1 - Time taken: 0.12 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 933.76
Fold 2 - Mean Absolute Error (MAE): 23.04
Fold 2 - Root Mean Squared Error (RMSE): 30.56
Fold 2 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 957.04
Fold 3 - Mean Absolute Error (MAE): 23.28
Fold 3 - Root Mean Squared Error (RMSE): 30.94
Fold 3 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 928.71
Fold 4 - Mean Absolute Error (MAE): 22.92
Fold 4 - Root Mean Squared Error (RMSE): 30.47
Fold 4 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 910.61
Fold 5 - Mean Absolute Error (MAE): 22.78
Fold 5 - Root Mean Squared Error (RMSE): 30.18
Fold 5 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 923.66
Mean - Mean Absolute Error (MAE): 22.93
Mean - Root Mean Squared Error (RMSE): 30.39
Mean - Time taken: 0.08 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 893.14
Fold 1 - Mean Absolute Error (MAE): 21.97
Fold 1 - Root Mean Squared Error (RMSE): 29.89
Fold 1 - Time taken: 6.10 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 896.69
Fold 2 - Mean Absolute Error (MAE): 22.14
Fold 2 - Root Mean Squared Error (RMSE): 29.94
Fold 2 - Time taken: 6.04 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 939.35
Fold 3 - Mean Absolute Error (MAE): 22.89
Fold 3 - Root Mean Squared Error (RMSE): 30.65
Fold 3 - Time taken: 4.17 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 851.02
Fold 4 - Mean Absolute Error (MAE): 21.71
Fold 4 - Root Mean Squared Error (RMSE): 29.17
Fold 4 - Time taken: 2.14 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 879.41
Fold 5 - Mean Absolute Error (MAE): 21.93
Fold 5 - Root Mean Squared Error (RMSE): 29.65
Fold 5 - Time taken: 2.03 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 891.92
Mean - Mean Absolute Error (MAE): 22.13
Mean - Root Mean Squared Error (RMSE): 29.86
Mean - Time taken: 4.10 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_Scattered_Reg2.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_Scattered_Reg2.xlsx file")

Results saved to Results__PL_model_2_Scattered_Reg2.xlsx file