# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing1_Reg2.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,81.498444,82.949532,72.292450,78.184854,87.160717,87.693298,82.182275,80.760157,79.187718,81.339866,...,80.064679,78.171515,82.106537,73.812383,86.066019,82.349210,78.733210,82.015244,68.893959,78.530314
1,81.697645,82.962273,72.234904,78.352839,87.216906,87.847948,82.266603,80.672843,79.419027,81.512788,...,79.852513,78.004756,81.435899,73.807210,86.408953,81.829290,78.494545,81.485288,68.392004,78.748257
2,81.551717,83.174948,72.035674,78.626837,87.394655,87.800263,82.290624,80.764130,79.392759,81.670727,...,80.032185,77.966333,81.786946,73.279978,86.084572,81.660736,78.449728,81.300635,68.229546,78.818975
3,81.699046,83.038355,71.976537,78.345324,87.328610,87.843148,82.061503,80.859499,79.118017,81.414740,...,80.024921,77.971799,81.727698,73.263061,86.523995,81.651011,78.195865,81.068164,68.082362,78.688211
4,81.408114,83.270601,71.871130,78.271196,87.397395,87.929512,81.899852,81.290095,79.368744,81.083667,...,79.699406,78.091290,81.691784,73.450303,86.546988,81.524751,78.304831,81.019206,68.194899,78.876421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,83.496077,82.597947,77.524787,69.156213,88.263204,87.385300,82.655146,81.861468,82.243711,79.634200,...,80.137596,80.480343,80.533231,69.257888,84.927727,81.676751,82.777379,79.399995,73.627692,69.620086
2439,83.520795,83.072028,77.536763,69.136243,88.140034,87.215165,82.334764,82.131792,82.139632,79.844606,...,80.349100,80.748868,80.404138,69.137258,84.520229,81.634801,82.557210,80.076236,73.837362,69.667187
2440,83.949679,83.033286,77.417232,69.010092,87.818193,87.509361,82.180550,82.099336,82.199534,79.835360,...,79.929388,80.940822,80.073954,69.506099,84.832328,81.559572,82.571253,80.015977,73.782259,69.769326
2441,83.919351,83.189580,77.097175,68.704798,87.970331,87.309033,82.015188,82.079340,82.249988,80.074416,...,79.898355,81.275998,79.889942,69.294912,84.869610,81.262911,82.539702,80.218017,73.856783,69.757102
2442,84.160345,82.921134,77.020572,68.435467,87.879249,87.675088,82.407249,82.490998,82.408714,79.763039,...,80.051214,81.265788,80.129362,69.179453,84.669733,81.187163,82.719530,80.106360,74.337690,69.598534

In [4]:
position_data = pd.read_excel('real_positions_Reg2_3.xlsx', header=None)

In [5]:
position_data

              0          1       2
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,81.498444,82.949532,72.292450,78.184854,87.160717,87.693298,82.182275,80.760157,79.187718,81.339866,...,80.064679,78.171515,82.106537,73.812383,86.066019,82.349210,78.733210,82.015244,68.893959,78.530314
1,81.697645,82.962273,72.234904,78.352839,87.216906,87.847948,82.266603,80.672843,79.419027,81.512788,...,79.852513,78.004756,81.435899,73.807210,86.408953,81.829290,78.494545,81.485288,68.392004,78.748257
2,81.551717,83.174948,72.035674,78.626837,87.394655,87.800263,82.290624,80.764130,79.392759,81.670727,...,80.032185,77.966333,81.786946,73.279978,86.084572,81.660736,78.449728,81.300635,68.229546,78.818975
3,81.699046,83.038355,71.976537,78.345324,87.328610,87.843148,82.061503,80.859499,79.118017,81.414740,...,80.024921,77.971799,81.727698,73.263061,86.523995,81.651011,78.195865,81.068164,68.082362,78.688211
4,81.408114,83.270601,71.871130,78.271196,87.397395,87.929512,81.899852,81.290095,79.368744,81.083667,...,79.699406,78.091290,81.691784,73.450303,86.546988,81.524751,78.304831,81.019206,68.194899,78.876421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,83.496077,82.597947,77.524787,69.156213,88.263204,87.385300,82.655146,81.861468,82.243711,79.634200,...,80.137596,80.480343,80.533231,69.257888,84.927727,81.676751,82.777379,79.399995,73.627692,69.620086
2439,83.520795,83.072028,77.536763,69.136243,88.140034,87.215165,82.334764,82.131792,82.139632,79.844606,...,80.349100,80.748868,80.404138,69.137258,84.520229,81.634801,82.557210,80.076236,73.837362,69.667187
2440,83.949679,83.033286,77.417232,69.010092,87.818193,87.509361,82.180550,82.099336,82.199534,79.835360,...,79.929388,80.940822,80.073954,69.506099,84.832328,81.559572,82.571253,80.015977,73.782259,69.769326
2441,83.919351,83.189580,77.097175,68.704798,87.970331,87.309033,82.015188,82.079340,82.249988,80.074416,...,79.898355,81.275998,79.889942,69.294912,84.869610,81.262911,82.539702,80.218017,73.856783,69.757102
2442,84.160345,82.921134,77.020572,68.435467,87.879249,87.675088,82.407249,82.490998,82.408714,79.763039,...,80.051214,81.265788,80.129362,69.179453,84.669733,81.187163,82.719530,80.106360,74.337690,69.598534

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y   Pos Z
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 9.45
Fold 1 - Mean Absolute Error (MAE): 2.34
Fold 1 - Root Mean Squared Error (RMSE): 3.07
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 9.10
Fold 2 - Mean Absolute Error (MAE): 2.34
Fold 2 - Root Mean Squared Error (RMSE): 3.02
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 8.94
Fold 3 - Mean Absolute Error (MAE): 2.29
Fold 3 - Root Mean Squared Error (RMSE): 2.99
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 8.53
Fold 4 - Mean Absolute Error (MAE): 2.24
Fold 4 - Root Mean Squared Error (RMSE): 2.92
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 9.05
Fold 5 - Mean Absolute Error (MAE): 2.31
Fold 5 - Root Mean Squared Error (RMSE): 3.01
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 9.01
Mean - Mean Absolute Error (MAE): 2.30
Mean - Root Mean Squared Error (RMSE): 3.00
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 25.26
Fold 1 - Mean Absolute Error (MAE): 1.38
Fold 1 - Root Mean Squared Error (RMSE): 5.03
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 14.64
Fold 2 - Mean Absolute Error (MAE): 1.11
Fold 2 - Root Mean Squared Error (RMSE): 3.83
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 6.63
Fold 3 - Mean Absolute Error (MAE): 0.86
Fold 3 - Root Mean Squared Error (RMSE): 2.57
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 12.16
Fold 4 - Mean Absolute Error (MAE): 1.06
Fold 4 - Root Mean Squared Error (RMSE): 3.49
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 9.97
Fold 5 - Mean Absolute Error (MAE): 0.96
Fold 5 - Root Mean Squared Error (RMSE): 3.16
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 13.73
Mean - Mean Absolute Error (MAE): 1.08
Mean - Root Mean Squared Error (RMSE): 3.61
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 2.44
Fold 1 - Mean Absolute Error (MAE): 0.64
Fold 1 - Root Mean Squared Error (RMSE): 1.56
Fold 1 - Time taken: 2.41 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 1.59
Fold 2 - Mean Absolute Error (MAE): 0.59
Fold 2 - Root Mean Squared Error (RMSE): 1.26
Fold 2 - Time taken: 2.37 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 1.54
Fold 3 - Mean Absolute Error (MAE): 0.60
Fold 3 - Root Mean Squared Error (RMSE): 1.24
Fold 3 - Time taken: 3.75 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 1.86
Fold 4 - Mean Absolute Error (MAE): 0.64
Fold 4 - Root Mean Squared Error (RMSE): 1.36
Fold 4 - Time taken: 3.90 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 2.06
Fold 5 - Mean Absolute Error (MAE): 0.63
Fold 5 - Root Mean Squared Error (RMSE): 1.44
Fold 5 - Time taken: 4.00 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 1.90
Mean - Mean Absolute Error (MAE): 0.62
Mean - Root Mean Squared Error (RMSE): 1.37
Mean - Time taken: 3.29 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.12
Fold 1 - Mean Absolute Error (MAE): 0.22
Fold 1 - Root Mean Squared Error (RMSE): 0.35
Fold 1 - Time taken: 0.12 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.15
Fold 2 - Mean Absolute Error (MAE): 0.23
Fold 2 - Root Mean Squared Error (RMSE): 0.38
Fold 2 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.19
Fold 3 - Mean Absolute Error (MAE): 0.25
Fold 3 - Root Mean Squared Error (RMSE): 0.44
Fold 3 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.15
Fold 4 - Mean Absolute Error (MAE): 0.23
Fold 4 - Root Mean Squared Error (RMSE): 0.39
Fold 4 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.18
Fold 5 - Mean Absolute Error (MAE): 0.25
Fold 5 - Root Mean Squared Error (RMSE): 0.42
Fold 5 - Time taken: 0.04 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.16
Mean - Mean Absolute Error (MAE): 0.24
Mean - Root Mean Squared Error (RMSE): 0.40
Mean - Time taken: 0.07 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 3.57
Fold 1 - Mean Absolute Error (MAE): 1.08
Fold 1 - Root Mean Squared Error (RMSE): 1.89
Fold 1 - Time taken: 4.78 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 5.46
Fold 2 - Mean Absolute Error (MAE): 1.15
Fold 2 - Root Mean Squared Error (RMSE): 2.34
Fold 2 - Time taken: 4.87 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 5.89
Fold 3 - Mean Absolute Error (MAE): 1.20
Fold 3 - Root Mean Squared Error (RMSE): 2.43
Fold 3 - Time taken: 5.22 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 3.79
Fold 4 - Mean Absolute Error (MAE): 1.14
Fold 4 - Root Mean Squared Error (RMSE): 1.95
Fold 4 - Time taken: 5.09 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 4.28
Fold 5 - Mean Absolute Error (MAE): 1.12
Fold 5 - Root Mean Squared Error (RMSE): 2.07
Fold 5 - Time taken: 3.49 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 4.60
Mean - Mean Absolute Error (MAE): 1.14
Mean - Root Mean Squared Error (RMSE): 2.13
Mean - Time taken: 4.69 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing1_Reg2.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing1_Reg2.xlsx file")

Results saved to Results__PL_model_2_smoothing1_Reg2.xlsx file