# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing2_Reg2.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,78.632971,81.399266,77.250888,77.881737,87.606491,90.878011,83.683674,76.939886,77.811940,79.216417,...,80.122692,77.439776,80.094806,69.037217,92.465980,80.227891,82.639231,81.956382,68.796643,79.465122
1,78.894162,81.456455,76.972121,77.906493,87.566765,90.759398,83.613337,77.200645,77.859044,79.324864,...,80.102728,77.443129,80.208063,69.342133,92.073577,80.326154,82.357046,81.884584,68.953000,79.397995
2,79.147814,81.518846,76.695525,77.930667,87.527735,90.642030,83.540562,77.458909,77.911848,79.433134,...,80.082263,77.453403,80.322355,69.643368,91.684261,80.420395,82.077674,81.811890,69.101216,79.332075
3,79.394387,81.586233,76.420343,77.954146,87.489211,90.526372,83.465142,77.714454,77.970389,79.541525,...,80.061302,77.470195,80.437383,69.941393,91.298301,80.510691,81.801362,81.738656,69.241014,79.267396
4,79.634173,81.658761,76.145646,77.977021,87.451288,90.412748,83.387176,77.966851,78.034360,79.650200,...,80.040164,77.492911,80.552828,70.236678,90.915933,80.597446,81.528380,81.665320,69.371942,79.203816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,81.085500,83.269269,77.997856,67.669686,87.586293,86.693977,79.712469,83.950738,84.346201,78.132821,...,79.811065,81.004474,78.294866,67.316514,82.950869,80.483248,83.071120,81.965866,75.374322,65.513829
2439,80.871869,83.367393,78.059860,67.583630,87.631434,86.606911,79.477164,84.132178,84.549588,78.050669,...,79.786175,80.986456,78.193919,67.210842,82.792298,80.468536,83.056954,82.122991,75.464144,65.102826
2440,80.656301,83.466033,78.125031,67.499484,87.677524,86.518893,79.242501,84.317854,84.758155,77.968463,...,79.761260,80.965988,78.090956,67.102590,82.633703,80.454453,83.036478,82.281210,75.548762,64.685126
2441,80.439400,83.564900,78.192290,67.417331,87.723150,86.430248,79.008253,84.507677,84.972099,77.886868,...,79.737010,80.943514,77.985717,66.991973,82.475239,80.441972,83.009817,82.440347,75.628233,64.260938
2442,80.221609,83.663892,78.260620,67.337267,87.767240,86.341214,78.774122,84.701836,85.191428,77.806510,...,79.714033,80.919808,77.878151,66.879278,82.317245,80.431920,82.977138,82.600111,75.702741,63.830729

In [4]:
position_data = pd.read_excel('real_positions_Reg2_3.xlsx', header=None)

In [5]:
position_data

              0          1       2
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,78.632971,81.399266,77.250888,77.881737,87.606491,90.878011,83.683674,76.939886,77.811940,79.216417,...,80.122692,77.439776,80.094806,69.037217,92.465980,80.227891,82.639231,81.956382,68.796643,79.465122
1,78.894162,81.456455,76.972121,77.906493,87.566765,90.759398,83.613337,77.200645,77.859044,79.324864,...,80.102728,77.443129,80.208063,69.342133,92.073577,80.326154,82.357046,81.884584,68.953000,79.397995
2,79.147814,81.518846,76.695525,77.930667,87.527735,90.642030,83.540562,77.458909,77.911848,79.433134,...,80.082263,77.453403,80.322355,69.643368,91.684261,80.420395,82.077674,81.811890,69.101216,79.332075
3,79.394387,81.586233,76.420343,77.954146,87.489211,90.526372,83.465142,77.714454,77.970389,79.541525,...,80.061302,77.470195,80.437383,69.941393,91.298301,80.510691,81.801362,81.738656,69.241014,79.267396
4,79.634173,81.658761,76.145646,77.977021,87.451288,90.412748,83.387176,77.966851,78.034360,79.650200,...,80.040164,77.492911,80.552828,70.236678,90.915933,80.597446,81.528380,81.665320,69.371942,79.203816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,81.085500,83.269269,77.997856,67.669686,87.586293,86.693977,79.712469,83.950738,84.346201,78.132821,...,79.811065,81.004474,78.294866,67.316514,82.950869,80.483248,83.071120,81.965866,75.374322,65.513829
2439,80.871869,83.367393,78.059860,67.583630,87.631434,86.606911,79.477164,84.132178,84.549588,78.050669,...,79.786175,80.986456,78.193919,67.210842,82.792298,80.468536,83.056954,82.122991,75.464144,65.102826
2440,80.656301,83.466033,78.125031,67.499484,87.677524,86.518893,79.242501,84.317854,84.758155,77.968463,...,79.761260,80.965988,78.090956,67.102590,82.633703,80.454453,83.036478,82.281210,75.548762,64.685126
2441,80.439400,83.564900,78.192290,67.417331,87.723150,86.430248,79.008253,84.507677,84.972099,77.886868,...,79.737010,80.943514,77.985717,66.991973,82.475239,80.441972,83.009817,82.440347,75.628233,64.260938
2442,80.221609,83.663892,78.260620,67.337267,87.767240,86.341214,78.774122,84.701836,85.191428,77.806510,...,79.714033,80.919808,77.878151,66.879278,82.317245,80.431920,82.977138,82.600111,75.702741,63.830729

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y   Pos Z
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 24.46
Fold 1 - Mean Absolute Error (MAE): 3.83
Fold 1 - Root Mean Squared Error (RMSE): 4.95
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 23.75
Fold 2 - Mean Absolute Error (MAE): 3.70
Fold 2 - Root Mean Squared Error (RMSE): 4.87
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 22.54
Fold 3 - Mean Absolute Error (MAE): 3.62
Fold 3 - Root Mean Squared Error (RMSE): 4.75
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 25.06
Fold 4 - Mean Absolute Error (MAE): 3.74
Fold 4 - Root Mean Squared Error (RMSE): 5.01
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 23.72
Fold 5 - Mean Absolute Error (MAE): 3.64
Fold 5 - Root Mean Squared Error (RMSE): 4.87
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 23.90
Mean - Mean Absolute Error (MAE): 3.71
Mean - Root Mean Squared Error (RMSE): 4.89
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 5.48
Fold 1 - Mean Absolute Error (MAE): 0.60
Fold 1 - Root Mean Squared Error (RMSE): 2.34
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 11.06
Fold 2 - Mean Absolute Error (MAE): 0.74
Fold 2 - Root Mean Squared Error (RMSE): 3.33
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 14.13
Fold 3 - Mean Absolute Error (MAE): 0.86
Fold 3 - Root Mean Squared Error (RMSE): 3.76
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 12.64
Fold 4 - Mean Absolute Error (MAE): 0.75
Fold 4 - Root Mean Squared Error (RMSE): 3.55
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 19.31
Fold 5 - Mean Absolute Error (MAE): 0.71
Fold 5 - Root Mean Squared Error (RMSE): 4.39
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 12.52
Mean - Mean Absolute Error (MAE): 0.73
Mean - Root Mean Squared Error (RMSE): 3.47
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 1.70
Fold 1 - Mean Absolute Error (MAE): 0.53
Fold 1 - Root Mean Squared Error (RMSE): 1.30
Fold 1 - Time taken: 2.39 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 1.70
Fold 2 - Mean Absolute Error (MAE): 0.53
Fold 2 - Root Mean Squared Error (RMSE): 1.31
Fold 2 - Time taken: 2.39 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 3.70
Fold 3 - Mean Absolute Error (MAE): 0.61
Fold 3 - Root Mean Squared Error (RMSE): 1.92
Fold 3 - Time taken: 3.93 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 3.13
Fold 4 - Mean Absolute Error (MAE): 0.48
Fold 4 - Root Mean Squared Error (RMSE): 1.77
Fold 4 - Time taken: 3.80 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 6.30
Fold 5 - Mean Absolute Error (MAE): 0.64
Fold 5 - Root Mean Squared Error (RMSE): 2.51
Fold 5 - Time taken: 3.86 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 3.31
Mean - Mean Absolute Error (MAE): 0.56
Mean - Root Mean Squared Error (RMSE): 1.76
Mean - Time taken: 3.27 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.09
Fold 1 - Mean Absolute Error (MAE): 0.18
Fold 1 - Root Mean Squared Error (RMSE): 0.29
Fold 1 - Time taken: 0.09 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.11
Fold 2 - Mean Absolute Error (MAE): 0.20
Fold 2 - Root Mean Squared Error (RMSE): 0.33
Fold 2 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.12
Fold 3 - Mean Absolute Error (MAE): 0.21
Fold 3 - Root Mean Squared Error (RMSE): 0.35
Fold 3 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.11
Fold 4 - Mean Absolute Error (MAE): 0.20
Fold 4 - Root Mean Squared Error (RMSE): 0.33
Fold 4 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.13
Fold 5 - Mean Absolute Error (MAE): 0.21
Fold 5 - Root Mean Squared Error (RMSE): 0.36
Fold 5 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.11
Mean - Mean Absolute Error (MAE): 0.20
Mean - Root Mean Squared Error (RMSE): 0.33
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 4.12
Fold 1 - Mean Absolute Error (MAE): 0.88
Fold 1 - Root Mean Squared Error (RMSE): 2.03
Fold 1 - Time taken: 3.64 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 4.23
Fold 2 - Mean Absolute Error (MAE): 0.83
Fold 2 - Root Mean Squared Error (RMSE): 2.06
Fold 2 - Time taken: 4.62 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 3.31
Fold 3 - Mean Absolute Error (MAE): 0.87
Fold 3 - Root Mean Squared Error (RMSE): 1.82
Fold 3 - Time taken: 4.78 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 3.68
Fold 4 - Mean Absolute Error (MAE): 0.90
Fold 4 - Root Mean Squared Error (RMSE): 1.92
Fold 4 - Time taken: 4.97 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 3.40
Fold 5 - Mean Absolute Error (MAE): 0.88
Fold 5 - Root Mean Squared Error (RMSE): 1.84
Fold 5 - Time taken: 5.09 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 3.75
Mean - Mean Absolute Error (MAE): 0.87
Mean - Root Mean Squared Error (RMSE): 1.93
Mean - Time taken: 4.62 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing2_Reg2.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing2_Reg2.xlsx file")

Results saved to Results__PL_model_2_smoothing2_Reg2.xlsx file