# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_Scattered_iReg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,77.406007,85.465645,46.676435,57.403574,66.385077,83.755009,60.222991,81.731340,54.146807,72.026821,...,58.654447,55.586006,59.621294,61.886111,90.600231,71.045191,58.392011,72.109779,54.770557,61.238352
1,64.351704,73.971619,49.717074,71.733702,72.604477,74.323361,71.642854,81.550451,54.828538,74.455141,...,56.141836,66.074063,59.301755,74.178376,73.527994,77.744891,69.881647,76.405338,47.770099,68.878286
2,64.878892,64.809892,69.192530,70.355513,68.884789,59.777149,65.629420,94.242576,57.244828,65.010419,...,63.968113,66.679467,52.122820,61.039546,62.873698,86.699905,63.250734,78.284037,55.390484,66.183183
3,63.316636,80.498511,64.441418,56.912369,66.358069,86.564540,76.867275,76.334062,67.969230,76.411697,...,57.043472,63.030395,59.615085,56.388748,64.602431,64.466087,72.581645,66.845638,58.829371,75.603256
4,69.911923,68.179991,67.936123,68.450759,70.633028,70.152683,68.569243,70.124111,51.508900,63.318079,...,59.409446,62.687461,51.773093,60.071736,72.803066,88.221204,64.157324,72.880851,49.007566,70.516981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,75.420924,72.983297,72.293340,70.574890,89.053725,84.569350,66.739765,72.234099,81.076902,80.482844,...,83.150568,65.953377,48.117080,49.682031,81.110885,58.450963,79.666812,77.889462,64.789617,52.903472
2439,72.586272,59.022907,72.990713,58.263311,80.833146,77.615216,67.822218,78.501928,68.473403,66.975001,...,67.039936,62.654153,53.132274,52.359962,60.410200,66.332568,61.709596,65.257602,75.843347,61.268631
2440,56.283441,73.072358,66.997185,62.548293,65.700286,61.067226,61.145387,75.482207,65.980870,59.776324,...,66.367211,71.064424,64.243497,46.093524,64.877998,79.549095,72.639319,74.272992,66.682511,64.059545
2441,77.908145,72.319050,76.136647,48.914493,67.858274,81.550251,74.442318,55.323266,60.177985,59.097731,...,71.733504,71.091485,67.318279,60.271055,80.732961,65.210486,67.417776,68.806994,66.393003,56.498697
2442,72.498225,64.546306,67.043324,53.831131,80.916082,69.252684,74.697408,71.993410,88.466893,74.215926,...,55.230278,68.590599,67.672809,57.354662,58.927945,71.631605,69.682465,78.281842,51.802674,62.521953

In [4]:
position_data = pd.read_excel('real_positions_iReg3.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,77.406007,85.465645,46.676435,57.403574,66.385077,83.755009,60.222991,81.731340,54.146807,72.026821,...,58.654447,55.586006,59.621294,61.886111,90.600231,71.045191,58.392011,72.109779,54.770557,61.238352
1,64.351704,73.971619,49.717074,71.733702,72.604477,74.323361,71.642854,81.550451,54.828538,74.455141,...,56.141836,66.074063,59.301755,74.178376,73.527994,77.744891,69.881647,76.405338,47.770099,68.878286
2,64.878892,64.809892,69.192530,70.355513,68.884789,59.777149,65.629420,94.242576,57.244828,65.010419,...,63.968113,66.679467,52.122820,61.039546,62.873698,86.699905,63.250734,78.284037,55.390484,66.183183
3,63.316636,80.498511,64.441418,56.912369,66.358069,86.564540,76.867275,76.334062,67.969230,76.411697,...,57.043472,63.030395,59.615085,56.388748,64.602431,64.466087,72.581645,66.845638,58.829371,75.603256
4,69.911923,68.179991,67.936123,68.450759,70.633028,70.152683,68.569243,70.124111,51.508900,63.318079,...,59.409446,62.687461,51.773093,60.071736,72.803066,88.221204,64.157324,72.880851,49.007566,70.516981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,75.420924,72.983297,72.293340,70.574890,89.053725,84.569350,66.739765,72.234099,81.076902,80.482844,...,83.150568,65.953377,48.117080,49.682031,81.110885,58.450963,79.666812,77.889462,64.789617,52.903472
2439,72.586272,59.022907,72.990713,58.263311,80.833146,77.615216,67.822218,78.501928,68.473403,66.975001,...,67.039936,62.654153,53.132274,52.359962,60.410200,66.332568,61.709596,65.257602,75.843347,61.268631
2440,56.283441,73.072358,66.997185,62.548293,65.700286,61.067226,61.145387,75.482207,65.980870,59.776324,...,66.367211,71.064424,64.243497,46.093524,64.877998,79.549095,72.639319,74.272992,66.682511,64.059545
2441,77.908145,72.319050,76.136647,48.914493,67.858274,81.550251,74.442318,55.323266,60.177985,59.097731,...,71.733504,71.091485,67.318279,60.271055,80.732961,65.210486,67.417776,68.806994,66.393003,56.498697
2442,72.498225,64.546306,67.043324,53.831131,80.916082,69.252684,74.697408,71.993410,88.466893,74.215926,...,55.230278,68.590599,67.672809,57.354662,58.927945,71.631605,69.682465,78.281842,51.802674,62.521953

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 32

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:32]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor23,sensor24,sensor25,sensor26,sensor27,sensor28,sensor29,sensor30,sensor31,sensor32
0,77.406007,85.465645,46.676435,57.403574,66.385077,83.755009,60.222991,81.731340,54.146807,72.026821,...,58.812423,71.404198,47.832419,65.726095,67.089594,70.302963,65.682749,66.716625,58.904427,71.036087
1,64.351704,73.971619,49.717074,71.733702,72.604477,74.323361,71.642854,81.550451,54.828538,74.455141,...,64.235175,82.468107,59.463758,59.171734,70.880318,80.435762,52.871830,69.075926,71.131244,68.511205
2,64.878892,64.809892,69.192530,70.355513,68.884789,59.777149,65.629420,94.242576,57.244828,65.010419,...,59.436072,74.805248,47.468523,64.008130,60.704825,63.317536,48.372077,79.884726,75.867919,70.213338
3,63.316636,80.498511,64.441418,56.912369,66.358069,86.564540,76.867275,76.334062,67.969230,76.411697,...,62.059686,61.364318,33.961042,78.945116,63.217072,61.489165,58.833700,65.120987,63.594367,63.573928
4,69.911923,68.179991,67.936123,68.450759,70.633028,70.152683,68.569243,70.124111,51.508900,63.318079,...,59.233611,69.001106,43.915973,52.637016,50.069315,61.037560,64.138415,61.856477,71.930397,77.183510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,75.420924,72.983297,72.293340,70.574890,89.053725,84.569350,66.739765,72.234099,81.076902,80.482844,...,70.805850,69.981446,69.461109,42.236492,61.996557,65.408369,70.183335,62.798858,67.790341,96.805943
2439,72.586272,59.022907,72.990713,58.263311,80.833146,77.615216,67.822218,78.501928,68.473403,66.975001,...,66.572605,63.060652,65.050301,24.141638,71.749892,52.979378,60.774102,72.822553,70.744083,83.781906
2440,56.283441,73.072358,66.997185,62.548293,65.700286,61.067226,61.145387,75.482207,65.980870,59.776324,...,82.151058,67.991846,50.612596,27.230988,56.344043,55.151609,64.529655,57.961591,73.934881,63.761236
2441,77.908145,72.319050,76.136647,48.914493,67.858274,81.550251,74.442318,55.323266,60.177985,59.097731,...,70.487396,53.900614,52.688039,48.473064,58.996558,56.647934,51.088288,59.398538,82.964955,78.060482
2442,72.498225,64.546306,67.043324,53.831131,80.916082,69.252684,74.697408,71.993410,88.466893,74.215926,...,74.587932,70.359590,71.775835,25.606970,71.087072,46.386048,70.989702,62.282244,68.680156,65.591319

# Importing Libraries

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [15]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

In [16]:
X

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor23,sensor24,sensor25,sensor26,sensor27,sensor28,sensor29,sensor30,sensor31,sensor32
0,77.406007,85.465645,46.676435,57.403574,66.385077,83.755009,60.222991,81.731340,54.146807,72.026821,...,58.812423,71.404198,47.832419,65.726095,67.089594,70.302963,65.682749,66.716625,58.904427,71.036087
1,64.351704,73.971619,49.717074,71.733702,72.604477,74.323361,71.642854,81.550451,54.828538,74.455141,...,64.235175,82.468107,59.463758,59.171734,70.880318,80.435762,52.871830,69.075926,71.131244,68.511205
2,64.878892,64.809892,69.192530,70.355513,68.884789,59.777149,65.629420,94.242576,57.244828,65.010419,...,59.436072,74.805248,47.468523,64.008130,60.704825,63.317536,48.372077,79.884726,75.867919,70.213338
3,63.316636,80.498511,64.441418,56.912369,66.358069,86.564540,76.867275,76.334062,67.969230,76.411697,...,62.059686,61.364318,33.961042,78.945116,63.217072,61.489165,58.833700,65.120987,63.594367,63.573928
4,69.911923,68.179991,67.936123,68.450759,70.633028,70.152683,68.569243,70.124111,51.508900,63.318079,...,59.233611,69.001106,43.915973,52.637016,50.069315,61.037560,64.138415,61.856477,71.930397,77.183510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,75.420924,72.983297,72.293340,70.574890,89.053725,84.569350,66.739765,72.234099,81.076902,80.482844,...,70.805850,69.981446,69.461109,42.236492,61.996557,65.408369,70.183335,62.798858,67.790341,96.805943
2439,72.586272,59.022907,72.990713,58.263311,80.833146,77.615216,67.822218,78.501928,68.473403,66.975001,...,66.572605,63.060652,65.050301,24.141638,71.749892,52.979378,60.774102,72.822553,70.744083,83.781906
2440,56.283441,73.072358,66.997185,62.548293,65.700286,61.067226,61.145387,75.482207,65.980870,59.776324,...,82.151058,67.991846,50.612596,27.230988,56.344043,55.151609,64.529655,57.961591,73.934881,63.761236
2441,77.908145,72.319050,76.136647,48.914493,67.858274,81.550251,74.442318,55.323266,60.177985,59.097731,...,70.487396,53.900614,52.688039,48.473064,58.996558,56.647934,51.088288,59.398538,82.964955,78.060482
2442,72.498225,64.546306,67.043324,53.831131,80.916082,69.252684,74.697408,71.993410,88.466893,74.215926,...,74.587932,70.359590,71.775835,25.606970,71.087072,46.386048,70.989702,62.282244,68.680156,65.591319

In [17]:
y

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Define models

In [18]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [19]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [20]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [21]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 174.44
Fold 1 - Mean Absolute Error (MAE): 10.62
Fold 1 - Root Mean Squared Error (RMSE): 13.21
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 175.07
Fold 2 - Mean Absolute Error (MAE): 10.65
Fold 2 - Root Mean Squared Error (RMSE): 13.23
Fold 2 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 176.32
Fold 3 - Mean Absolute Error (MAE): 10.65
Fold 3 - Root Mean Squared Error (RMSE): 13.28
Fold 3 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 182.81
Fold 4 - Mean Absolute Error (MAE): 10.90
Fold 4 - Root Mean Squared Error (RMSE): 13.52
Fold 4 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 181.57
Fold 5 - Mean Absolute Error (MAE): 10.89
Fold 5 - Root Mean Squared Error (RMSE): 13.47
Fold 5 - Time taken: 0.00 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 178.04
Mean - Mean Absolute Error (MAE): 10.74
Mean - Root Mean Squared Error (RMSE): 13.34
Mean - Time taken: 0.00 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 525.54
Fold 1 - Mean Absolute Error (MAE): 16.68
Fold 1 - Root Mean Squared Error (RMSE): 22.92
Fold 1 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 511.53
Fold 2 - Mean Absolute Error (MAE): 16.77
Fold 2 - Root Mean Squared Error (RMSE): 22.62
Fold 2 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 546.05
Fold 3 - Mean Absolute Error (MAE): 17.36
Fold 3 - Root Mean Squared Error (RMSE): 23.37
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 595.33
Fold 4 - Mean Absolute Error (MAE): 18.06
Fold 4 - Root Mean Squared Error (RMSE): 24.40
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 536.43
Fold 5 - Mean Absolute Error (MAE): 17.25
Fold 5 - Root Mean Squared Error (RMSE): 23.16
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 542.98
Mean - Mean Absolute Error (MAE): 17.23
Mean - Root Mean Squared Error (RMSE): 23.29
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 213.05
Fold 1 - Mean Absolute Error (MAE): 11.99
Fold 1 - Root Mean Squared Error (RMSE): 14.60
Fold 1 - Time taken: 1.97 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 224.57
Fold 2 - Mean Absolute Error (MAE): 12.30
Fold 2 - Root Mean Squared Error (RMSE): 14.99
Fold 2 - Time taken: 1.96 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 221.00
Fold 3 - Mean Absolute Error (MAE): 12.21
Fold 3 - Root Mean Squared Error (RMSE): 14.87
Fold 3 - Time taken: 2.66 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 232.83
Fold 4 - Mean Absolute Error (MAE): 12.43
Fold 4 - Root Mean Squared Error (RMSE): 15.26
Fold 4 - Time taken: 3.04 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 220.35
Fold 5 - Mean Absolute Error (MAE): 12.00
Fold 5 - Root Mean Squared Error (RMSE): 14.84
Fold 5 - Time taken: 3.00 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 222.36
Mean - Mean Absolute Error (MAE): 12.19
Mean - Root Mean Squared Error (RMSE): 14.91
Mean - Time taken: 2.52 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 208.29
Fold 1 - Mean Absolute Error (MAE): 11.39
Fold 1 - Root Mean Squared Error (RMSE): 14.43
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 213.62
Fold 2 - Mean Absolute Error (MAE): 11.67
Fold 2 - Root Mean Squared Error (RMSE): 14.62
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 201.73
Fold 3 - Mean Absolute Error (MAE): 11.24
Fold 3 - Root Mean Squared Error (RMSE): 14.20
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 207.23
Fold 4 - Mean Absolute Error (MAE): 11.63
Fold 4 - Root Mean Squared Error (RMSE): 14.40
Fold 4 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 206.46
Fold 5 - Mean Absolute Error (MAE): 11.32
Fold 5 - Root Mean Squared Error (RMSE): 14.37
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 207.46
Mean - Mean Absolute Error (MAE): 11.45
Mean - Root Mean Squared Error (RMSE): 14.40
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 201.76
Fold 1 - Mean Absolute Error (MAE): 11.25
Fold 1 - Root Mean Squared Error (RMSE): 14.20
Fold 1 - Time taken: 3.14 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 226.03
Fold 2 - Mean Absolute Error (MAE): 11.73
Fold 2 - Root Mean Squared Error (RMSE): 15.03
Fold 2 - Time taken: 3.79 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 226.56
Fold 3 - Mean Absolute Error (MAE): 11.97
Fold 3 - Root Mean Squared Error (RMSE): 15.05
Fold 3 - Time taken: 4.31 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 222.69
Fold 4 - Mean Absolute Error (MAE): 11.57
Fold 4 - Root Mean Squared Error (RMSE): 14.92
Fold 4 - Time taken: 4.32 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 218.69
Fold 5 - Mean Absolute Error (MAE): 11.53
Fold 5 - Root Mean Squared Error (RMSE): 14.79
Fold 5 - Time taken: 4.36 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 219.14
Mean - Mean Absolute Error (MAE): 11.61
Mean - Root Mean Squared Error (RMSE): 14.80
Mean - Time taken: 3.98 seconds

# Saving the Mean results to an Excel file

In [22]:
# Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

# Filter the dataframe to include only the mean values
mean_results_df = results_df[results_df["Fold"] == "Mean"]

# Save the mean results to an Excel file
mean_results_df.to_excel("(1-32) Sensors PL_model_2_Scattered_iReg3 results.xlsx", index=False)