# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing2_iReg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,69.448072,71.866212,55.379099,67.169250,68.703894,73.546136,67.810228,77.510547,61.298868,68.717478,...,59.015999,62.518813,59.411256,60.758988,68.038102,72.988410,63.830242,75.252439,52.602491,67.851956
1,69.418672,71.935271,55.344122,67.311666,68.862156,73.638498,67.636949,77.055207,61.417464,68.656037,...,59.062238,62.619356,59.705588,60.845566,67.996626,72.754005,63.917271,75.285079,52.570382,67.864368
2,69.389637,72.007924,55.310861,67.452753,69.019299,73.733994,67.468015,76.608876,61.529876,68.599884,...,59.111119,62.720162,59.994576,60.937070,67.958247,72.523518,64.005781,75.315011,52.539130,67.878903
3,69.360882,72.083804,55.280242,67.592834,69.175079,73.832377,67.304084,76.171754,61.636534,68.548849,...,59.162988,62.821366,60.277882,61.033224,67.922592,72.296890,64.095845,75.342087,52.508766,67.896058
4,69.332575,72.162679,55.252883,67.732185,69.329214,73.933638,67.145806,75.743710,61.738066,68.502746,...,59.218087,62.922934,60.555414,61.133664,67.889440,72.073711,64.187436,75.366102,52.479200,67.916340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,71.350987,70.538258,68.544841,53.906213,73.763653,76.608353,69.085982,71.842437,70.823796,62.002797,...,66.743266,68.095627,59.788287,55.782259,73.302487,69.777199,70.634276,72.344860,66.105552,57.730447
2439,71.073659,70.368423,68.696703,53.930584,73.653961,76.505011,68.987498,71.977737,71.021247,61.899134,...,66.884332,68.147865,59.701153,55.875421,73.314650,69.681036,70.473344,72.306974,66.184077,57.778432
2440,70.796726,70.197133,68.850197,53.955863,73.544931,76.398826,68.891677,72.111296,71.217271,61.795862,...,67.027974,68.198538,59.614914,55.967148,73.321655,69.583333,70.310319,72.267957,66.266954,57.829265
2441,70.520438,70.024321,69.005341,53.982231,73.436429,76.289524,68.798594,72.242943,71.411729,61.693438,...,67.173718,68.247988,59.530568,56.057411,73.323308,69.484466,70.145269,72.228032,66.353304,57.883165
2442,70.245255,69.849882,69.162132,54.009588,73.328562,76.177104,68.708527,72.372422,71.604788,61.592348,...,67.321086,68.296467,59.448892,56.146465,73.319703,69.384572,69.978262,72.187434,66.442219,57.940128

In [4]:
position_data = pd.read_excel('real_positions_iReg3.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,69.448072,71.866212,55.379099,67.169250,68.703894,73.546136,67.810228,77.510547,61.298868,68.717478,...,59.015999,62.518813,59.411256,60.758988,68.038102,72.988410,63.830242,75.252439,52.602491,67.851956
1,69.418672,71.935271,55.344122,67.311666,68.862156,73.638498,67.636949,77.055207,61.417464,68.656037,...,59.062238,62.619356,59.705588,60.845566,67.996626,72.754005,63.917271,75.285079,52.570382,67.864368
2,69.389637,72.007924,55.310861,67.452753,69.019299,73.733994,67.468015,76.608876,61.529876,68.599884,...,59.111119,62.720162,59.994576,60.937070,67.958247,72.523518,64.005781,75.315011,52.539130,67.878903
3,69.360882,72.083804,55.280242,67.592834,69.175079,73.832377,67.304084,76.171754,61.636534,68.548849,...,59.162988,62.821366,60.277882,61.033224,67.922592,72.296890,64.095845,75.342087,52.508766,67.896058
4,69.332575,72.162679,55.252883,67.732185,69.329214,73.933638,67.145806,75.743710,61.738066,68.502746,...,59.218087,62.922934,60.555414,61.133664,67.889440,72.073711,64.187436,75.366102,52.479200,67.916340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,71.350987,70.538258,68.544841,53.906213,73.763653,76.608353,69.085982,71.842437,70.823796,62.002797,...,66.743266,68.095627,59.788287,55.782259,73.302487,69.777199,70.634276,72.344860,66.105552,57.730447
2439,71.073659,70.368423,68.696703,53.930584,73.653961,76.505011,68.987498,71.977737,71.021247,61.899134,...,66.884332,68.147865,59.701153,55.875421,73.314650,69.681036,70.473344,72.306974,66.184077,57.778432
2440,70.796726,70.197133,68.850197,53.955863,73.544931,76.398826,68.891677,72.111296,71.217271,61.795862,...,67.027974,68.198538,59.614914,55.967148,73.321655,69.583333,70.310319,72.267957,66.266954,57.829265
2441,70.520438,70.024321,69.005341,53.982231,73.436429,76.289524,68.798594,72.242943,71.411729,61.693438,...,67.173718,68.247988,59.530568,56.057411,73.323308,69.484466,70.145269,72.228032,66.353304,57.883165
2442,70.245255,69.849882,69.162132,54.009588,73.328562,76.177104,68.708527,72.372422,71.604788,61.592348,...,67.321086,68.296467,59.448892,56.146465,73.319703,69.384572,69.978262,72.187434,66.442219,57.940128

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 32

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:32]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor23,sensor24,sensor25,sensor26,sensor27,sensor28,sensor29,sensor30,sensor31,sensor32
0,69.448072,71.866212,55.379099,67.169250,68.703894,73.546136,67.810228,77.510547,61.298868,68.717478,...,61.617424,71.352761,44.988390,60.897140,63.941093,64.669714,62.472069,69.532677,66.071604,68.156040
1,69.418672,71.935271,55.344122,67.311666,68.862156,73.638498,67.636949,77.055207,61.417464,68.656037,...,61.417515,71.408016,44.912100,60.950077,63.642115,64.847298,62.567469,69.394385,65.889377,68.318221
2,69.389637,72.007924,55.310861,67.452753,69.019299,73.733994,67.468015,76.608876,61.529876,68.599884,...,61.218926,71.464419,44.841220,61.005044,63.345513,65.025287,62.656474,69.256797,65.710188,68.479716
3,69.360882,72.083804,55.280242,67.592834,69.175079,73.832377,67.304084,76.171754,61.636534,68.548849,...,61.021928,71.521580,44.775412,61.061846,63.051005,65.202738,62.738968,69.120142,65.534390,68.640083
4,69.332575,72.162679,55.252883,67.732185,69.329214,73.933638,67.145806,75.743710,61.738066,68.502746,...,60.826849,71.578954,44.714199,61.120104,62.758331,65.378656,62.815263,68.984412,65.362021,68.798812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,71.350987,70.538258,68.544841,53.906213,73.763653,76.608353,69.085982,71.842437,70.823796,62.002797,...,70.645923,62.372587,62.655147,32.573937,64.538244,57.561803,66.500537,61.011540,73.017234,68.733032
2439,71.073659,70.368423,68.696703,53.930584,73.653961,76.505011,68.987498,71.977737,71.021247,61.899134,...,70.774777,62.370815,62.989742,32.687229,64.456411,57.323991,66.527387,60.791943,73.062015,68.582853
2440,70.796726,70.197133,68.850197,53.955863,73.544931,76.398826,68.891677,72.111296,71.217271,61.795862,...,70.906763,62.371777,63.324557,32.797749,64.373578,57.080766,66.551626,60.574792,73.109695,68.434048
2441,70.520438,70.024321,69.005341,53.982231,73.436429,76.289524,68.798594,72.242943,71.411729,61.693438,...,71.042271,62.375594,63.658953,32.905504,64.289679,56.831862,66.572935,60.359916,73.160283,68.286710
2442,70.245255,69.849882,69.162132,54.009588,73.328562,76.177104,68.708527,72.372422,71.604788,61.592348,...,71.181410,62.382246,63.992725,33.010669,64.204881,56.577137,66.591237,60.147182,73.213698,68.140945

# Importing Libraries

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [15]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

In [16]:
X

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor23,sensor24,sensor25,sensor26,sensor27,sensor28,sensor29,sensor30,sensor31,sensor32
0,69.448072,71.866212,55.379099,67.169250,68.703894,73.546136,67.810228,77.510547,61.298868,68.717478,...,61.617424,71.352761,44.988390,60.897140,63.941093,64.669714,62.472069,69.532677,66.071604,68.156040
1,69.418672,71.935271,55.344122,67.311666,68.862156,73.638498,67.636949,77.055207,61.417464,68.656037,...,61.417515,71.408016,44.912100,60.950077,63.642115,64.847298,62.567469,69.394385,65.889377,68.318221
2,69.389637,72.007924,55.310861,67.452753,69.019299,73.733994,67.468015,76.608876,61.529876,68.599884,...,61.218926,71.464419,44.841220,61.005044,63.345513,65.025287,62.656474,69.256797,65.710188,68.479716
3,69.360882,72.083804,55.280242,67.592834,69.175079,73.832377,67.304084,76.171754,61.636534,68.548849,...,61.021928,71.521580,44.775412,61.061846,63.051005,65.202738,62.738968,69.120142,65.534390,68.640083
4,69.332575,72.162679,55.252883,67.732185,69.329214,73.933638,67.145806,75.743710,61.738066,68.502746,...,60.826849,71.578954,44.714199,61.120104,62.758331,65.378656,62.815263,68.984412,65.362021,68.798812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,71.350987,70.538258,68.544841,53.906213,73.763653,76.608353,69.085982,71.842437,70.823796,62.002797,...,70.645923,62.372587,62.655147,32.573937,64.538244,57.561803,66.500537,61.011540,73.017234,68.733032
2439,71.073659,70.368423,68.696703,53.930584,73.653961,76.505011,68.987498,71.977737,71.021247,61.899134,...,70.774777,62.370815,62.989742,32.687229,64.456411,57.323991,66.527387,60.791943,73.062015,68.582853
2440,70.796726,70.197133,68.850197,53.955863,73.544931,76.398826,68.891677,72.111296,71.217271,61.795862,...,70.906763,62.371777,63.324557,32.797749,64.373578,57.080766,66.551626,60.574792,73.109695,68.434048
2441,70.520438,70.024321,69.005341,53.982231,73.436429,76.289524,68.798594,72.242943,71.411729,61.693438,...,71.042271,62.375594,63.658953,32.905504,64.289679,56.831862,66.572935,60.359916,73.160283,68.286710
2442,70.245255,69.849882,69.162132,54.009588,73.328562,76.177104,68.708527,72.372422,71.604788,61.592348,...,71.181410,62.382246,63.992725,33.010669,64.204881,56.577137,66.591237,60.147182,73.213698,68.140945

In [17]:
y

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Define models

In [18]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [19]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [20]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [21]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 8.53
Fold 1 - Mean Absolute Error (MAE): 2.35
Fold 1 - Root Mean Squared Error (RMSE): 2.92
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 8.52
Fold 2 - Mean Absolute Error (MAE): 2.35
Fold 2 - Root Mean Squared Error (RMSE): 2.92
Fold 2 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 8.69
Fold 3 - Mean Absolute Error (MAE): 2.35
Fold 3 - Root Mean Squared Error (RMSE): 2.95
Fold 3 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 8.71
Fold 4 - Mean Absolute Error (MAE): 2.37
Fold 4 - Root Mean Squared Error (RMSE): 2.95
Fold 4 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 8.61
Fold 5 - Mean Absolute Error (MAE): 2.33
Fold 5 - Root Mean Squared Error (RMSE): 2.93
Fold 5 - Time taken: 0.00 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 8.61
Mean - Mean Absolute Error (MAE): 2.35
Mean - Root Mean Squared Error (RMSE): 2.93
Mean - Time taken: 0.00 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 1.55
Fold 1 - Mean Absolute Error (MAE): 0.41
Fold 1 - Root Mean Squared Error (RMSE): 1.25
Fold 1 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 4.52
Fold 2 - Mean Absolute Error (MAE): 0.50
Fold 2 - Root Mean Squared Error (RMSE): 2.13
Fold 2 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 1.24
Fold 3 - Mean Absolute Error (MAE): 0.41
Fold 3 - Root Mean Squared Error (RMSE): 1.11
Fold 3 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 0.48
Fold 4 - Mean Absolute Error (MAE): 0.31
Fold 4 - Root Mean Squared Error (RMSE): 0.69
Fold 4 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 0.76
Fold 5 - Mean Absolute Error (MAE): 0.34
Fold 5 - Root Mean Squared Error (RMSE): 0.87
Fold 5 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 1.71
Mean - Mean Absolute Error (MAE): 0.39
Mean - Root Mean Squared Error (RMSE): 1.21
Mean - Time taken: 0.03 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.20
Fold 1 - Mean Absolute Error (MAE): 0.22
Fold 1 - Root Mean Squared Error (RMSE): 0.44
Fold 1 - Time taken: 1.54 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.29
Fold 2 - Mean Absolute Error (MAE): 0.25
Fold 2 - Root Mean Squared Error (RMSE): 0.54
Fold 2 - Time taken: 1.55 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.47
Fold 3 - Mean Absolute Error (MAE): 0.27
Fold 3 - Root Mean Squared Error (RMSE): 0.69
Fold 3 - Time taken: 1.56 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.18
Fold 4 - Mean Absolute Error (MAE): 0.22
Fold 4 - Root Mean Squared Error (RMSE): 0.42
Fold 4 - Time taken: 2.44 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.14
Fold 5 - Mean Absolute Error (MAE): 0.22
Fold 5 - Root Mean Squared Error (RMSE): 0.38
Fold 5 - Time taken: 2.59 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.26
Mean - Mean Absolute Error (MAE): 0.24
Mean - Root Mean Squared Error (RMSE): 0.49
Mean - Time taken: 1.94 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.04
Fold 1 - Mean Absolute Error (MAE): 0.13
Fold 1 - Root Mean Squared Error (RMSE): 0.20
Fold 1 - Time taken: 0.10 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.05
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.23
Fold 2 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.06
Fold 3 - Mean Absolute Error (MAE): 0.15
Fold 3 - Root Mean Squared Error (RMSE): 0.24
Fold 3 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.05
Fold 4 - Mean Absolute Error (MAE): 0.14
Fold 4 - Root Mean Squared Error (RMSE): 0.22
Fold 4 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.06
Fold 5 - Mean Absolute Error (MAE): 0.15
Fold 5 - Root Mean Squared Error (RMSE): 0.24
Fold 5 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.05
Mean - Mean Absolute Error (MAE): 0.14
Mean - Root Mean Squared Error (RMSE): 0.23
Mean - Time taken: 0.06 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.62
Fold 1 - Mean Absolute Error (MAE): 0.45
Fold 1 - Root Mean Squared Error (RMSE): 0.79
Fold 1 - Time taken: 3.76 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.80
Fold 2 - Mean Absolute Error (MAE): 0.45
Fold 2 - Root Mean Squared Error (RMSE): 0.89
Fold 2 - Time taken: 3.78 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.33
Fold 3 - Mean Absolute Error (MAE): 0.49
Fold 3 - Root Mean Squared Error (RMSE): 1.15
Fold 3 - Time taken: 3.66 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.71
Fold 4 - Mean Absolute Error (MAE): 0.46
Fold 4 - Root Mean Squared Error (RMSE): 0.84
Fold 4 - Time taken: 3.50 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 0.90
Fold 5 - Mean Absolute Error (MAE): 0.48
Fold 5 - Root Mean Squared Error (RMSE): 0.95
Fold 5 - Time taken: 1.75 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 0.87
Mean - Mean Absolute Error (MAE): 0.46
Mean - Root Mean Squared Error (RMSE): 0.92
Mean - Time taken: 3.29 seconds

# Saving the Mean results to an Excel file

In [22]:
# Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

# Filter the dataframe to include only the mean values
mean_results_df = results_df[results_df["Fold"] == "Mean"]

# Save the mean results to an Excel file
mean_results_df.to_excel("(1-32) Sensors PL_model_2_smoothing2_iReg3 results.xlsx", index=False)