# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_smoothing1_iReg2.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,105.003468,121.918943,72.614668,120.778069,126.091678,138.991005,104.050101,135.784545,100.041306,100.901393,...,101.958929,100.577222,103.695343,84.072031,128.355342,112.074373,101.704719,119.872892,67.473626,117.440874
1,105.288397,121.846958,72.665261,120.994713,126.401543,139.010325,104.538267,135.959707,100.522858,101.269006,...,101.404439,100.193565,104.188435,83.896697,128.754311,112.437843,101.691450,119.810472,68.154669,117.349962
2,105.529054,122.272041,72.698489,121.104146,126.123602,138.590843,104.352239,136.356352,100.430917,101.239155,...,101.578573,100.713249,104.180440,84.098068,129.114644,112.261508,101.608375,119.644478,67.759420,116.806581
3,105.135220,122.530820,72.466250,121.170212,125.649189,138.778514,104.162736,136.389872,100.724891,101.368423,...,101.756930,100.534214,104.070139,84.301517,128.766190,112.045597,101.799057,119.715629,67.431983,116.975926
4,104.978396,122.222707,72.495686,120.114529,126.228204,138.395157,104.254778,136.388414,100.997511,101.669398,...,101.620548,100.593832,104.410458,84.901029,128.075921,112.077857,101.512118,119.616790,67.135372,116.982323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,131.175076,93.135082,101.686180,77.696033,153.034618,128.210562,129.136011,116.500609,120.506940,87.647725,...,107.023833,121.190256,109.167381,72.305893,136.601490,113.073235,132.694225,100.711548,106.702656,81.590547
2439,131.314712,92.910718,101.951012,77.579420,153.121661,128.495347,129.108249,116.254523,120.634790,87.875987,...,106.870128,121.256424,109.294415,72.376148,136.266148,113.064917,132.472667,100.622317,106.638515,81.899383
2440,131.068290,93.001838,102.127088,77.633756,152.924650,128.481487,129.612965,116.127758,120.779996,87.924817,...,106.734718,120.780139,109.539750,72.864727,136.251841,113.140413,132.163429,100.936236,106.697645,81.500206
2441,131.501680,92.504927,101.623617,77.855502,152.834235,128.681416,128.822557,115.798652,120.559853,87.917146,...,106.011231,121.198749,109.048077,72.841395,136.123409,113.512316,132.047130,100.960092,106.831510,81.618212
2442,131.471134,92.285320,101.207837,77.700327,153.292364,129.240958,129.305244,116.090118,120.344506,87.936843,...,105.691064,121.689646,109.025871,73.136904,136.010019,113.655976,132.699088,101.196379,107.320174,81.958724

In [4]:
position_data = pd.read_excel('real_positions_iReg2.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,105.003468,121.918943,72.614668,120.778069,126.091678,138.991005,104.050101,135.784545,100.041306,100.901393,...,101.958929,100.577222,103.695343,84.072031,128.355342,112.074373,101.704719,119.872892,67.473626,117.440874
1,105.288397,121.846958,72.665261,120.994713,126.401543,139.010325,104.538267,135.959707,100.522858,101.269006,...,101.404439,100.193565,104.188435,83.896697,128.754311,112.437843,101.691450,119.810472,68.154669,117.349962
2,105.529054,122.272041,72.698489,121.104146,126.123602,138.590843,104.352239,136.356352,100.430917,101.239155,...,101.578573,100.713249,104.180440,84.098068,129.114644,112.261508,101.608375,119.644478,67.759420,116.806581
3,105.135220,122.530820,72.466250,121.170212,125.649189,138.778514,104.162736,136.389872,100.724891,101.368423,...,101.756930,100.534214,104.070139,84.301517,128.766190,112.045597,101.799057,119.715629,67.431983,116.975926
4,104.978396,122.222707,72.495686,120.114529,126.228204,138.395157,104.254778,136.388414,100.997511,101.669398,...,101.620548,100.593832,104.410458,84.901029,128.075921,112.077857,101.512118,119.616790,67.135372,116.982323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,131.175076,93.135082,101.686180,77.696033,153.034618,128.210562,129.136011,116.500609,120.506940,87.647725,...,107.023833,121.190256,109.167381,72.305893,136.601490,113.073235,132.694225,100.711548,106.702656,81.590547
2439,131.314712,92.910718,101.951012,77.579420,153.121661,128.495347,129.108249,116.254523,120.634790,87.875987,...,106.870128,121.256424,109.294415,72.376148,136.266148,113.064917,132.472667,100.622317,106.638515,81.899383
2440,131.068290,93.001838,102.127088,77.633756,152.924650,128.481487,129.612965,116.127758,120.779996,87.924817,...,106.734718,120.780139,109.539750,72.864727,136.251841,113.140413,132.163429,100.936236,106.697645,81.500206
2441,131.501680,92.504927,101.623617,77.855502,152.834235,128.681416,128.822557,115.798652,120.559853,87.917146,...,106.011231,121.198749,109.048077,72.841395,136.123409,113.512316,132.047130,100.960092,106.831510,81.618212
2442,131.471134,92.285320,101.207837,77.700327,153.292364,129.240958,129.305244,116.090118,120.344506,87.936843,...,105.691064,121.689646,109.025871,73.136904,136.010019,113.655976,132.699088,101.196379,107.320174,81.958724

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.38
Fold 1 - Mean Absolute Error (MAE): 0.49
Fold 1 - Root Mean Squared Error (RMSE): 0.62
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.41
Fold 2 - Mean Absolute Error (MAE): 0.50
Fold 2 - Root Mean Squared Error (RMSE): 0.64
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.38
Fold 3 - Mean Absolute Error (MAE): 0.49
Fold 3 - Root Mean Squared Error (RMSE): 0.61
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.38
Fold 4 - Mean Absolute Error (MAE): 0.49
Fold 4 - Root Mean Squared Error (RMSE): 0.62
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.37
Fold 5 - Mean Absolute Error (MAE): 0.47
Fold 5 - Root Mean Squared Error (RMSE): 0.61
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.38
Mean - Mean Absolute Error (MAE): 0.49
Mean - Root Mean Squared Error (RMSE): 0.62
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 1.72
Fold 1 - Mean Absolute Error (MAE): 0.58
Fold 1 - Root Mean Squared Error (RMSE): 1.31
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 2.22
Fold 2 - Mean Absolute Error (MAE): 0.54
Fold 2 - Root Mean Squared Error (RMSE): 1.49
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 1.80
Fold 3 - Mean Absolute Error (MAE): 0.53
Fold 3 - Root Mean Squared Error (RMSE): 1.34
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 1.79
Fold 4 - Mean Absolute Error (MAE): 0.56
Fold 4 - Root Mean Squared Error (RMSE): 1.34
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 0.88
Fold 5 - Mean Absolute Error (MAE): 0.48
Fold 5 - Root Mean Squared Error (RMSE): 0.94
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 1.68
Mean - Mean Absolute Error (MAE): 0.54
Mean - Root Mean Squared Error (RMSE): 1.28
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.15
Fold 1 - Mean Absolute Error (MAE): 0.20
Fold 1 - Root Mean Squared Error (RMSE): 0.39
Fold 1 - Time taken: 2.28 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.09
Fold 2 - Mean Absolute Error (MAE): 0.18
Fold 2 - Root Mean Squared Error (RMSE): 0.30
Fold 2 - Time taken: 2.30 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.10
Fold 3 - Mean Absolute Error (MAE): 0.19
Fold 3 - Root Mean Squared Error (RMSE): 0.32
Fold 3 - Time taken: 3.44 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.10
Fold 4 - Mean Absolute Error (MAE): 0.18
Fold 4 - Root Mean Squared Error (RMSE): 0.31
Fold 4 - Time taken: 3.67 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.08
Fold 5 - Mean Absolute Error (MAE): 0.18
Fold 5 - Root Mean Squared Error (RMSE): 0.29
Fold 5 - Time taken: 3.80 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.11
Mean - Mean Absolute Error (MAE): 0.19
Mean - Root Mean Squared Error (RMSE): 0.32
Mean - Time taken: 3.10 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.05
Fold 1 - Mean Absolute Error (MAE): 0.14
Fold 1 - Root Mean Squared Error (RMSE): 0.22
Fold 1 - Time taken: 0.11 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.05
Fold 2 - Mean Absolute Error (MAE): 0.15
Fold 2 - Root Mean Squared Error (RMSE): 0.23
Fold 2 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.06
Fold 3 - Mean Absolute Error (MAE): 0.15
Fold 3 - Root Mean Squared Error (RMSE): 0.24
Fold 3 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.06
Fold 4 - Mean Absolute Error (MAE): 0.15
Fold 4 - Root Mean Squared Error (RMSE): 0.25
Fold 4 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.06
Fold 5 - Mean Absolute Error (MAE): 0.15
Fold 5 - Root Mean Squared Error (RMSE): 0.24
Fold 5 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.06
Mean - Mean Absolute Error (MAE): 0.15
Mean - Root Mean Squared Error (RMSE): 0.24
Mean - Time taken: 0.07 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.60
Fold 1 - Mean Absolute Error (MAE): 0.48
Fold 1 - Root Mean Squared Error (RMSE): 0.78
Fold 1 - Time taken: 4.70 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.95
Fold 2 - Mean Absolute Error (MAE): 0.48
Fold 2 - Root Mean Squared Error (RMSE): 0.97
Fold 2 - Time taken: 4.86 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 0.74
Fold 3 - Mean Absolute Error (MAE): 0.48
Fold 3 - Root Mean Squared Error (RMSE): 0.86
Fold 3 - Time taken: 5.29 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.57
Fold 4 - Mean Absolute Error (MAE): 0.48
Fold 4 - Root Mean Squared Error (RMSE): 0.75
Fold 4 - Time taken: 3.64 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.04
Fold 5 - Mean Absolute Error (MAE): 0.51
Fold 5 - Root Mean Squared Error (RMSE): 1.02
Fold 5 - Time taken: 3.57 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 0.78
Mean - Mean Absolute Error (MAE): 0.49
Mean - Root Mean Squared Error (RMSE): 0.88
Mean - Time taken: 4.41 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_1_smoothing1_iReg2.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_1_smoothing1_iReg2.xlsx file")

Results saved to Results__PL_model_1_smoothing1_iReg2.xlsx file