# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_smoothing2_iReg2.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,105.581144,121.691250,71.710660,121.513079,127.659940,139.847042,104.351603,136.963235,99.995116,99.791768,...,101.704371,101.155731,103.308173,82.660342,129.381926,112.923367,101.146352,122.002081,67.949077,117.237953
1,105.524490,121.668979,71.804143,121.501801,127.500817,139.678893,104.268760,136.929737,100.153934,100.030871,...,101.738906,101.032783,103.508774,82.911455,129.228435,112.809086,101.158553,121.867879,67.820635,117.143327
2,105.469292,121.646783,71.896634,121.488849,127.341299,139.511275,104.183308,136.891768,100.310622,100.271582,...,101.775285,100.908895,103.708617,83.159866,129.073122,112.693825,101.171470,121.732776,67.690508,117.048085
3,105.415763,121.624692,71.988660,121.473989,127.180989,139.344401,104.095318,136.849328,100.464885,100.513650,...,101.813102,100.784030,103.907669,83.405474,128.916381,112.577423,101.185276,121.596664,67.558865,116.952573
4,105.364060,121.602965,72.080679,121.457018,127.019687,139.178521,104.005133,136.802535,100.616321,100.756953,...,101.851997,100.658234,104.105768,83.648174,128.758795,112.459577,101.200226,121.459653,67.426044,116.857169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.728531,92.441642,101.202601,77.804608,153.838347,128.232569,128.459868,116.655242,120.440648,87.206760,...,105.689467,120.473155,107.841446,72.997443,135.818430,113.131951,132.325896,99.937362,107.210261,81.802100
2439,130.596769,92.077926,101.124903,77.901299,153.904951,128.311948,128.441816,116.694648,120.331474,87.086973,...,105.464179,120.560378,107.671227,73.199293,135.670696,113.150086,132.260341,99.982531,107.359420,81.873348
2440,130.464682,91.709550,101.047300,77.998927,153.972266,128.393288,128.427227,116.731304,120.218587,86.967369,...,105.239157,120.649702,107.503805,73.404412,135.524236,113.168153,132.196818,100.029316,107.511505,81.944709
2441,130.332085,91.336783,100.969772,78.097359,154.040051,128.476205,128.415753,116.765569,120.101567,86.847565,...,105.014174,120.740959,107.339401,73.612622,135.378886,113.185989,132.135425,100.077310,107.666713,82.016300
2442,130.198857,90.959833,100.892246,78.196421,154.108146,128.560424,128.406914,116.797768,119.980207,86.727068,...,104.789077,120.833899,107.178160,73.823767,135.234362,113.203453,132.076210,100.126144,107.825019,82.088215

In [4]:
position_data = pd.read_excel('real_positions_iReg2.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,105.581144,121.691250,71.710660,121.513079,127.659940,139.847042,104.351603,136.963235,99.995116,99.791768,...,101.704371,101.155731,103.308173,82.660342,129.381926,112.923367,101.146352,122.002081,67.949077,117.237953
1,105.524490,121.668979,71.804143,121.501801,127.500817,139.678893,104.268760,136.929737,100.153934,100.030871,...,101.738906,101.032783,103.508774,82.911455,129.228435,112.809086,101.158553,121.867879,67.820635,117.143327
2,105.469292,121.646783,71.896634,121.488849,127.341299,139.511275,104.183308,136.891768,100.310622,100.271582,...,101.775285,100.908895,103.708617,83.159866,129.073122,112.693825,101.171470,121.732776,67.690508,117.048085
3,105.415763,121.624692,71.988660,121.473989,127.180989,139.344401,104.095318,136.849328,100.464885,100.513650,...,101.813102,100.784030,103.907669,83.405474,128.916381,112.577423,101.185276,121.596664,67.558865,116.952573
4,105.364060,121.602965,72.080679,121.457018,127.019687,139.178521,104.005133,136.802535,100.616321,100.756953,...,101.851997,100.658234,104.105768,83.648174,128.758795,112.459577,101.200226,121.459653,67.426044,116.857169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.728531,92.441642,101.202601,77.804608,153.838347,128.232569,128.459868,116.655242,120.440648,87.206760,...,105.689467,120.473155,107.841446,72.997443,135.818430,113.131951,132.325896,99.937362,107.210261,81.802100
2439,130.596769,92.077926,101.124903,77.901299,153.904951,128.311948,128.441816,116.694648,120.331474,87.086973,...,105.464179,120.560378,107.671227,73.199293,135.670696,113.150086,132.260341,99.982531,107.359420,81.873348
2440,130.464682,91.709550,101.047300,77.998927,153.972266,128.393288,128.427227,116.731304,120.218587,86.967369,...,105.239157,120.649702,107.503805,73.404412,135.524236,113.168153,132.196818,100.029316,107.511505,81.944709
2441,130.332085,91.336783,100.969772,78.097359,154.040051,128.476205,128.415753,116.765569,120.101567,86.847565,...,105.014174,120.740959,107.339401,73.612622,135.378886,113.185989,132.135425,100.077310,107.666713,82.016300
2442,130.198857,90.959833,100.892246,78.196421,154.108146,128.560424,128.406914,116.797768,119.980207,86.727068,...,104.789077,120.833899,107.178160,73.823767,135.234362,113.203453,132.076210,100.126144,107.825019,82.088215

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.24
Fold 1 - Mean Absolute Error (MAE): 0.38
Fold 1 - Root Mean Squared Error (RMSE): 0.49
Fold 1 - Time taken: 0.02 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.24
Fold 2 - Mean Absolute Error (MAE): 0.39
Fold 2 - Root Mean Squared Error (RMSE): 0.49
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.24
Fold 3 - Mean Absolute Error (MAE): 0.39
Fold 3 - Root Mean Squared Error (RMSE): 0.49
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.23
Fold 4 - Mean Absolute Error (MAE): 0.39
Fold 4 - Root Mean Squared Error (RMSE): 0.48
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.23
Fold 5 - Mean Absolute Error (MAE): 0.37
Fold 5 - Root Mean Squared Error (RMSE): 0.48
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.23
Mean - Mean Absolute Error (MAE): 0.38
Mean - Root Mean Squared Error (RMSE): 0.48
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 0.74
Fold 1 - Mean Absolute Error (MAE): 0.31
Fold 1 - Root Mean Squared Error (RMSE): 0.86
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 0.57
Fold 2 - Mean Absolute Error (MAE): 0.31
Fold 2 - Root Mean Squared Error (RMSE): 0.76
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 2.68
Fold 3 - Mean Absolute Error (MAE): 0.42
Fold 3 - Root Mean Squared Error (RMSE): 1.64
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 1.53
Fold 4 - Mean Absolute Error (MAE): 0.33
Fold 4 - Root Mean Squared Error (RMSE): 1.24
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 0.19
Fold 5 - Mean Absolute Error (MAE): 0.28
Fold 5 - Root Mean Squared Error (RMSE): 0.44
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 1.14
Mean - Mean Absolute Error (MAE): 0.33
Mean - Root Mean Squared Error (RMSE): 0.99
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.06
Fold 1 - Mean Absolute Error (MAE): 0.13
Fold 1 - Root Mean Squared Error (RMSE): 0.24
Fold 1 - Time taken: 2.12 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.06
Fold 2 - Mean Absolute Error (MAE): 0.13
Fold 2 - Root Mean Squared Error (RMSE): 0.25
Fold 2 - Time taken: 2.12 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.05
Fold 3 - Mean Absolute Error (MAE): 0.13
Fold 3 - Root Mean Squared Error (RMSE): 0.23
Fold 3 - Time taken: 3.23 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.06
Fold 4 - Mean Absolute Error (MAE): 0.13
Fold 4 - Root Mean Squared Error (RMSE): 0.24
Fold 4 - Time taken: 3.34 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.05
Fold 5 - Mean Absolute Error (MAE): 0.13
Fold 5 - Root Mean Squared Error (RMSE): 0.22
Fold 5 - Time taken: 3.32 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.06
Mean - Mean Absolute Error (MAE): 0.13
Mean - Root Mean Squared Error (RMSE): 0.24
Mean - Time taken: 2.83 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.04
Fold 1 - Mean Absolute Error (MAE): 0.13
Fold 1 - Root Mean Squared Error (RMSE): 0.19
Fold 1 - Time taken: 0.09 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.05
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.22
Fold 2 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.05
Fold 3 - Mean Absolute Error (MAE): 0.14
Fold 3 - Root Mean Squared Error (RMSE): 0.22
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.05
Fold 4 - Mean Absolute Error (MAE): 0.14
Fold 4 - Root Mean Squared Error (RMSE): 0.23
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.05
Fold 5 - Mean Absolute Error (MAE): 0.14
Fold 5 - Root Mean Squared Error (RMSE): 0.23
Fold 5 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.05
Mean - Mean Absolute Error (MAE): 0.14
Mean - Root Mean Squared Error (RMSE): 0.22
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.31
Fold 1 - Mean Absolute Error (MAE): 0.34
Fold 1 - Root Mean Squared Error (RMSE): 0.56
Fold 1 - Time taken: 3.33 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.36
Fold 2 - Mean Absolute Error (MAE): 0.34
Fold 2 - Root Mean Squared Error (RMSE): 0.60
Fold 2 - Time taken: 3.57 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 0.40
Fold 3 - Mean Absolute Error (MAE): 0.37
Fold 3 - Root Mean Squared Error (RMSE): 0.63
Fold 3 - Time taken: 4.51 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.27
Fold 4 - Mean Absolute Error (MAE): 0.32
Fold 4 - Root Mean Squared Error (RMSE): 0.52
Fold 4 - Time taken: 4.73 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 0.31
Fold 5 - Mean Absolute Error (MAE): 0.32
Fold 5 - Root Mean Squared Error (RMSE): 0.56
Fold 5 - Time taken: 4.90 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 0.33
Mean - Mean Absolute Error (MAE): 0.34
Mean - Root Mean Squared Error (RMSE): 0.57
Mean - Time taken: 4.21 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_1_smoothing2_iReg2.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_1_smoothing2_iReg2.xlsx file")

Results saved to Results__PL_model_1_smoothing2_iReg2.xlsx file