# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_Scattered_iReg2.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,97.405888,127.373970,65.064241,123.319484,137.006160,138.709136,106.281830,136.165019,99.657609,106.495647,...,107.555040,103.816906,102.693371,83.665529,127.378419,112.766780,98.484669,106.892581,66.166999,111.691859
1,110.907991,117.620254,65.501323,121.662897,128.791561,137.917203,98.088284,127.856812,101.710314,101.315520,...,106.749169,98.142553,102.274025,78.735115,122.166130,112.983391,103.347729,126.559428,64.996180,117.262317
2,106.793757,117.586356,74.426471,121.134129,121.411851,138.515993,97.889689,134.980689,101.973825,95.294105,...,99.200142,100.484779,108.233942,83.474743,125.055787,116.894099,97.811473,114.190958,63.683711,117.694597
3,101.700284,116.922757,78.449751,117.881621,123.730122,142.568559,100.795983,137.192389,102.443033,101.257518,...,99.784286,96.206037,103.661472,86.805991,133.914147,111.506820,101.962299,116.765421,67.085678,113.621893
4,111.446612,126.975744,71.602516,120.221975,119.926274,142.552904,111.256441,137.753694,95.471630,106.225758,...,105.595128,98.080643,102.991818,83.726940,126.933014,112.594604,107.629661,127.955371,74.803966,110.021028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,135.383116,88.599679,100.675551,78.507329,159.441427,125.123209,131.951413,107.588937,118.553067,86.573807,...,106.144077,115.525901,105.229755,80.342864,137.517629,119.442601,132.252696,101.207564,111.645457,80.568678
2439,130.855957,92.082625,99.105763,75.024304,154.506954,135.020716,131.444864,109.956019,121.020833,92.265527,...,105.859661,127.304822,109.815413,73.455141,141.830108,106.235962,129.074738,96.763477,105.857949,74.862348
2440,127.850549,93.796540,102.996596,80.191772,150.601073,123.315809,133.069200,118.941198,110.125525,90.802233,...,102.905323,122.015303,107.604109,73.755257,139.583246,112.850601,134.635429,100.940027,114.209796,82.794513
2441,133.696404,87.859727,101.537723,78.441571,157.565669,130.330865,126.048233,115.820611,117.355064,83.341521,...,106.272728,122.142303,111.979213,69.467000,129.358800,117.825683,130.500345,99.054865,114.664881,84.719648
2442,124.866102,89.961497,99.174211,76.515849,148.616680,125.525878,125.323253,119.978816,115.108982,77.786072,...,101.950886,118.869517,109.201592,78.282267,134.457311,106.262748,137.309142,97.722441,105.718145,81.728519

In [4]:
position_data = pd.read_excel('real_positions_iReg2.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,97.405888,127.373970,65.064241,123.319484,137.006160,138.709136,106.281830,136.165019,99.657609,106.495647,...,107.555040,103.816906,102.693371,83.665529,127.378419,112.766780,98.484669,106.892581,66.166999,111.691859
1,110.907991,117.620254,65.501323,121.662897,128.791561,137.917203,98.088284,127.856812,101.710314,101.315520,...,106.749169,98.142553,102.274025,78.735115,122.166130,112.983391,103.347729,126.559428,64.996180,117.262317
2,106.793757,117.586356,74.426471,121.134129,121.411851,138.515993,97.889689,134.980689,101.973825,95.294105,...,99.200142,100.484779,108.233942,83.474743,125.055787,116.894099,97.811473,114.190958,63.683711,117.694597
3,101.700284,116.922757,78.449751,117.881621,123.730122,142.568559,100.795983,137.192389,102.443033,101.257518,...,99.784286,96.206037,103.661472,86.805991,133.914147,111.506820,101.962299,116.765421,67.085678,113.621893
4,111.446612,126.975744,71.602516,120.221975,119.926274,142.552904,111.256441,137.753694,95.471630,106.225758,...,105.595128,98.080643,102.991818,83.726940,126.933014,112.594604,107.629661,127.955371,74.803966,110.021028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,135.383116,88.599679,100.675551,78.507329,159.441427,125.123209,131.951413,107.588937,118.553067,86.573807,...,106.144077,115.525901,105.229755,80.342864,137.517629,119.442601,132.252696,101.207564,111.645457,80.568678
2439,130.855957,92.082625,99.105763,75.024304,154.506954,135.020716,131.444864,109.956019,121.020833,92.265527,...,105.859661,127.304822,109.815413,73.455141,141.830108,106.235962,129.074738,96.763477,105.857949,74.862348
2440,127.850549,93.796540,102.996596,80.191772,150.601073,123.315809,133.069200,118.941198,110.125525,90.802233,...,102.905323,122.015303,107.604109,73.755257,139.583246,112.850601,134.635429,100.940027,114.209796,82.794513
2441,133.696404,87.859727,101.537723,78.441571,157.565669,130.330865,126.048233,115.820611,117.355064,83.341521,...,106.272728,122.142303,111.979213,69.467000,129.358800,117.825683,130.500345,99.054865,114.664881,84.719648
2442,124.866102,89.961497,99.174211,76.515849,148.616680,125.525878,125.323253,119.978816,115.108982,77.786072,...,101.950886,118.869517,109.201592,78.282267,134.457311,106.262748,137.309142,97.722441,105.718145,81.728519

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 8.96
Fold 1 - Mean Absolute Error (MAE): 2.38
Fold 1 - Root Mean Squared Error (RMSE): 2.99
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 8.40
Fold 2 - Mean Absolute Error (MAE): 2.30
Fold 2 - Root Mean Squared Error (RMSE): 2.90
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 9.23
Fold 3 - Mean Absolute Error (MAE): 2.41
Fold 3 - Root Mean Squared Error (RMSE): 3.04
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 9.00
Fold 4 - Mean Absolute Error (MAE): 2.39
Fold 4 - Root Mean Squared Error (RMSE): 3.00
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 9.49
Fold 5 - Mean Absolute Error (MAE): 2.42
Fold 5 - Root Mean Squared Error (RMSE): 3.08
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 9.02
Mean - Mean Absolute Error (MAE): 2.38
Mean - Root Mean Squared Error (RMSE): 3.00
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 90.27
Fold 1 - Mean Absolute Error (MAE): 5.90
Fold 1 - Root Mean Squared Error (RMSE): 9.50
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 87.37
Fold 2 - Mean Absolute Error (MAE): 5.90
Fold 2 - Root Mean Squared Error (RMSE): 9.35
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 107.01
Fold 3 - Mean Absolute Error (MAE): 6.72
Fold 3 - Root Mean Squared Error (RMSE): 10.34
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 83.29
Fold 4 - Mean Absolute Error (MAE): 5.82
Fold 4 - Root Mean Squared Error (RMSE): 9.13
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 91.72
Fold 5 - Mean Absolute Error (MAE): 6.05
Fold 5 - Root Mean Squared Error (RMSE): 9.58
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 91.93
Mean - Mean Absolute Error (MAE): 6.08
Mean - Root Mean Squared Error (RMSE): 9.58
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 19.99
Fold 1 - Mean Absolute Error (MAE): 3.48
Fold 1 - Root Mean Squared Error (RMSE): 4.47
Fold 1 - Time taken: 2.54 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 17.24
Fold 2 - Mean Absolute Error (MAE): 3.29
Fold 2 - Root Mean Squared Error (RMSE): 4.15
Fold 2 - Time taken: 2.53 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 17.91
Fold 3 - Mean Absolute Error (MAE): 3.39
Fold 3 - Root Mean Squared Error (RMSE): 4.23
Fold 3 - Time taken: 4.17 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 16.65
Fold 4 - Mean Absolute Error (MAE): 3.29
Fold 4 - Root Mean Squared Error (RMSE): 4.08
Fold 4 - Time taken: 4.25 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 17.26
Fold 5 - Mean Absolute Error (MAE): 3.30
Fold 5 - Root Mean Squared Error (RMSE): 4.15
Fold 5 - Time taken: 4.24 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 17.81
Mean - Mean Absolute Error (MAE): 3.35
Mean - Root Mean Squared Error (RMSE): 4.22
Mean - Time taken: 3.54 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 5.74
Fold 1 - Mean Absolute Error (MAE): 1.55
Fold 1 - Root Mean Squared Error (RMSE): 2.40
Fold 1 - Time taken: 0.11 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 5.17
Fold 2 - Mean Absolute Error (MAE): 1.48
Fold 2 - Root Mean Squared Error (RMSE): 2.27
Fold 2 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 5.75
Fold 3 - Mean Absolute Error (MAE): 1.58
Fold 3 - Root Mean Squared Error (RMSE): 2.40
Fold 3 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 6.17
Fold 4 - Mean Absolute Error (MAE): 1.61
Fold 4 - Root Mean Squared Error (RMSE): 2.48
Fold 4 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 5.67
Fold 5 - Mean Absolute Error (MAE): 1.55
Fold 5 - Root Mean Squared Error (RMSE): 2.38
Fold 5 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 5.70
Mean - Mean Absolute Error (MAE): 1.55
Mean - Root Mean Squared Error (RMSE): 2.39
Mean - Time taken: 0.07 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 21.15
Fold 1 - Mean Absolute Error (MAE): 3.42
Fold 1 - Root Mean Squared Error (RMSE): 4.60
Fold 1 - Time taken: 6.24 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 18.11
Fold 2 - Mean Absolute Error (MAE): 3.17
Fold 2 - Root Mean Squared Error (RMSE): 4.26
Fold 2 - Time taken: 4.93 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 19.28
Fold 3 - Mean Absolute Error (MAE): 3.21
Fold 3 - Root Mean Squared Error (RMSE): 4.39
Fold 3 - Time taken: 4.03 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 19.29
Fold 4 - Mean Absolute Error (MAE): 3.27
Fold 4 - Root Mean Squared Error (RMSE): 4.39
Fold 4 - Time taken: 1.97 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 18.76
Fold 5 - Mean Absolute Error (MAE): 3.27
Fold 5 - Root Mean Squared Error (RMSE): 4.33
Fold 5 - Time taken: 1.97 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 19.32
Mean - Mean Absolute Error (MAE): 3.27
Mean - Root Mean Squared Error (RMSE): 4.39
Mean - Time taken: 3.83 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_1_Scattered_iReg2.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_1_Scattered_iReg2.xlsx file")

Results saved to Results__PL_model_1_Scattered_iReg2.xlsx file