# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_smoothing1_iReg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,104.229731,133.916482,69.582276,115.664391,123.991728,147.659619,105.711954,133.286175,90.473502,109.004295,...,81.963603,87.520114,91.765851,88.158335,119.213147,112.770061,101.725999,130.210809,64.939317,113.341266
1,104.096643,133.296636,70.130061,115.151749,124.719488,148.043050,105.780104,133.264538,91.115053,108.720727,...,81.847566,87.222475,91.418591,88.448622,118.354018,112.719545,101.575650,130.939839,65.090954,112.420208
2,104.269194,134.039960,70.185466,114.965570,125.134427,147.533303,106.016680,133.320150,91.316149,109.050588,...,81.398157,87.039664,91.080941,89.192947,118.278729,112.816756,101.095120,130.084628,65.237873,112.261933
3,104.009965,134.107466,70.073135,115.038764,124.565904,148.053915,105.952191,133.746681,91.252396,109.070002,...,81.490008,87.187652,90.556080,89.228694,117.748686,112.705986,101.264670,129.937736,64.943835,111.860676
4,103.716244,133.923783,70.137982,115.189681,124.279434,148.188051,105.670767,133.816904,91.010440,108.799768,...,81.824784,86.938101,90.949154,89.064556,117.737750,112.374230,100.975256,130.126338,65.298789,111.377045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,129.504699,113.681686,101.734898,71.228102,151.130564,139.693063,129.287804,113.947902,108.597469,96.283387,...,87.476207,111.542419,90.273780,70.749549,123.765551,113.223303,130.315200,115.248941,106.436842,76.576625
2439,129.320014,113.715258,102.343018,70.858426,151.666517,139.520460,129.426182,113.888160,108.691070,96.039910,...,87.285045,111.524664,90.131994,70.687025,123.649300,112.971769,130.204911,115.622842,106.223716,76.424972
2440,129.286633,113.218568,102.864278,71.015322,151.249085,139.576369,129.168366,113.518177,108.661496,95.824007,...,87.337012,111.474442,90.046661,71.105108,123.727818,112.771069,130.154799,115.194890,105.804487,76.532021
2441,128.857556,112.747813,103.112700,70.718712,151.907094,139.298192,129.195823,113.848718,108.379633,96.920101,...,87.374597,111.212196,89.625040,70.506018,123.588928,112.730240,130.119482,114.950999,105.855205,76.879438
2442,129.225288,113.374526,102.929935,71.068335,151.870568,139.328725,129.430282,113.710309,108.044539,96.452851,...,86.995403,111.127982,89.308846,70.825666,123.395320,112.773125,129.732866,114.470667,106.002656,76.441053

In [4]:
position_data = pd.read_excel('real_positions_iReg3.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,104.229731,133.916482,69.582276,115.664391,123.991728,147.659619,105.711954,133.286175,90.473502,109.004295,...,81.963603,87.520114,91.765851,88.158335,119.213147,112.770061,101.725999,130.210809,64.939317,113.341266
1,104.096643,133.296636,70.130061,115.151749,124.719488,148.043050,105.780104,133.264538,91.115053,108.720727,...,81.847566,87.222475,91.418591,88.448622,118.354018,112.719545,101.575650,130.939839,65.090954,112.420208
2,104.269194,134.039960,70.185466,114.965570,125.134427,147.533303,106.016680,133.320150,91.316149,109.050588,...,81.398157,87.039664,91.080941,89.192947,118.278729,112.816756,101.095120,130.084628,65.237873,112.261933
3,104.009965,134.107466,70.073135,115.038764,124.565904,148.053915,105.952191,133.746681,91.252396,109.070002,...,81.490008,87.187652,90.556080,89.228694,117.748686,112.705986,101.264670,129.937736,64.943835,111.860676
4,103.716244,133.923783,70.137982,115.189681,124.279434,148.188051,105.670767,133.816904,91.010440,108.799768,...,81.824784,86.938101,90.949154,89.064556,117.737750,112.374230,100.975256,130.126338,65.298789,111.377045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,129.504699,113.681686,101.734898,71.228102,151.130564,139.693063,129.287804,113.947902,108.597469,96.283387,...,87.476207,111.542419,90.273780,70.749549,123.765551,113.223303,130.315200,115.248941,106.436842,76.576625
2439,129.320014,113.715258,102.343018,70.858426,151.666517,139.520460,129.426182,113.888160,108.691070,96.039910,...,87.285045,111.524664,90.131994,70.687025,123.649300,112.971769,130.204911,115.622842,106.223716,76.424972
2440,129.286633,113.218568,102.864278,71.015322,151.249085,139.576369,129.168366,113.518177,108.661496,95.824007,...,87.337012,111.474442,90.046661,71.105108,123.727818,112.771069,130.154799,115.194890,105.804487,76.532021
2441,128.857556,112.747813,103.112700,70.718712,151.907094,139.298192,129.195823,113.848718,108.379633,96.920101,...,87.374597,111.212196,89.625040,70.506018,123.588928,112.730240,130.119482,114.950999,105.855205,76.879438
2442,129.225288,113.374526,102.929935,71.068335,151.870568,139.328725,129.430282,113.710309,108.044539,96.452851,...,86.995403,111.127982,89.308846,70.825666,123.395320,112.773125,129.732866,114.470667,106.002656,76.441053

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.46
Fold 1 - Mean Absolute Error (MAE): 0.54
Fold 1 - Root Mean Squared Error (RMSE): 0.68
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.43
Fold 2 - Mean Absolute Error (MAE): 0.52
Fold 2 - Root Mean Squared Error (RMSE): 0.66
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.44
Fold 3 - Mean Absolute Error (MAE): 0.52
Fold 3 - Root Mean Squared Error (RMSE): 0.66
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.47
Fold 4 - Mean Absolute Error (MAE): 0.55
Fold 4 - Root Mean Squared Error (RMSE): 0.69
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.45
Fold 5 - Mean Absolute Error (MAE): 0.53
Fold 5 - Root Mean Squared Error (RMSE): 0.67
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.45
Mean - Mean Absolute Error (MAE): 0.53
Mean - Root Mean Squared Error (RMSE): 0.67
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 0.66
Fold 1 - Mean Absolute Error (MAE): 0.48
Fold 1 - Root Mean Squared Error (RMSE): 0.81
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 1.24
Fold 2 - Mean Absolute Error (MAE): 0.48
Fold 2 - Root Mean Squared Error (RMSE): 1.11
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 1.35
Fold 3 - Mean Absolute Error (MAE): 0.52
Fold 3 - Root Mean Squared Error (RMSE): 1.16
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 2.49
Fold 4 - Mean Absolute Error (MAE): 0.55
Fold 4 - Root Mean Squared Error (RMSE): 1.58
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 1.34
Fold 5 - Mean Absolute Error (MAE): 0.54
Fold 5 - Root Mean Squared Error (RMSE): 1.16
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 1.42
Mean - Mean Absolute Error (MAE): 0.51
Mean - Root Mean Squared Error (RMSE): 1.16
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.13
Fold 1 - Mean Absolute Error (MAE): 0.19
Fold 1 - Root Mean Squared Error (RMSE): 0.36
Fold 1 - Time taken: 2.29 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.08
Fold 2 - Mean Absolute Error (MAE): 0.18
Fold 2 - Root Mean Squared Error (RMSE): 0.29
Fold 2 - Time taken: 2.25 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.20
Fold 3 - Mean Absolute Error (MAE): 0.20
Fold 3 - Root Mean Squared Error (RMSE): 0.45
Fold 3 - Time taken: 3.46 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.11
Fold 4 - Mean Absolute Error (MAE): 0.18
Fold 4 - Root Mean Squared Error (RMSE): 0.33
Fold 4 - Time taken: 3.48 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.13
Fold 5 - Mean Absolute Error (MAE): 0.20
Fold 5 - Root Mean Squared Error (RMSE): 0.36
Fold 5 - Time taken: 3.49 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.13
Mean - Mean Absolute Error (MAE): 0.19
Mean - Root Mean Squared Error (RMSE): 0.36
Mean - Time taken: 2.99 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.04
Fold 1 - Mean Absolute Error (MAE): 0.14
Fold 1 - Root Mean Squared Error (RMSE): 0.21
Fold 1 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.06
Fold 2 - Mean Absolute Error (MAE): 0.15
Fold 2 - Root Mean Squared Error (RMSE): 0.24
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.06
Fold 3 - Mean Absolute Error (MAE): 0.15
Fold 3 - Root Mean Squared Error (RMSE): 0.25
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.06
Fold 4 - Mean Absolute Error (MAE): 0.16
Fold 4 - Root Mean Squared Error (RMSE): 0.24
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.06
Fold 5 - Mean Absolute Error (MAE): 0.15
Fold 5 - Root Mean Squared Error (RMSE): 0.23
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.06
Mean - Mean Absolute Error (MAE): 0.15
Mean - Root Mean Squared Error (RMSE): 0.23
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.80
Fold 1 - Mean Absolute Error (MAE): 0.51
Fold 1 - Root Mean Squared Error (RMSE): 0.89
Fold 1 - Time taken: 1.87 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.67
Fold 2 - Mean Absolute Error (MAE): 0.48
Fold 2 - Root Mean Squared Error (RMSE): 0.82
Fold 2 - Time taken: 1.96 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 0.58
Fold 3 - Mean Absolute Error (MAE): 0.48
Fold 3 - Root Mean Squared Error (RMSE): 0.76
Fold 3 - Time taken: 1.87 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1.17
Fold 4 - Mean Absolute Error (MAE): 0.53
Fold 4 - Root Mean Squared Error (RMSE): 1.08
Fold 4 - Time taken: 1.81 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 0.68
Fold 5 - Mean Absolute Error (MAE): 0.51
Fold 5 - Root Mean Squared Error (RMSE): 0.83
Fold 5 - Time taken: 1.82 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 0.78
Mean - Mean Absolute Error (MAE): 0.50
Mean - Root Mean Squared Error (RMSE): 0.88
Mean - Time taken: 1.87 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_1_smoothing1_iReg3.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_1_smoothing1_iReg3.xlsx file")

Results saved to Results__PL_model_1_smoothing1_iReg3.xlsx file