# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_smoothing2_iReg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.722102,133.549604,70.246654,114.393425,125.518042,148.490719,105.960735,134.734917,90.358364,107.880691,...,80.511088,86.266577,91.324276,88.413835,118.079357,112.830599,101.581432,130.484864,65.849519,112.853971
1,103.741769,133.613840,70.333167,114.403077,125.425263,148.406322,105.788181,134.546280,90.431246,107.970290,...,80.667880,86.301348,91.369136,88.468505,117.851056,112.732842,101.535137,130.422780,65.831506,112.816370
2,103.759517,133.678503,70.421559,114.410863,125.331731,148.320508,105.613823,134.358052,90.503448,108.058270,...,80.823085,86.337129,91.414783,88.521309,117.621052,112.638386,101.491179,130.363766,65.812886,112.778795
3,103.775461,133.743510,70.511477,114.417015,125.237166,148.233207,105.437718,134.170555,90.574876,108.144722,...,80.976531,86.373826,91.461416,88.572363,117.389684,112.547228,101.449812,130.307871,65.793756,112.741332
4,103.789800,133.808609,70.602435,114.421924,125.141318,148.144403,105.260017,133.984101,90.645256,108.229792,...,81.128195,86.411394,91.509328,88.621720,117.157444,112.459148,101.411458,130.254975,65.774054,112.703922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.394731,113.120062,102.722429,71.609424,151.352281,140.904922,128.827778,113.779812,107.558742,96.997103,...,88.095891,110.712051,89.522396,71.221952,124.108295,113.383110,130.244963,114.622501,107.532818,76.703086
2439,128.269154,112.982064,102.785866,71.581983,151.277725,140.892099,128.842679,113.832694,107.410332,96.815164,...,88.034588,110.548388,89.310220,71.379769,124.099541,113.470836,130.083759,114.395532,107.742386,76.682848
2440,128.143792,112.844766,102.852637,71.555953,151.200817,140.880374,128.857569,113.886728,107.258332,96.632920,...,87.974760,110.380633,89.095824,71.538448,124.091471,113.557163,129.920154,114.165400,107.949968,76.663408
2441,128.018936,112.708365,102.922962,71.531847,151.121227,140.870082,128.872267,113.942389,107.102486,96.450473,...,87.916419,110.208561,88.879379,71.697850,124.084220,113.641886,129.753926,113.932214,108.155353,76.644759
2442,127.894929,112.572888,102.996952,71.509933,151.038840,140.861436,128.886554,113.999895,106.942607,96.267932,...,87.859482,110.032132,88.660934,71.857879,124.077867,113.725050,129.584939,113.696233,108.358487,76.626723

In [4]:
position_data = pd.read_excel('real_positions_iReg3.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.722102,133.549604,70.246654,114.393425,125.518042,148.490719,105.960735,134.734917,90.358364,107.880691,...,80.511088,86.266577,91.324276,88.413835,118.079357,112.830599,101.581432,130.484864,65.849519,112.853971
1,103.741769,133.613840,70.333167,114.403077,125.425263,148.406322,105.788181,134.546280,90.431246,107.970290,...,80.667880,86.301348,91.369136,88.468505,117.851056,112.732842,101.535137,130.422780,65.831506,112.816370
2,103.759517,133.678503,70.421559,114.410863,125.331731,148.320508,105.613823,134.358052,90.503448,108.058270,...,80.823085,86.337129,91.414783,88.521309,117.621052,112.638386,101.491179,130.363766,65.812886,112.778795
3,103.775461,133.743510,70.511477,114.417015,125.237166,148.233207,105.437718,134.170555,90.574876,108.144722,...,80.976531,86.373826,91.461416,88.572363,117.389684,112.547228,101.449812,130.307871,65.793756,112.741332
4,103.789800,133.808609,70.602435,114.421924,125.141318,148.144403,105.260017,133.984101,90.645256,108.229792,...,81.128195,86.411394,91.509328,88.621720,117.157444,112.459148,101.411458,130.254975,65.774054,112.703922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.394731,113.120062,102.722429,71.609424,151.352281,140.904922,128.827778,113.779812,107.558742,96.997103,...,88.095891,110.712051,89.522396,71.221952,124.108295,113.383110,130.244963,114.622501,107.532818,76.703086
2439,128.269154,112.982064,102.785866,71.581983,151.277725,140.892099,128.842679,113.832694,107.410332,96.815164,...,88.034588,110.548388,89.310220,71.379769,124.099541,113.470836,130.083759,114.395532,107.742386,76.682848
2440,128.143792,112.844766,102.852637,71.555953,151.200817,140.880374,128.857569,113.886728,107.258332,96.632920,...,87.974760,110.380633,89.095824,71.538448,124.091471,113.557163,129.920154,114.165400,107.949968,76.663408
2441,128.018936,112.708365,102.922962,71.531847,151.121227,140.870082,128.872267,113.942389,107.102486,96.450473,...,87.916419,110.208561,88.879379,71.697850,124.084220,113.641886,129.753926,113.932214,108.155353,76.644759
2442,127.894929,112.572888,102.996952,71.509933,151.038840,140.861436,128.886554,113.999895,106.942607,96.267932,...,87.859482,110.032132,88.660934,71.857879,124.077867,113.725050,129.584939,113.696233,108.358487,76.626723

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.28
Fold 1 - Mean Absolute Error (MAE): 0.42
Fold 1 - Root Mean Squared Error (RMSE): 0.53
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.25
Fold 2 - Mean Absolute Error (MAE): 0.40
Fold 2 - Root Mean Squared Error (RMSE): 0.50
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.25
Fold 3 - Mean Absolute Error (MAE): 0.40
Fold 3 - Root Mean Squared Error (RMSE): 0.50
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.28
Fold 4 - Mean Absolute Error (MAE): 0.42
Fold 4 - Root Mean Squared Error (RMSE): 0.53
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.27
Fold 5 - Mean Absolute Error (MAE): 0.41
Fold 5 - Root Mean Squared Error (RMSE): 0.52
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.27
Mean - Mean Absolute Error (MAE): 0.41
Mean - Root Mean Squared Error (RMSE): 0.52
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 0.73
Fold 1 - Mean Absolute Error (MAE): 0.33
Fold 1 - Root Mean Squared Error (RMSE): 0.86
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 0.48
Fold 2 - Mean Absolute Error (MAE): 0.30
Fold 2 - Root Mean Squared Error (RMSE): 0.69
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 0.58
Fold 3 - Mean Absolute Error (MAE): 0.30
Fold 3 - Root Mean Squared Error (RMSE): 0.76
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 0.50
Fold 4 - Mean Absolute Error (MAE): 0.30
Fold 4 - Root Mean Squared Error (RMSE): 0.71
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 0.48
Fold 5 - Mean Absolute Error (MAE): 0.29
Fold 5 - Root Mean Squared Error (RMSE): 0.69
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 0.56
Mean - Mean Absolute Error (MAE): 0.30
Mean - Root Mean Squared Error (RMSE): 0.74
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.08
Fold 1 - Mean Absolute Error (MAE): 0.15
Fold 1 - Root Mean Squared Error (RMSE): 0.28
Fold 1 - Time taken: 2.07 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.08
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.28
Fold 2 - Time taken: 2.09 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.10
Fold 3 - Mean Absolute Error (MAE): 0.15
Fold 3 - Root Mean Squared Error (RMSE): 0.31
Fold 3 - Time taken: 2.87 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.05
Fold 4 - Mean Absolute Error (MAE): 0.13
Fold 4 - Root Mean Squared Error (RMSE): 0.23
Fold 4 - Time taken: 3.26 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.07
Fold 5 - Mean Absolute Error (MAE): 0.14
Fold 5 - Root Mean Squared Error (RMSE): 0.26
Fold 5 - Time taken: 3.31 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.07
Mean - Mean Absolute Error (MAE): 0.14
Mean - Root Mean Squared Error (RMSE): 0.27
Mean - Time taken: 2.72 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.04
Fold 1 - Mean Absolute Error (MAE): 0.13
Fold 1 - Root Mean Squared Error (RMSE): 0.20
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.05
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.22
Fold 2 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.05
Fold 3 - Mean Absolute Error (MAE): 0.14
Fold 3 - Root Mean Squared Error (RMSE): 0.22
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.05
Fold 4 - Mean Absolute Error (MAE): 0.15
Fold 4 - Root Mean Squared Error (RMSE): 0.23
Fold 4 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.06
Fold 5 - Mean Absolute Error (MAE): 0.15
Fold 5 - Root Mean Squared Error (RMSE): 0.23
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.05
Mean - Mean Absolute Error (MAE): 0.14
Mean - Root Mean Squared Error (RMSE): 0.22
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.36
Fold 1 - Mean Absolute Error (MAE): 0.35
Fold 1 - Root Mean Squared Error (RMSE): 0.60
Fold 1 - Time taken: 1.87 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.30
Fold 2 - Mean Absolute Error (MAE): 0.33
Fold 2 - Root Mean Squared Error (RMSE): 0.55
Fold 2 - Time taken: 1.86 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 0.33
Fold 3 - Mean Absolute Error (MAE): 0.35
Fold 3 - Root Mean Squared Error (RMSE): 0.58
Fold 3 - Time taken: 1.82 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.35
Fold 4 - Mean Absolute Error (MAE): 0.35
Fold 4 - Root Mean Squared Error (RMSE): 0.59
Fold 4 - Time taken: 1.80 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 0.34
Fold 5 - Mean Absolute Error (MAE): 0.34
Fold 5 - Root Mean Squared Error (RMSE): 0.58
Fold 5 - Time taken: 2.23 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 0.34
Mean - Mean Absolute Error (MAE): 0.34
Mean - Root Mean Squared Error (RMSE): 0.58
Mean - Time taken: 1.92 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_1_smoothing2_iReg3.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_1_smoothing2_iReg3.xlsx file")

Results saved to Results__PL_model_1_smoothing2_iReg3.xlsx file