# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_Scattered_iReg2.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,69.504758,72.699002,55.085638,66.173337,84.753257,71.298257,59.878089,73.727874,69.510217,64.643339,...,80.469861,59.908289,73.537360,47.001026,70.347171,64.658168,58.327979,75.626453,44.316109,81.929812
1,73.423629,62.869174,56.973828,72.105647,74.660708,71.303875,64.829931,73.778408,77.512238,61.567103,...,64.559002,58.096001,58.674305,55.872167,82.169380,67.796612,49.168594,53.877790,42.422505,65.847775
2,58.885600,74.520716,58.024814,65.047906,79.330827,68.906749,76.241294,75.894009,61.340697,51.180290,...,55.048812,56.535119,64.608609,73.067838,68.332979,65.462007,58.085808,58.783579,43.111623,81.969896
3,71.331291,47.386818,58.823015,71.861802,78.253041,76.812617,58.912996,69.668207,55.529779,76.970422,...,56.861250,72.704739,63.238291,57.972900,80.193439,75.980874,59.999893,73.128975,57.403179,63.816814
4,73.317551,76.556561,56.400789,63.621970,57.080447,85.134788,73.243302,95.796228,68.543582,63.424165,...,79.457890,70.396764,75.827037,70.084755,75.864089,74.671150,66.625431,65.738958,50.213844,73.088754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,72.226504,56.488343,73.254318,66.790649,88.982244,75.651704,83.634026,73.400280,72.735343,64.479263,...,82.603771,79.192550,56.582241,60.577551,74.630820,63.173840,77.145089,76.449037,73.407471,69.313160
2439,60.617048,67.174950,61.204680,68.591467,68.922653,65.789294,79.375839,78.914898,64.620030,63.765256,...,82.627564,76.385570,73.048469,57.933199,62.527859,59.904236,79.425998,52.553628,73.274137,58.940341
2440,77.949557,67.255947,61.264368,58.647853,74.970134,65.826270,87.673489,74.010953,65.102825,71.216146,...,62.394747,81.802915,74.796262,64.739224,79.097945,60.733229,64.697559,56.558044,72.317287,73.863062
2441,60.491092,56.908349,71.813213,56.536097,67.807212,66.223507,81.550036,69.072593,68.069714,58.229280,...,63.055867,60.497326,74.699198,47.926331,92.390756,65.225291,65.328292,73.874100,70.786954,67.507575
2442,70.432481,56.696404,69.584591,58.395155,81.894138,82.289493,84.694279,51.504089,53.449078,56.594175,...,82.506529,74.915866,62.319736,57.314528,76.724935,75.176037,85.533961,71.475944,68.504314,58.868130

In [4]:
position_data = pd.read_excel('real_positions_iReg2.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,69.504758,72.699002,55.085638,66.173337,84.753257,71.298257,59.878089,73.727874,69.510217,64.643339,...,80.469861,59.908289,73.537360,47.001026,70.347171,64.658168,58.327979,75.626453,44.316109,81.929812
1,73.423629,62.869174,56.973828,72.105647,74.660708,71.303875,64.829931,73.778408,77.512238,61.567103,...,64.559002,58.096001,58.674305,55.872167,82.169380,67.796612,49.168594,53.877790,42.422505,65.847775
2,58.885600,74.520716,58.024814,65.047906,79.330827,68.906749,76.241294,75.894009,61.340697,51.180290,...,55.048812,56.535119,64.608609,73.067838,68.332979,65.462007,58.085808,58.783579,43.111623,81.969896
3,71.331291,47.386818,58.823015,71.861802,78.253041,76.812617,58.912996,69.668207,55.529779,76.970422,...,56.861250,72.704739,63.238291,57.972900,80.193439,75.980874,59.999893,73.128975,57.403179,63.816814
4,73.317551,76.556561,56.400789,63.621970,57.080447,85.134788,73.243302,95.796228,68.543582,63.424165,...,79.457890,70.396764,75.827037,70.084755,75.864089,74.671150,66.625431,65.738958,50.213844,73.088754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,72.226504,56.488343,73.254318,66.790649,88.982244,75.651704,83.634026,73.400280,72.735343,64.479263,...,82.603771,79.192550,56.582241,60.577551,74.630820,63.173840,77.145089,76.449037,73.407471,69.313160
2439,60.617048,67.174950,61.204680,68.591467,68.922653,65.789294,79.375839,78.914898,64.620030,63.765256,...,82.627564,76.385570,73.048469,57.933199,62.527859,59.904236,79.425998,52.553628,73.274137,58.940341
2440,77.949557,67.255947,61.264368,58.647853,74.970134,65.826270,87.673489,74.010953,65.102825,71.216146,...,62.394747,81.802915,74.796262,64.739224,79.097945,60.733229,64.697559,56.558044,72.317287,73.863062
2441,60.491092,56.908349,71.813213,56.536097,67.807212,66.223507,81.550036,69.072593,68.069714,58.229280,...,63.055867,60.497326,74.699198,47.926331,92.390756,65.225291,65.328292,73.874100,70.786954,67.507575
2442,70.432481,56.696404,69.584591,58.395155,81.894138,82.289493,84.694279,51.504089,53.449078,56.594175,...,82.506529,74.915866,62.319736,57.314528,76.724935,75.176037,85.533961,71.475944,68.504314,58.868130

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 137.58
Fold 1 - Mean Absolute Error (MAE): 9.34
Fold 1 - Root Mean Squared Error (RMSE): 11.73
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 148.67
Fold 2 - Mean Absolute Error (MAE): 9.78
Fold 2 - Root Mean Squared Error (RMSE): 12.19
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 146.39
Fold 3 - Mean Absolute Error (MAE): 9.59
Fold 3 - Root Mean Squared Error (RMSE): 12.10
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 137.53
Fold 4 - Mean Absolute Error (MAE): 9.36
Fold 4 - Root Mean Squared Error (RMSE): 11.73
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 149.75
Fold 5 - Mean Absolute Error (MAE): 9.82
Fold 5 - Root Mean Squared Error (RMSE): 12.24
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 143.98
Mean - Mean Absolute Error (MAE): 9.58
Mean - Root Mean Squared Error (RMSE): 12.00
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 498.28
Fold 1 - Mean Absolute Error (MAE): 16.60
Fold 1 - Root Mean Squared Error (RMSE): 22.32
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 512.30
Fold 2 - Mean Absolute Error (MAE): 16.79
Fold 2 - Root Mean Squared Error (RMSE): 22.63
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 489.19
Fold 3 - Mean Absolute Error (MAE): 16.67
Fold 3 - Root Mean Squared Error (RMSE): 22.12
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 470.10
Fold 4 - Mean Absolute Error (MAE): 16.07
Fold 4 - Root Mean Squared Error (RMSE): 21.68
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 524.98
Fold 5 - Mean Absolute Error (MAE): 16.96
Fold 5 - Root Mean Squared Error (RMSE): 22.91
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 498.97
Mean - Mean Absolute Error (MAE): 16.62
Mean - Root Mean Squared Error (RMSE): 22.33
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 197.36
Fold 1 - Mean Absolute Error (MAE): 11.55
Fold 1 - Root Mean Squared Error (RMSE): 14.05
Fold 1 - Time taken: 2.70 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 217.93
Fold 2 - Mean Absolute Error (MAE): 12.05
Fold 2 - Root Mean Squared Error (RMSE): 14.76
Fold 2 - Time taken: 3.42 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 229.21
Fold 3 - Mean Absolute Error (MAE): 12.19
Fold 3 - Root Mean Squared Error (RMSE): 15.14
Fold 3 - Time taken: 4.11 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 192.75
Fold 4 - Mean Absolute Error (MAE): 11.34
Fold 4 - Root Mean Squared Error (RMSE): 13.88
Fold 4 - Time taken: 4.09 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 201.36
Fold 5 - Mean Absolute Error (MAE): 11.60
Fold 5 - Root Mean Squared Error (RMSE): 14.19
Fold 5 - Time taken: 4.12 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 207.72
Mean - Mean Absolute Error (MAE): 11.75
Mean - Root Mean Squared Error (RMSE): 14.40
Mean - Time taken: 3.69 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 163.63
Fold 1 - Mean Absolute Error (MAE): 10.17
Fold 1 - Root Mean Squared Error (RMSE): 12.79
Fold 1 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 158.77
Fold 2 - Mean Absolute Error (MAE): 9.99
Fold 2 - Root Mean Squared Error (RMSE): 12.60
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 175.88
Fold 3 - Mean Absolute Error (MAE): 10.65
Fold 3 - Root Mean Squared Error (RMSE): 13.26
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 164.90
Fold 4 - Mean Absolute Error (MAE): 10.25
Fold 4 - Root Mean Squared Error (RMSE): 12.84
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 172.30
Fold 5 - Mean Absolute Error (MAE): 10.46
Fold 5 - Root Mean Squared Error (RMSE): 13.13
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 167.10
Mean - Mean Absolute Error (MAE): 10.30
Mean - Root Mean Squared Error (RMSE): 12.92
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 176.59
Fold 1 - Mean Absolute Error (MAE): 10.46
Fold 1 - Root Mean Squared Error (RMSE): 13.29
Fold 1 - Time taken: 2.02 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 198.18
Fold 2 - Mean Absolute Error (MAE): 11.04
Fold 2 - Root Mean Squared Error (RMSE): 14.08
Fold 2 - Time taken: 2.01 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 207.16
Fold 3 - Mean Absolute Error (MAE): 11.14
Fold 3 - Root Mean Squared Error (RMSE): 14.39
Fold 3 - Time taken: 1.98 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 174.78
Fold 4 - Mean Absolute Error (MAE): 10.32
Fold 4 - Root Mean Squared Error (RMSE): 13.22
Fold 4 - Time taken: 2.00 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 192.55
Fold 5 - Mean Absolute Error (MAE): 10.91
Fold 5 - Root Mean Squared Error (RMSE): 13.88
Fold 5 - Time taken: 1.98 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 189.85
Mean - Mean Absolute Error (MAE): 10.77
Mean - Root Mean Squared Error (RMSE): 13.77
Mean - Time taken: 2.00 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_Scattered_iReg2.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_Scattered_iReg2.xlsx file")

Results saved to Results__PL_model_2_Scattered_iReg2.xlsx file