# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing1_iReg2.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,66.720362,70.472225,56.022131,69.615502,70.920891,76.205256,65.312046,76.783781,66.998074,67.821152,...,68.770784,66.104511,65.538687,63.934924,71.998162,68.722180,66.494946,69.719336,49.339660,71.526458
1,66.861115,70.346837,55.854726,69.863441,71.117415,75.795258,65.279444,76.813717,66.992744,67.860327,...,69.211473,65.929991,65.168911,63.889588,72.076508,68.908584,66.740806,69.658496,49.241778,71.291433
2,66.810516,70.403370,55.879860,69.693334,70.936307,75.445636,65.402451,76.903100,66.737564,68.066349,...,69.097179,65.816289,65.529600,63.891041,72.487731,68.863496,67.201566,69.859366,49.425856,71.255513
3,66.839383,70.286452,55.824614,69.686411,70.772802,75.347255,64.841846,77.318551,66.681033,68.296759,...,68.913081,65.973715,65.541494,63.865958,72.676739,69.079112,67.063966,70.135703,48.996669,71.230804
4,66.733063,70.754979,55.743733,69.972551,70.444707,75.422072,64.711931,76.969568,65.978494,67.792779,...,68.693240,65.754548,66.300478,63.949047,72.626921,69.114627,66.619799,69.999278,49.003874,71.153164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,72.601373,66.341384,67.337881,55.825223,77.967400,71.910312,72.692030,71.046740,68.724946,62.172037,...,67.937644,73.549670,69.290666,54.746139,76.726063,67.576495,75.640683,62.731838,68.047644,59.138689
2439,72.315456,66.774758,66.888220,55.853188,77.962237,71.643323,72.684745,70.870263,69.436552,62.187217,...,67.982420,73.428162,69.001879,54.655717,76.700567,67.796478,75.744320,62.685795,67.877887,59.035888
2440,72.304377,66.725390,66.976145,55.841109,78.062979,71.641237,72.796626,70.668382,69.126593,61.761723,...,68.239644,73.255665,69.127211,54.661539,76.238937,67.611005,75.918019,62.714834,67.932558,58.890512
2441,72.013995,66.609345,66.781691,56.113330,78.307970,71.632529,72.938150,70.811151,68.886790,61.889437,...,68.130556,72.948675,68.928867,55.183831,76.239997,67.502674,76.065982,62.303248,67.774467,59.022633
2442,71.686132,66.791573,66.392684,55.839944,78.047322,71.430428,72.906105,70.959872,69.033621,61.594370,...,68.414709,72.538691,68.806358,55.265778,76.492998,67.541065,76.007901,62.471803,67.578108,58.761440

In [4]:
position_data = pd.read_excel('real_positions_iReg2.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,66.720362,70.472225,56.022131,69.615502,70.920891,76.205256,65.312046,76.783781,66.998074,67.821152,...,68.770784,66.104511,65.538687,63.934924,71.998162,68.722180,66.494946,69.719336,49.339660,71.526458
1,66.861115,70.346837,55.854726,69.863441,71.117415,75.795258,65.279444,76.813717,66.992744,67.860327,...,69.211473,65.929991,65.168911,63.889588,72.076508,68.908584,66.740806,69.658496,49.241778,71.291433
2,66.810516,70.403370,55.879860,69.693334,70.936307,75.445636,65.402451,76.903100,66.737564,68.066349,...,69.097179,65.816289,65.529600,63.891041,72.487731,68.863496,67.201566,69.859366,49.425856,71.255513
3,66.839383,70.286452,55.824614,69.686411,70.772802,75.347255,64.841846,77.318551,66.681033,68.296759,...,68.913081,65.973715,65.541494,63.865958,72.676739,69.079112,67.063966,70.135703,48.996669,71.230804
4,66.733063,70.754979,55.743733,69.972551,70.444707,75.422072,64.711931,76.969568,65.978494,67.792779,...,68.693240,65.754548,66.300478,63.949047,72.626921,69.114627,66.619799,69.999278,49.003874,71.153164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,72.601373,66.341384,67.337881,55.825223,77.967400,71.910312,72.692030,71.046740,68.724946,62.172037,...,67.937644,73.549670,69.290666,54.746139,76.726063,67.576495,75.640683,62.731838,68.047644,59.138689
2439,72.315456,66.774758,66.888220,55.853188,77.962237,71.643323,72.684745,70.870263,69.436552,62.187217,...,67.982420,73.428162,69.001879,54.655717,76.700567,67.796478,75.744320,62.685795,67.877887,59.035888
2440,72.304377,66.725390,66.976145,55.841109,78.062979,71.641237,72.796626,70.668382,69.126593,61.761723,...,68.239644,73.255665,69.127211,54.661539,76.238937,67.611005,75.918019,62.714834,67.932558,58.890512
2441,72.013995,66.609345,66.781691,56.113330,78.307970,71.632529,72.938150,70.811151,68.886790,61.889437,...,68.130556,72.948675,68.928867,55.183831,76.239997,67.502674,76.065982,62.303248,67.774467,59.022633
2442,71.686132,66.791573,66.392684,55.839944,78.047322,71.430428,72.906105,70.959872,69.033621,61.594370,...,68.414709,72.538691,68.806358,55.265778,76.492998,67.541065,76.007901,62.471803,67.578108,58.761440

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 1.31
Fold 1 - Mean Absolute Error (MAE): 0.94
Fold 1 - Root Mean Squared Error (RMSE): 1.15
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 1.30
Fold 2 - Mean Absolute Error (MAE): 0.91
Fold 2 - Root Mean Squared Error (RMSE): 1.14
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 1.35
Fold 3 - Mean Absolute Error (MAE): 0.93
Fold 3 - Root Mean Squared Error (RMSE): 1.16
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 1.33
Fold 4 - Mean Absolute Error (MAE): 0.92
Fold 4 - Root Mean Squared Error (RMSE): 1.15
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 1.39
Fold 5 - Mean Absolute Error (MAE): 0.95
Fold 5 - Root Mean Squared Error (RMSE): 1.18
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 1.34
Mean - Mean Absolute Error (MAE): 0.93
Mean - Root Mean Squared Error (RMSE): 1.16
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 1.73
Fold 1 - Mean Absolute Error (MAE): 0.56
Fold 1 - Root Mean Squared Error (RMSE): 1.31
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 2.74
Fold 2 - Mean Absolute Error (MAE): 0.66
Fold 2 - Root Mean Squared Error (RMSE): 1.66
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 1.03
Fold 3 - Mean Absolute Error (MAE): 0.54
Fold 3 - Root Mean Squared Error (RMSE): 1.02
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 3.99
Fold 4 - Mean Absolute Error (MAE): 0.67
Fold 4 - Root Mean Squared Error (RMSE): 2.00
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 1.95
Fold 5 - Mean Absolute Error (MAE): 0.65
Fold 5 - Root Mean Squared Error (RMSE): 1.40
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 2.29
Mean - Mean Absolute Error (MAE): 0.62
Mean - Root Mean Squared Error (RMSE): 1.48
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.29
Fold 1 - Mean Absolute Error (MAE): 0.29
Fold 1 - Root Mean Squared Error (RMSE): 0.54
Fold 1 - Time taken: 2.31 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.88
Fold 2 - Mean Absolute Error (MAE): 0.30
Fold 2 - Root Mean Squared Error (RMSE): 0.94
Fold 2 - Time taken: 2.26 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.25
Fold 3 - Mean Absolute Error (MAE): 0.29
Fold 3 - Root Mean Squared Error (RMSE): 0.50
Fold 3 - Time taken: 3.62 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.29
Fold 4 - Mean Absolute Error (MAE): 0.30
Fold 4 - Root Mean Squared Error (RMSE): 0.54
Fold 4 - Time taken: 3.67 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.42
Fold 5 - Mean Absolute Error (MAE): 0.31
Fold 5 - Root Mean Squared Error (RMSE): 0.65
Fold 5 - Time taken: 3.50 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.43
Mean - Mean Absolute Error (MAE): 0.29
Mean - Root Mean Squared Error (RMSE): 0.63
Mean - Time taken: 3.07 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.05
Fold 1 - Mean Absolute Error (MAE): 0.15
Fold 1 - Root Mean Squared Error (RMSE): 0.23
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.06
Fold 2 - Mean Absolute Error (MAE): 0.15
Fold 2 - Root Mean Squared Error (RMSE): 0.25
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.07
Fold 3 - Mean Absolute Error (MAE): 0.17
Fold 3 - Root Mean Squared Error (RMSE): 0.27
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.07
Fold 4 - Mean Absolute Error (MAE): 0.16
Fold 4 - Root Mean Squared Error (RMSE): 0.26
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.08
Fold 5 - Mean Absolute Error (MAE): 0.17
Fold 5 - Root Mean Squared Error (RMSE): 0.29
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.07
Mean - Mean Absolute Error (MAE): 0.16
Mean - Root Mean Squared Error (RMSE): 0.26
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.71
Fold 1 - Mean Absolute Error (MAE): 0.69
Fold 1 - Root Mean Squared Error (RMSE): 1.31
Fold 1 - Time taken: 1.86 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 1.13
Fold 2 - Mean Absolute Error (MAE): 0.64
Fold 2 - Root Mean Squared Error (RMSE): 1.06
Fold 2 - Time taken: 1.84 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.12
Fold 3 - Mean Absolute Error (MAE): 0.64
Fold 3 - Root Mean Squared Error (RMSE): 1.06
Fold 3 - Time taken: 1.87 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1.35
Fold 4 - Mean Absolute Error (MAE): 0.67
Fold 4 - Root Mean Squared Error (RMSE): 1.16
Fold 4 - Time taken: 1.90 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.48
Fold 5 - Mean Absolute Error (MAE): 0.70
Fold 5 - Root Mean Squared Error (RMSE): 1.22
Fold 5 - Time taken: 1.90 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1.36
Mean - Mean Absolute Error (MAE): 0.67
Mean - Root Mean Squared Error (RMSE): 1.16
Mean - Time taken: 1.87 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing1_iReg2.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing1_iReg2.xlsx file")

Results saved to Results__PL_model_2_smoothing1_iReg2.xlsx file