# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing2_iReg2.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,68.129301,71.602329,55.566067,67.590334,75.557613,74.326944,66.452069,78.387676,65.852280,67.993772,...,69.092923,66.696309,66.494276,58.445127,70.944787,71.395686,62.010039,68.899007,50.356404,68.908219
1,68.035894,71.623981,55.538732,67.779734,75.282046,74.413560,66.380999,78.312352,65.915155,67.988997,...,69.112455,66.666759,66.398256,58.768554,70.997386,71.277318,62.345321,69.004014,50.254800,68.960169
2,67.946655,71.642390,55.514654,67.967263,75.007580,74.498252,66.308489,78.232556,65.980046,67.982031,...,69.129310,66.632012,66.303579,59.091246,71.054836,71.156952,62.672196,69.106379,50.152661,69.014478
3,67.861605,71.657607,55.493962,68.152722,74.733780,74.581274,66.234837,78.148603,66.046341,67.973490,...,69.142988,66.592768,66.210409,59.413656,71.117042,71.035096,62.990739,69.206157,50.050893,69.070711
4,67.780951,71.669690,55.476651,68.335938,74.460013,74.663090,66.160138,78.061036,66.113528,67.964337,...,69.153419,66.550110,66.119093,59.735944,71.183841,70.912473,63.301306,69.303778,49.950698,69.128143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,67.333851,64.500719,66.541245,58.995487,76.127768,69.651740,77.570858,70.476723,67.658123,62.433644,...,68.513270,69.794561,68.979456,57.097427,77.841612,64.803516,75.667654,63.063683,69.339919,61.270723
2439,67.010521,64.316341,66.512357,59.273114,75.965636,69.466500,77.948412,70.418010,67.472554,62.485466,...,68.662873,69.572002,68.997878,57.215836,77.969706,64.588792,75.686065,63.087391,69.390372,61.484816
2440,66.688657,64.129001,66.487479,59.556813,75.800057,69.278591,78.329484,70.359714,67.282371,62.536592,...,68.819489,69.355756,69.012774,57.329919,78.098090,64.370833,75.703789,63.112468,69.445841,61.703037
2441,66.368395,63.938350,66.466576,59.845856,75.631228,69.088439,78.714694,70.301585,67.087365,62.586759,...,68.982778,69.145980,69.024584,57.439836,78.227143,64.150293,75.720567,63.139494,69.506202,61.925605
2442,66.049673,63.743977,66.449764,60.139546,75.459487,68.896620,79.104324,70.243198,66.887418,62.635497,...,69.152596,68.942484,69.033459,57.545581,78.357179,63.927939,75.736503,63.169230,69.571175,62.152394

In [4]:
position_data = pd.read_excel('real_positions_iReg2.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,68.129301,71.602329,55.566067,67.590334,75.557613,74.326944,66.452069,78.387676,65.852280,67.993772,...,69.092923,66.696309,66.494276,58.445127,70.944787,71.395686,62.010039,68.899007,50.356404,68.908219
1,68.035894,71.623981,55.538732,67.779734,75.282046,74.413560,66.380999,78.312352,65.915155,67.988997,...,69.112455,66.666759,66.398256,58.768554,70.997386,71.277318,62.345321,69.004014,50.254800,68.960169
2,67.946655,71.642390,55.514654,67.967263,75.007580,74.498252,66.308489,78.232556,65.980046,67.982031,...,69.129310,66.632012,66.303579,59.091246,71.054836,71.156952,62.672196,69.106379,50.152661,69.014478
3,67.861605,71.657607,55.493962,68.152722,74.733780,74.581274,66.234837,78.148603,66.046341,67.973490,...,69.142988,66.592768,66.210409,59.413656,71.117042,71.035096,62.990739,69.206157,50.050893,69.070711
4,67.780951,71.669690,55.476651,68.335938,74.460013,74.663090,66.160138,78.061036,66.113528,67.964337,...,69.153419,66.550110,66.119093,59.735944,71.183841,70.912473,63.301306,69.303778,49.950698,69.128143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,67.333851,64.500719,66.541245,58.995487,76.127768,69.651740,77.570858,70.476723,67.658123,62.433644,...,68.513270,69.794561,68.979456,57.097427,77.841612,64.803516,75.667654,63.063683,69.339919,61.270723
2439,67.010521,64.316341,66.512357,59.273114,75.965636,69.466500,77.948412,70.418010,67.472554,62.485466,...,68.662873,69.572002,68.997878,57.215836,77.969706,64.588792,75.686065,63.087391,69.390372,61.484816
2440,66.688657,64.129001,66.487479,59.556813,75.800057,69.278591,78.329484,70.359714,67.282371,62.536592,...,68.819489,69.355756,69.012774,57.329919,78.098090,64.370833,75.703789,63.112468,69.445841,61.703037
2441,66.368395,63.938350,66.466576,59.845856,75.631228,69.088439,78.714694,70.301585,67.087365,62.586759,...,68.982778,69.145980,69.024584,57.439836,78.227143,64.150293,75.720567,63.139494,69.506202,61.925605
2442,66.049673,63.743977,66.449764,60.139546,75.459487,68.896620,79.104324,70.243198,66.887418,62.635497,...,69.152596,68.942484,69.033459,57.545581,78.357179,63.927939,75.736503,63.169230,69.571175,62.152394

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 3.97
Fold 1 - Mean Absolute Error (MAE): 1.62
Fold 1 - Root Mean Squared Error (RMSE): 1.99
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 4.12
Fold 2 - Mean Absolute Error (MAE): 1.63
Fold 2 - Root Mean Squared Error (RMSE): 2.03
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 3.87
Fold 3 - Mean Absolute Error (MAE): 1.57
Fold 3 - Root Mean Squared Error (RMSE): 1.97
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 4.14
Fold 4 - Mean Absolute Error (MAE): 1.63
Fold 4 - Root Mean Squared Error (RMSE): 2.03
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 3.94
Fold 5 - Mean Absolute Error (MAE): 1.58
Fold 5 - Root Mean Squared Error (RMSE): 1.98
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 4.01
Mean - Mean Absolute Error (MAE): 1.61
Mean - Root Mean Squared Error (RMSE): 2.00
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 1.23
Fold 1 - Mean Absolute Error (MAE): 0.34
Fold 1 - Root Mean Squared Error (RMSE): 1.11
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 3.17
Fold 2 - Mean Absolute Error (MAE): 0.47
Fold 2 - Root Mean Squared Error (RMSE): 1.78
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 2.13
Fold 3 - Mean Absolute Error (MAE): 0.40
Fold 3 - Root Mean Squared Error (RMSE): 1.46
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 6.81
Fold 4 - Mean Absolute Error (MAE): 0.52
Fold 4 - Root Mean Squared Error (RMSE): 2.61
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 4.73
Fold 5 - Mean Absolute Error (MAE): 0.44
Fold 5 - Root Mean Squared Error (RMSE): 2.17
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 3.61
Mean - Mean Absolute Error (MAE): 0.44
Mean - Root Mean Squared Error (RMSE): 1.83
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.19
Fold 1 - Mean Absolute Error (MAE): 0.21
Fold 1 - Root Mean Squared Error (RMSE): 0.44
Fold 1 - Time taken: 2.23 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.31
Fold 2 - Mean Absolute Error (MAE): 0.24
Fold 2 - Root Mean Squared Error (RMSE): 0.56
Fold 2 - Time taken: 2.21 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.34
Fold 3 - Mean Absolute Error (MAE): 0.26
Fold 3 - Root Mean Squared Error (RMSE): 0.58
Fold 3 - Time taken: 3.13 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.31
Fold 4 - Mean Absolute Error (MAE): 0.27
Fold 4 - Root Mean Squared Error (RMSE): 0.55
Fold 4 - Time taken: 3.37 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.36
Fold 5 - Mean Absolute Error (MAE): 0.26
Fold 5 - Root Mean Squared Error (RMSE): 0.60
Fold 5 - Time taken: 3.59 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.30
Mean - Mean Absolute Error (MAE): 0.25
Mean - Root Mean Squared Error (RMSE): 0.55
Mean - Time taken: 2.90 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.04
Fold 1 - Mean Absolute Error (MAE): 0.13
Fold 1 - Root Mean Squared Error (RMSE): 0.20
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.05
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.21
Fold 2 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.06
Fold 3 - Mean Absolute Error (MAE): 0.15
Fold 3 - Root Mean Squared Error (RMSE): 0.23
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.05
Fold 4 - Mean Absolute Error (MAE): 0.14
Fold 4 - Root Mean Squared Error (RMSE): 0.22
Fold 4 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.05
Fold 5 - Mean Absolute Error (MAE): 0.15
Fold 5 - Root Mean Squared Error (RMSE): 0.23
Fold 5 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.05
Mean - Mean Absolute Error (MAE): 0.14
Mean - Root Mean Squared Error (RMSE): 0.22
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.79
Fold 1 - Mean Absolute Error (MAE): 0.44
Fold 1 - Root Mean Squared Error (RMSE): 0.89
Fold 1 - Time taken: 1.88 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 1.03
Fold 2 - Mean Absolute Error (MAE): 0.49
Fold 2 - Root Mean Squared Error (RMSE): 1.01
Fold 2 - Time taken: 1.84 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.03
Fold 3 - Mean Absolute Error (MAE): 0.50
Fold 3 - Root Mean Squared Error (RMSE): 1.01
Fold 3 - Time taken: 1.82 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.94
Fold 4 - Mean Absolute Error (MAE): 0.47
Fold 4 - Root Mean Squared Error (RMSE): 0.97
Fold 4 - Time taken: 2.37 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 0.81
Fold 5 - Mean Absolute Error (MAE): 0.48
Fold 5 - Root Mean Squared Error (RMSE): 0.90
Fold 5 - Time taken: 2.35 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 0.92
Mean - Mean Absolute Error (MAE): 0.48
Mean - Root Mean Squared Error (RMSE): 0.96
Mean - Time taken: 2.05 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing2_iReg2.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing2_iReg2.xlsx file")

Results saved to Results__PL_model_2_smoothing2_iReg2.xlsx file