# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing2_Reg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,87.362170,92.059179,81.639492,83.046279,87.557608,88.829065,86.304978,91.903081,90.974425,87.964761,...,80.716972,82.980276,91.631634,83.478056,87.786838,89.127069,80.956526,92.613983,77.410061,81.618024
1,87.314653,91.868510,81.753510,83.102770,87.667622,89.014976,86.405655,91.761364,90.912489,88.054400,...,80.811359,82.990759,91.367214,83.430809,87.885892,88.975725,81.054012,92.393965,77.261457,81.568429
2,87.265068,91.681240,81.863257,83.160659,87.776139,89.204368,86.502722,91.621445,90.850914,88.142340,...,80.909673,82.999959,91.107171,83.381318,87.981265,88.825590,81.151156,92.174215,77.116598,81.522525
3,87.213900,91.497346,81.968488,83.220587,87.883528,89.397035,86.596130,91.482991,90.789162,88.228029,...,81.011722,83.008250,90.851560,83.329554,88.072869,88.677138,81.247568,91.955906,76.975967,81.480128
4,87.161546,91.316921,82.068671,83.283040,87.990020,89.592487,86.686142,91.345397,90.726820,88.311044,...,81.117124,83.015760,90.600178,83.275815,88.160725,88.530710,81.342925,91.740266,76.839861,81.440740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,91.606026,88.069788,79.531699,85.419493,91.976891,92.243208,87.175784,88.590557,91.681913,90.119286,...,84.995612,87.574274,86.411497,79.268845,90.031115,86.998545,84.367165,86.580171,78.319799,79.437264
2439,91.746546,88.072322,79.441336,85.618475,91.938881,92.245196,87.057803,88.739174,91.794750,90.221004,...,85.070026,87.674484,86.261152,79.277755,89.975204,86.894393,84.210259,86.641084,78.327737,79.590486
2440,91.887422,88.071942,79.354928,85.820510,91.904210,92.245867,86.937141,88.888750,91.904207,90.319187,...,85.149368,87.775550,86.108531,79.287771,89.921318,86.790128,84.051367,86.698728,78.334857,79.743283
2441,92.028156,88.068195,79.272625,86.026023,91.872413,92.245207,86.814066,89.039560,92.010556,90.413832,...,85.234268,87.876485,85.954382,79.298734,89.869081,86.686079,83.891148,86.753257,78.341213,79.895198
2442,92.168162,88.060630,79.194408,86.235405,91.843085,92.243320,86.689144,89.192029,92.114117,90.504833,...,85.324974,87.976567,85.799219,79.310773,89.818353,86.582394,83.730161,86.805090,78.347071,80.045589

In [4]:
position_data = pd.read_excel('real_positions_Reg2_3.xlsx', header=None)

In [5]:
position_data

              0          1       2
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,87.362170,92.059179,81.639492,83.046279,87.557608,88.829065,86.304978,91.903081,90.974425,87.964761,...,80.716972,82.980276,91.631634,83.478056,87.786838,89.127069,80.956526,92.613983,77.410061,81.618024
1,87.314653,91.868510,81.753510,83.102770,87.667622,89.014976,86.405655,91.761364,90.912489,88.054400,...,80.811359,82.990759,91.367214,83.430809,87.885892,88.975725,81.054012,92.393965,77.261457,81.568429
2,87.265068,91.681240,81.863257,83.160659,87.776139,89.204368,86.502722,91.621445,90.850914,88.142340,...,80.909673,82.999959,91.107171,83.381318,87.981265,88.825590,81.151156,92.174215,77.116598,81.522525
3,87.213900,91.497346,81.968488,83.220587,87.883528,89.397035,86.596130,91.482991,90.789162,88.228029,...,81.011722,83.008250,90.851560,83.329554,88.072869,88.677138,81.247568,91.955906,76.975967,81.480128
4,87.161546,91.316921,82.068671,83.283040,87.990020,89.592487,86.686142,91.345397,90.726820,88.311044,...,81.117124,83.015760,90.600178,83.275815,88.160725,88.530710,81.342925,91.740266,76.839861,81.440740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,91.606026,88.069788,79.531699,85.419493,91.976891,92.243208,87.175784,88.590557,91.681913,90.119286,...,84.995612,87.574274,86.411497,79.268845,90.031115,86.998545,84.367165,86.580171,78.319799,79.437264
2439,91.746546,88.072322,79.441336,85.618475,91.938881,92.245196,87.057803,88.739174,91.794750,90.221004,...,85.070026,87.674484,86.261152,79.277755,89.975204,86.894393,84.210259,86.641084,78.327737,79.590486
2440,91.887422,88.071942,79.354928,85.820510,91.904210,92.245867,86.937141,88.888750,91.904207,90.319187,...,85.149368,87.775550,86.108531,79.287771,89.921318,86.790128,84.051367,86.698728,78.334857,79.743283
2441,92.028156,88.068195,79.272625,86.026023,91.872413,92.245207,86.814066,89.039560,92.010556,90.413832,...,85.234268,87.876485,85.954382,79.298734,89.869081,86.686079,83.891148,86.753257,78.341213,79.895198
2442,92.168162,88.060630,79.194408,86.235405,91.843085,92.243320,86.689144,89.192029,92.114117,90.504833,...,85.324974,87.976567,85.799219,79.310773,89.818353,86.582394,83.730161,86.805090,78.347071,80.045589

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y   Pos Z
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 62.28
Fold 1 - Mean Absolute Error (MAE): 5.75
Fold 1 - Root Mean Squared Error (RMSE): 7.89
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 63.14
Fold 2 - Mean Absolute Error (MAE): 5.77
Fold 2 - Root Mean Squared Error (RMSE): 7.95
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 64.35
Fold 3 - Mean Absolute Error (MAE): 5.83
Fold 3 - Root Mean Squared Error (RMSE): 8.02
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 66.68
Fold 4 - Mean Absolute Error (MAE): 5.89
Fold 4 - Root Mean Squared Error (RMSE): 8.17
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 60.13
Fold 5 - Mean Absolute Error (MAE): 5.66
Fold 5 - Root Mean Squared Error (RMSE): 7.75
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 63.32
Mean - Mean Absolute Error (MAE): 5.78
Mean - Root Mean Squared Error (RMSE): 7.96
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 53.79
Fold 1 - Mean Absolute Error (MAE): 1.34
Fold 1 - Root Mean Squared Error (RMSE): 7.33
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 38.72
Fold 2 - Mean Absolute Error (MAE): 1.04
Fold 2 - Root Mean Squared Error (RMSE): 6.22
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 28.84
Fold 3 - Mean Absolute Error (MAE): 1.00
Fold 3 - Root Mean Squared Error (RMSE): 5.37
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 8.66
Fold 4 - Mean Absolute Error (MAE): 0.56
Fold 4 - Root Mean Squared Error (RMSE): 2.94
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 20.26
Fold 5 - Mean Absolute Error (MAE): 0.99
Fold 5 - Root Mean Squared Error (RMSE): 4.50
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 30.06
Mean - Mean Absolute Error (MAE): 0.99
Mean - Root Mean Squared Error (RMSE): 5.27
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 2.32
Fold 1 - Mean Absolute Error (MAE): 0.81
Fold 1 - Root Mean Squared Error (RMSE): 1.52
Fold 1 - Time taken: 2.37 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 5.50
Fold 2 - Mean Absolute Error (MAE): 0.97
Fold 2 - Root Mean Squared Error (RMSE): 2.35
Fold 2 - Time taken: 2.32 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 6.06
Fold 3 - Mean Absolute Error (MAE): 0.90
Fold 3 - Root Mean Squared Error (RMSE): 2.46
Fold 3 - Time taken: 3.48 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 7.02
Fold 4 - Mean Absolute Error (MAE): 0.88
Fold 4 - Root Mean Squared Error (RMSE): 2.65
Fold 4 - Time taken: 3.63 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 4.36
Fold 5 - Mean Absolute Error (MAE): 0.86
Fold 5 - Root Mean Squared Error (RMSE): 2.09
Fold 5 - Time taken: 3.61 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 5.05
Mean - Mean Absolute Error (MAE): 0.88
Mean - Root Mean Squared Error (RMSE): 2.21
Mean - Time taken: 3.08 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.09
Fold 1 - Mean Absolute Error (MAE): 0.19
Fold 1 - Root Mean Squared Error (RMSE): 0.30
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.11
Fold 2 - Mean Absolute Error (MAE): 0.20
Fold 2 - Root Mean Squared Error (RMSE): 0.32
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.13
Fold 3 - Mean Absolute Error (MAE): 0.20
Fold 3 - Root Mean Squared Error (RMSE): 0.35
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.11
Fold 4 - Mean Absolute Error (MAE): 0.20
Fold 4 - Root Mean Squared Error (RMSE): 0.34
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.11
Fold 5 - Mean Absolute Error (MAE): 0.20
Fold 5 - Root Mean Squared Error (RMSE): 0.33
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.11
Mean - Mean Absolute Error (MAE): 0.20
Mean - Root Mean Squared Error (RMSE): 0.33
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 7.04
Fold 1 - Mean Absolute Error (MAE): 1.12
Fold 1 - Root Mean Squared Error (RMSE): 2.65
Fold 1 - Time taken: 1.89 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 5.86
Fold 2 - Mean Absolute Error (MAE): 1.17
Fold 2 - Root Mean Squared Error (RMSE): 2.42
Fold 2 - Time taken: 1.86 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 5.40
Fold 3 - Mean Absolute Error (MAE): 1.12
Fold 3 - Root Mean Squared Error (RMSE): 2.32
Fold 3 - Time taken: 1.87 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 9.25
Fold 4 - Mean Absolute Error (MAE): 1.31
Fold 4 - Root Mean Squared Error (RMSE): 3.04
Fold 4 - Time taken: 1.88 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 5.18
Fold 5 - Mean Absolute Error (MAE): 1.11
Fold 5 - Root Mean Squared Error (RMSE): 2.28
Fold 5 - Time taken: 1.88 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 6.55
Mean - Mean Absolute Error (MAE): 1.17
Mean - Root Mean Squared Error (RMSE): 2.54
Mean - Time taken: 1.88 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing2_Reg3.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing2_Reg3.xlsx file")

Results saved to Results__PL_model_2_smoothing2_Reg3.xlsx file