# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing1_Reg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,86.474506,88.704403,82.639125,83.727940,88.522842,91.993564,87.061084,90.346654,90.197267,88.016072,...,82.734058,82.876381,87.862629,83.190713,89.302300,86.885863,82.679101,89.251506,76.241020,81.242401
1,87.097580,89.080518,82.407856,83.771566,88.545131,91.921942,87.246513,89.794374,89.922371,88.151341,...,83.293134,83.051687,87.890651,82.964816,89.355104,87.064988,82.883981,89.012599,76.356958,81.722744
2,87.261515,89.027883,82.384026,83.865495,88.667173,92.175730,87.019149,89.618165,89.934151,87.841048,...,83.220237,83.210094,87.608707,82.974061,89.195045,87.044838,82.708135,88.765746,76.555252,81.801832
3,87.482548,88.876063,82.268035,84.046756,89.009087,92.392985,87.425092,89.652052,89.896348,88.129031,...,83.392148,83.142568,87.359826,82.858619,89.494011,87.414908,82.612739,88.662205,76.529228,81.548127
4,87.452021,88.920963,82.182759,84.471407,89.133617,92.684736,87.285199,89.631959,89.937344,88.403344,...,83.225027,83.251213,87.263240,83.043622,89.165392,87.395030,82.838681,88.255191,76.729186,81.543631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,90.833031,87.866926,83.062002,82.561272,93.627726,91.997922,88.743257,86.755749,89.662795,88.103421,...,84.756427,86.803463,88.673935,79.702073,90.562447,88.648488,86.485949,85.573430,77.933595,76.794969
2439,90.751680,87.549299,83.002549,82.430121,93.394111,92.220490,88.824007,87.079787,89.885462,88.132921,...,84.850316,87.100930,88.536268,79.421433,90.419617,88.681114,86.032256,85.251377,78.089242,77.124041
2440,90.472239,87.427284,82.747883,82.548230,93.024337,92.256531,88.933373,86.786145,89.595458,88.475013,...,84.652360,87.258071,88.611640,79.397743,89.887686,88.356211,85.608738,85.345970,77.760505,77.539171
2441,90.538150,87.272426,83.007167,82.748681,92.825691,92.209180,88.766609,86.911457,89.809041,88.482085,...,84.768161,87.141975,88.706291,79.399100,89.816903,88.266936,85.837902,85.504951,77.554314,77.436131
2442,90.797108,87.456333,83.071067,82.885801,92.924875,91.983571,88.543770,87.178056,89.831496,88.745970,...,84.883955,87.062526,88.400405,79.274087,90.083610,88.031765,85.665470,85.801330,77.706967,77.327934

In [4]:
position_data = pd.read_excel('real_positions_Reg2_3.xlsx', header=None)

In [5]:
position_data

              0          1       2
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,86.474506,88.704403,82.639125,83.727940,88.522842,91.993564,87.061084,90.346654,90.197267,88.016072,...,82.734058,82.876381,87.862629,83.190713,89.302300,86.885863,82.679101,89.251506,76.241020,81.242401
1,87.097580,89.080518,82.407856,83.771566,88.545131,91.921942,87.246513,89.794374,89.922371,88.151341,...,83.293134,83.051687,87.890651,82.964816,89.355104,87.064988,82.883981,89.012599,76.356958,81.722744
2,87.261515,89.027883,82.384026,83.865495,88.667173,92.175730,87.019149,89.618165,89.934151,87.841048,...,83.220237,83.210094,87.608707,82.974061,89.195045,87.044838,82.708135,88.765746,76.555252,81.801832
3,87.482548,88.876063,82.268035,84.046756,89.009087,92.392985,87.425092,89.652052,89.896348,88.129031,...,83.392148,83.142568,87.359826,82.858619,89.494011,87.414908,82.612739,88.662205,76.529228,81.548127
4,87.452021,88.920963,82.182759,84.471407,89.133617,92.684736,87.285199,89.631959,89.937344,88.403344,...,83.225027,83.251213,87.263240,83.043622,89.165392,87.395030,82.838681,88.255191,76.729186,81.543631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,90.833031,87.866926,83.062002,82.561272,93.627726,91.997922,88.743257,86.755749,89.662795,88.103421,...,84.756427,86.803463,88.673935,79.702073,90.562447,88.648488,86.485949,85.573430,77.933595,76.794969
2439,90.751680,87.549299,83.002549,82.430121,93.394111,92.220490,88.824007,87.079787,89.885462,88.132921,...,84.850316,87.100930,88.536268,79.421433,90.419617,88.681114,86.032256,85.251377,78.089242,77.124041
2440,90.472239,87.427284,82.747883,82.548230,93.024337,92.256531,88.933373,86.786145,89.595458,88.475013,...,84.652360,87.258071,88.611640,79.397743,89.887686,88.356211,85.608738,85.345970,77.760505,77.539171
2441,90.538150,87.272426,83.007167,82.748681,92.825691,92.209180,88.766609,86.911457,89.809041,88.482085,...,84.768161,87.141975,88.706291,79.399100,89.816903,88.266936,85.837902,85.504951,77.554314,77.436131
2442,90.797108,87.456333,83.071067,82.885801,92.924875,91.983571,88.543770,87.178056,89.831496,88.745970,...,84.883955,87.062526,88.400405,79.274087,90.083610,88.031765,85.665470,85.801330,77.706967,77.327934

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y   Pos Z
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 23.47
Fold 1 - Mean Absolute Error (MAE): 3.49
Fold 1 - Root Mean Squared Error (RMSE): 4.84
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 23.63
Fold 2 - Mean Absolute Error (MAE): 3.50
Fold 2 - Root Mean Squared Error (RMSE): 4.86
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 22.53
Fold 3 - Mean Absolute Error (MAE): 3.46
Fold 3 - Root Mean Squared Error (RMSE): 4.75
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 26.13
Fold 4 - Mean Absolute Error (MAE): 3.59
Fold 4 - Root Mean Squared Error (RMSE): 5.11
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 25.07
Fold 5 - Mean Absolute Error (MAE): 3.60
Fold 5 - Root Mean Squared Error (RMSE): 5.01
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 24.17
Mean - Mean Absolute Error (MAE): 3.53
Mean - Root Mean Squared Error (RMSE): 4.91
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 15.46
Fold 1 - Mean Absolute Error (MAE): 1.16
Fold 1 - Root Mean Squared Error (RMSE): 3.93
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 15.75
Fold 2 - Mean Absolute Error (MAE): 1.28
Fold 2 - Root Mean Squared Error (RMSE): 3.97
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 34.98
Fold 3 - Mean Absolute Error (MAE): 1.86
Fold 3 - Root Mean Squared Error (RMSE): 5.91
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 26.69
Fold 4 - Mean Absolute Error (MAE): 1.47
Fold 4 - Root Mean Squared Error (RMSE): 5.17
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 31.07
Fold 5 - Mean Absolute Error (MAE): 1.64
Fold 5 - Root Mean Squared Error (RMSE): 5.57
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 24.79
Mean - Mean Absolute Error (MAE): 1.48
Mean - Root Mean Squared Error (RMSE): 4.91
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 2.67
Fold 1 - Mean Absolute Error (MAE): 0.84
Fold 1 - Root Mean Squared Error (RMSE): 1.64
Fold 1 - Time taken: 2.49 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 4.12
Fold 2 - Mean Absolute Error (MAE): 0.89
Fold 2 - Root Mean Squared Error (RMSE): 2.03
Fold 2 - Time taken: 2.65 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 4.88
Fold 3 - Mean Absolute Error (MAE): 1.01
Fold 3 - Root Mean Squared Error (RMSE): 2.21
Fold 3 - Time taken: 3.97 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 6.55
Fold 4 - Mean Absolute Error (MAE): 1.05
Fold 4 - Root Mean Squared Error (RMSE): 2.56
Fold 4 - Time taken: 4.05 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 6.02
Fold 5 - Mean Absolute Error (MAE): 1.00
Fold 5 - Root Mean Squared Error (RMSE): 2.45
Fold 5 - Time taken: 4.10 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 4.85
Mean - Mean Absolute Error (MAE): 0.96
Mean - Root Mean Squared Error (RMSE): 2.18
Mean - Time taken: 3.45 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.15
Fold 1 - Mean Absolute Error (MAE): 0.23
Fold 1 - Root Mean Squared Error (RMSE): 0.38
Fold 1 - Time taken: 0.11 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.18
Fold 2 - Mean Absolute Error (MAE): 0.24
Fold 2 - Root Mean Squared Error (RMSE): 0.43
Fold 2 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.20
Fold 3 - Mean Absolute Error (MAE): 0.25
Fold 3 - Root Mean Squared Error (RMSE): 0.44
Fold 3 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.17
Fold 4 - Mean Absolute Error (MAE): 0.24
Fold 4 - Root Mean Squared Error (RMSE): 0.42
Fold 4 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.17
Fold 5 - Mean Absolute Error (MAE): 0.25
Fold 5 - Root Mean Squared Error (RMSE): 0.41
Fold 5 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.17
Mean - Mean Absolute Error (MAE): 0.24
Mean - Root Mean Squared Error (RMSE): 0.42
Mean - Time taken: 0.06 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 6.72
Fold 1 - Mean Absolute Error (MAE): 1.51
Fold 1 - Root Mean Squared Error (RMSE): 2.59
Fold 1 - Time taken: 4.99 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 8.75
Fold 2 - Mean Absolute Error (MAE): 1.53
Fold 2 - Root Mean Squared Error (RMSE): 2.96
Fold 2 - Time taken: 5.03 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 7.46
Fold 3 - Mean Absolute Error (MAE): 1.50
Fold 3 - Root Mean Squared Error (RMSE): 2.73
Fold 3 - Time taken: 5.29 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 7.97
Fold 4 - Mean Absolute Error (MAE): 1.47
Fold 4 - Root Mean Squared Error (RMSE): 2.82
Fold 4 - Time taken: 4.87 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 11.74
Fold 5 - Mean Absolute Error (MAE): 1.62
Fold 5 - Root Mean Squared Error (RMSE): 3.43
Fold 5 - Time taken: 3.50 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 8.53
Mean - Mean Absolute Error (MAE): 1.53
Mean - Root Mean Squared Error (RMSE): 2.91
Mean - Time taken: 4.74 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing1_Reg3.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing1_Reg3.xlsx file")

Results saved to Results__PL_model_2_smoothing1_Reg3.xlsx file