# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_Scattered_Reg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,84.790990,98.942547,66.852061,78.537710,72.380824,88.951092,90.918692,92.278454,95.010308,91.001789,...,89.761621,74.427330,100.513502,87.217017,80.749395,87.358951,85.650476,80.068792,70.987126,80.521285
1,78.340619,90.423198,87.642409,76.630040,88.921830,97.253265,79.304423,98.406720,97.725501,92.447989,...,79.890950,83.426100,71.982395,77.217953,94.068811,84.359733,80.933342,75.148912,82.359444,90.743983
2,95.585628,90.770939,87.347984,88.109083,89.558906,95.264726,79.142780,94.795926,80.983974,80.981781,...,85.152129,93.026783,100.161187,75.605136,84.857012,98.253237,79.653379,92.539654,102.217921,85.841926
3,79.574467,80.281353,83.429868,94.266988,103.766700,89.221949,88.361743,102.614685,99.713954,93.260670,...,85.325950,80.537477,94.396560,82.269627,82.429383,80.173917,75.793891,101.563571,86.944513,91.575176
4,89.736692,99.069960,78.459327,85.468961,93.727308,87.788715,85.554527,79.567194,86.725867,80.043688,...,68.876022,89.364210,82.782980,90.465916,83.111218,98.746243,89.322503,103.316556,66.082041,74.533889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,97.956169,95.527122,82.599286,81.825403,99.607106,79.993118,101.025214,95.664585,96.039527,89.015385,...,80.149358,102.984487,80.083995,88.586414,91.307511,95.327354,79.514761,75.111528,85.596108,87.116670
2439,83.530267,99.272592,88.012521,88.214706,93.137435,88.777329,80.989867,90.011529,86.195937,83.045404,...,80.998522,83.406136,80.599574,79.125240,86.045887,71.973222,81.306598,86.631450,70.973688,78.326997
2440,97.749384,88.461724,81.749940,83.120943,90.872430,90.740286,74.873689,82.490343,91.818896,98.934953,...,97.848848,83.749303,105.613048,67.985040,81.187445,91.825642,84.844603,77.509772,74.625785,88.986403
2441,91.721041,82.662321,78.148643,97.861113,91.111689,89.193802,92.662224,92.046467,90.960519,78.208066,...,94.036006,85.598085,87.757701,80.216331,98.069703,93.979685,103.198712,88.088120,75.949089,73.258968
2442,83.996569,82.181851,105.005366,89.794222,90.315036,96.690272,89.378480,96.499707,94.032005,91.797499,...,86.648738,81.697754,88.436257,84.215493,85.823238,82.540064,84.626611,91.986858,86.176124,71.070116

In [4]:
position_data = pd.read_excel('real_positions_Reg2_3.xlsx', header=None)

In [5]:
position_data

              0          1       2
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,84.790990,98.942547,66.852061,78.537710,72.380824,88.951092,90.918692,92.278454,95.010308,91.001789,...,89.761621,74.427330,100.513502,87.217017,80.749395,87.358951,85.650476,80.068792,70.987126,80.521285
1,78.340619,90.423198,87.642409,76.630040,88.921830,97.253265,79.304423,98.406720,97.725501,92.447989,...,79.890950,83.426100,71.982395,77.217953,94.068811,84.359733,80.933342,75.148912,82.359444,90.743983
2,95.585628,90.770939,87.347984,88.109083,89.558906,95.264726,79.142780,94.795926,80.983974,80.981781,...,85.152129,93.026783,100.161187,75.605136,84.857012,98.253237,79.653379,92.539654,102.217921,85.841926
3,79.574467,80.281353,83.429868,94.266988,103.766700,89.221949,88.361743,102.614685,99.713954,93.260670,...,85.325950,80.537477,94.396560,82.269627,82.429383,80.173917,75.793891,101.563571,86.944513,91.575176
4,89.736692,99.069960,78.459327,85.468961,93.727308,87.788715,85.554527,79.567194,86.725867,80.043688,...,68.876022,89.364210,82.782980,90.465916,83.111218,98.746243,89.322503,103.316556,66.082041,74.533889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,97.956169,95.527122,82.599286,81.825403,99.607106,79.993118,101.025214,95.664585,96.039527,89.015385,...,80.149358,102.984487,80.083995,88.586414,91.307511,95.327354,79.514761,75.111528,85.596108,87.116670
2439,83.530267,99.272592,88.012521,88.214706,93.137435,88.777329,80.989867,90.011529,86.195937,83.045404,...,80.998522,83.406136,80.599574,79.125240,86.045887,71.973222,81.306598,86.631450,70.973688,78.326997
2440,97.749384,88.461724,81.749940,83.120943,90.872430,90.740286,74.873689,82.490343,91.818896,98.934953,...,97.848848,83.749303,105.613048,67.985040,81.187445,91.825642,84.844603,77.509772,74.625785,88.986403
2441,91.721041,82.662321,78.148643,97.861113,91.111689,89.193802,92.662224,92.046467,90.960519,78.208066,...,94.036006,85.598085,87.757701,80.216331,98.069703,93.979685,103.198712,88.088120,75.949089,73.258968
2442,83.996569,82.181851,105.005366,89.794222,90.315036,96.690272,89.378480,96.499707,94.032005,91.797499,...,86.648738,81.697754,88.436257,84.215493,85.823238,82.540064,84.626611,91.986858,86.176124,71.070116

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y   Pos Z
0    -75.968791  60.239368 -105.00
1    -75.314716  60.181623 -104.93
2    -74.653109  60.131806 -104.86
3    -73.984037  60.089935 -104.79
4    -73.307567  60.056029 -104.72
...         ...        ...     ...
2438 -99.899763  81.788725   65.66
2439 -99.939531  81.389997   65.73
2440 -99.969304  80.990713   65.80
2441 -99.989081  80.591032   65.87
2442 -99.998859  80.191116   65.94

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 1187.12
Fold 1 - Mean Absolute Error (MAE): 26.11
Fold 1 - Root Mean Squared Error (RMSE): 34.45
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 1157.05
Fold 2 - Mean Absolute Error (MAE): 26.16
Fold 2 - Root Mean Squared Error (RMSE): 34.02
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 1099.01
Fold 3 - Mean Absolute Error (MAE): 24.94
Fold 3 - Root Mean Squared Error (RMSE): 33.15
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 1118.11
Fold 4 - Mean Absolute Error (MAE): 25.08
Fold 4 - Root Mean Squared Error (RMSE): 33.44
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 1180.31
Fold 5 - Mean Absolute Error (MAE): 26.03
Fold 5 - Root Mean Squared Error (RMSE): 34.36
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 1148.32
Mean - Mean Absolute Error (MAE): 25.66
Mean - Root Mean Squared Error (RMSE): 33.88
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 3583.72
Fold 1 - Mean Absolute Error (MAE): 42.94
Fold 1 - Root Mean Squared Error (RMSE): 59.86
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 3392.78
Fold 2 - Mean Absolute Error (MAE): 42.10
Fold 2 - Root Mean Squared Error (RMSE): 58.25
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 3459.99
Fold 3 - Mean Absolute Error (MAE): 41.79
Fold 3 - Root Mean Squared Error (RMSE): 58.82
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 3610.74
Fold 4 - Mean Absolute Error (MAE): 42.80
Fold 4 - Root Mean Squared Error (RMSE): 60.09
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 3387.19
Fold 5 - Mean Absolute Error (MAE): 41.58
Fold 5 - Root Mean Squared Error (RMSE): 58.20
Fold 5 - Time taken: 0.06 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 3486.88
Mean - Mean Absolute Error (MAE): 42.24
Mean - Root Mean Squared Error (RMSE): 59.04
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 1500.60
Fold 1 - Mean Absolute Error (MAE): 30.87
Fold 1 - Root Mean Squared Error (RMSE): 38.74
Fold 1 - Time taken: 2.88 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 1580.43
Fold 2 - Mean Absolute Error (MAE): 31.81
Fold 2 - Root Mean Squared Error (RMSE): 39.75
Fold 2 - Time taken: 3.41 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 1423.22
Fold 3 - Mean Absolute Error (MAE): 29.72
Fold 3 - Root Mean Squared Error (RMSE): 37.73
Fold 3 - Time taken: 4.69 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 1479.71
Fold 4 - Mean Absolute Error (MAE): 30.26
Fold 4 - Root Mean Squared Error (RMSE): 38.47
Fold 4 - Time taken: 4.81 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 1511.74
Fold 5 - Mean Absolute Error (MAE): 30.59
Fold 5 - Root Mean Squared Error (RMSE): 38.88
Fold 5 - Time taken: 4.74 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 1499.14
Mean - Mean Absolute Error (MAE): 30.65
Mean - Root Mean Squared Error (RMSE): 38.71
Mean - Time taken: 4.11 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 1512.24
Fold 1 - Mean Absolute Error (MAE): 29.91
Fold 1 - Root Mean Squared Error (RMSE): 38.89
Fold 1 - Time taken: 0.12 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 1531.55
Fold 2 - Mean Absolute Error (MAE): 29.53
Fold 2 - Root Mean Squared Error (RMSE): 39.14
Fold 2 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 1434.52
Fold 3 - Mean Absolute Error (MAE): 28.63
Fold 3 - Root Mean Squared Error (RMSE): 37.88
Fold 3 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 1525.17
Fold 4 - Mean Absolute Error (MAE): 29.53
Fold 4 - Root Mean Squared Error (RMSE): 39.05
Fold 4 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 1589.89
Fold 5 - Mean Absolute Error (MAE): 30.20
Fold 5 - Root Mean Squared Error (RMSE): 39.87
Fold 5 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 1518.68
Mean - Mean Absolute Error (MAE): 29.56
Mean - Root Mean Squared Error (RMSE): 38.96
Mean - Time taken: 0.07 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1499.81
Fold 1 - Mean Absolute Error (MAE): 29.09
Fold 1 - Root Mean Squared Error (RMSE): 38.73
Fold 1 - Time taken: 6.09 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 1579.59
Fold 2 - Mean Absolute Error (MAE): 30.04
Fold 2 - Root Mean Squared Error (RMSE): 39.74
Fold 2 - Time taken: 5.89 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1426.06
Fold 3 - Mean Absolute Error (MAE): 28.39
Fold 3 - Root Mean Squared Error (RMSE): 37.76
Fold 3 - Time taken: 4.12 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1518.19
Fold 4 - Mean Absolute Error (MAE): 28.81
Fold 4 - Root Mean Squared Error (RMSE): 38.96
Fold 4 - Time taken: 2.48 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1627.18
Fold 5 - Mean Absolute Error (MAE): 29.73
Fold 5 - Root Mean Squared Error (RMSE): 40.34
Fold 5 - Time taken: 2.01 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1530.17
Mean - Mean Absolute Error (MAE): 29.21
Mean - Root Mean Squared Error (RMSE): 39.11
Mean - Time taken: 4.12 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_Scattered_Reg3.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_Scattered_Reg3.xlsx file")

Results saved to Results__PL_model_2_Scattered_Reg3.xlsx file