# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing1_iReg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,68.165602,73.214525,54.929182,69.655864,71.403868,75.361652,65.210943,70.099918,64.281094,67.694688,...,60.252563,63.449992,63.813749,63.989190,69.030748,70.568751,66.133151,74.897365,51.720686,68.719496
1,68.320769,73.503020,55.108143,69.849646,71.284041,75.608396,65.163524,70.352373,64.361128,67.758981,...,60.710144,63.745899,64.099498,63.987072,68.672240,70.433020,66.060377,74.975562,51.523917,68.854377
2,68.264952,73.761429,55.468074,70.055615,70.985613,75.905123,65.398957,70.578626,64.030457,67.813435,...,60.732694,63.998184,63.855413,63.949856,68.861595,70.290949,66.296819,74.677690,51.575612,68.692020
3,68.362153,74.040411,55.887237,70.525134,70.682778,75.605431,65.836389,70.664216,63.803375,67.950125,...,60.559639,64.287954,63.756134,64.036254,68.426069,69.851734,66.250169,74.819140,51.493836,68.625242
4,68.033015,74.204715,56.095547,70.602525,70.478464,75.447531,65.956767,70.831873,63.606507,67.955323,...,60.609487,64.146717,63.755710,63.655477,68.403576,69.896899,66.161135,74.958032,51.610822,68.573682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,74.568059,72.293618,67.704718,53.468833,75.884867,76.857451,70.997719,69.497509,68.363975,63.138777,...,65.035954,67.324317,62.334454,54.718227,71.670996,70.765093,72.695217,72.621895,64.892693,57.751374
2439,74.508017,72.408536,67.160446,53.550493,75.510517,76.987400,70.623577,69.880277,68.369050,62.981114,...,65.133341,67.407684,62.354433,54.765825,71.764926,71.045431,72.709782,72.508221,64.492520,57.765599
2440,74.337699,72.037422,67.417756,53.762911,75.742519,76.769187,70.338529,69.929756,68.295190,63.218778,...,65.053770,67.275562,62.138605,55.006686,71.780226,71.203497,72.526414,72.693934,64.685362,57.448548
2441,74.170043,71.958709,67.589126,53.918517,75.820175,76.695817,70.132494,69.752393,68.412262,63.306653,...,65.354303,67.365558,62.109005,54.630687,71.807060,71.009592,72.666838,72.642795,64.657371,57.886483
2442,73.665377,71.905628,67.053401,53.813570,75.916665,77.026193,70.289944,69.887088,68.955342,63.421998,...,65.805226,67.400068,61.747480,54.597664,72.277687,70.895712,72.414682,72.594683,64.671397,57.699748

In [4]:
position_data = pd.read_excel('real_positions_iReg3.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,68.165602,73.214525,54.929182,69.655864,71.403868,75.361652,65.210943,70.099918,64.281094,67.694688,...,60.252563,63.449992,63.813749,63.989190,69.030748,70.568751,66.133151,74.897365,51.720686,68.719496
1,68.320769,73.503020,55.108143,69.849646,71.284041,75.608396,65.163524,70.352373,64.361128,67.758981,...,60.710144,63.745899,64.099498,63.987072,68.672240,70.433020,66.060377,74.975562,51.523917,68.854377
2,68.264952,73.761429,55.468074,70.055615,70.985613,75.905123,65.398957,70.578626,64.030457,67.813435,...,60.732694,63.998184,63.855413,63.949856,68.861595,70.290949,66.296819,74.677690,51.575612,68.692020
3,68.362153,74.040411,55.887237,70.525134,70.682778,75.605431,65.836389,70.664216,63.803375,67.950125,...,60.559639,64.287954,63.756134,64.036254,68.426069,69.851734,66.250169,74.819140,51.493836,68.625242
4,68.033015,74.204715,56.095547,70.602525,70.478464,75.447531,65.956767,70.831873,63.606507,67.955323,...,60.609487,64.146717,63.755710,63.655477,68.403576,69.896899,66.161135,74.958032,51.610822,68.573682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,74.568059,72.293618,67.704718,53.468833,75.884867,76.857451,70.997719,69.497509,68.363975,63.138777,...,65.035954,67.324317,62.334454,54.718227,71.670996,70.765093,72.695217,72.621895,64.892693,57.751374
2439,74.508017,72.408536,67.160446,53.550493,75.510517,76.987400,70.623577,69.880277,68.369050,62.981114,...,65.133341,67.407684,62.354433,54.765825,71.764926,71.045431,72.709782,72.508221,64.492520,57.765599
2440,74.337699,72.037422,67.417756,53.762911,75.742519,76.769187,70.338529,69.929756,68.295190,63.218778,...,65.053770,67.275562,62.138605,55.006686,71.780226,71.203497,72.526414,72.693934,64.685362,57.448548
2441,74.170043,71.958709,67.589126,53.918517,75.820175,76.695817,70.132494,69.752393,68.412262,63.306653,...,65.354303,67.365558,62.109005,54.630687,71.807060,71.009592,72.666838,72.642795,64.657371,57.886483
2442,73.665377,71.905628,67.053401,53.813570,75.916665,77.026193,70.289944,69.887088,68.955342,63.421998,...,65.805226,67.400068,61.747480,54.597664,72.277687,70.895712,72.414682,72.594683,64.671397,57.699748

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 1.44
Fold 1 - Mean Absolute Error (MAE): 0.95
Fold 1 - Root Mean Squared Error (RMSE): 1.20
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 1.19
Fold 2 - Mean Absolute Error (MAE): 0.88
Fold 2 - Root Mean Squared Error (RMSE): 1.09
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 1.36
Fold 3 - Mean Absolute Error (MAE): 0.91
Fold 3 - Root Mean Squared Error (RMSE): 1.17
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 1.47
Fold 4 - Mean Absolute Error (MAE): 0.96
Fold 4 - Root Mean Squared Error (RMSE): 1.21
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 1.41
Fold 5 - Mean Absolute Error (MAE): 0.93
Fold 5 - Root Mean Squared Error (RMSE): 1.19
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 1.37
Mean - Mean Absolute Error (MAE): 0.93
Mean - Root Mean Squared Error (RMSE): 1.17
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 4.50
Fold 1 - Mean Absolute Error (MAE): 0.71
Fold 1 - Root Mean Squared Error (RMSE): 2.12
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 1.49
Fold 2 - Mean Absolute Error (MAE): 0.57
Fold 2 - Root Mean Squared Error (RMSE): 1.22
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 4.23
Fold 3 - Mean Absolute Error (MAE): 0.64
Fold 3 - Root Mean Squared Error (RMSE): 2.06
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 4.76
Fold 4 - Mean Absolute Error (MAE): 0.73
Fold 4 - Root Mean Squared Error (RMSE): 2.18
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 7.03
Fold 5 - Mean Absolute Error (MAE): 0.83
Fold 5 - Root Mean Squared Error (RMSE): 2.65
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 4.40
Mean - Mean Absolute Error (MAE): 0.70
Mean - Root Mean Squared Error (RMSE): 2.05
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.47
Fold 1 - Mean Absolute Error (MAE): 0.29
Fold 1 - Root Mean Squared Error (RMSE): 0.69
Fold 1 - Time taken: 2.38 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.54
Fold 2 - Mean Absolute Error (MAE): 0.30
Fold 2 - Root Mean Squared Error (RMSE): 0.73
Fold 2 - Time taken: 2.56 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 1.17
Fold 3 - Mean Absolute Error (MAE): 0.34
Fold 3 - Root Mean Squared Error (RMSE): 1.08
Fold 3 - Time taken: 3.86 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.22
Fold 4 - Mean Absolute Error (MAE): 0.26
Fold 4 - Root Mean Squared Error (RMSE): 0.47
Fold 4 - Time taken: 3.89 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 1.22
Fold 5 - Mean Absolute Error (MAE): 0.34
Fold 5 - Root Mean Squared Error (RMSE): 1.10
Fold 5 - Time taken: 3.80 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.72
Mean - Mean Absolute Error (MAE): 0.31
Mean - Root Mean Squared Error (RMSE): 0.82
Mean - Time taken: 3.30 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.06
Fold 1 - Mean Absolute Error (MAE): 0.15
Fold 1 - Root Mean Squared Error (RMSE): 0.24
Fold 1 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.06
Fold 2 - Mean Absolute Error (MAE): 0.15
Fold 2 - Root Mean Squared Error (RMSE): 0.24
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.07
Fold 3 - Mean Absolute Error (MAE): 0.17
Fold 3 - Root Mean Squared Error (RMSE): 0.27
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.07
Fold 4 - Mean Absolute Error (MAE): 0.16
Fold 4 - Root Mean Squared Error (RMSE): 0.26
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.07
Fold 5 - Mean Absolute Error (MAE): 0.16
Fold 5 - Root Mean Squared Error (RMSE): 0.26
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.06
Mean - Mean Absolute Error (MAE): 0.16
Mean - Root Mean Squared Error (RMSE): 0.25
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.95
Fold 1 - Mean Absolute Error (MAE): 0.65
Fold 1 - Root Mean Squared Error (RMSE): 1.40
Fold 1 - Time taken: 1.97 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 1.58
Fold 2 - Mean Absolute Error (MAE): 0.63
Fold 2 - Root Mean Squared Error (RMSE): 1.26
Fold 2 - Time taken: 1.88 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.17
Fold 3 - Mean Absolute Error (MAE): 0.62
Fold 3 - Root Mean Squared Error (RMSE): 1.08
Fold 3 - Time taken: 1.85 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1.36
Fold 4 - Mean Absolute Error (MAE): 0.60
Fold 4 - Root Mean Squared Error (RMSE): 1.17
Fold 4 - Time taken: 1.99 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 2.86
Fold 5 - Mean Absolute Error (MAE): 0.67
Fold 5 - Root Mean Squared Error (RMSE): 1.69
Fold 5 - Time taken: 2.35 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1.79
Mean - Mean Absolute Error (MAE): 0.64
Mean - Root Mean Squared Error (RMSE): 1.32
Mean - Time taken: 2.01 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing1_iReg3.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing1_iReg3.xlsx file")

Results saved to Results__PL_model_2_smoothing1_iReg3.xlsx file