# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_Scattered_iReg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,77.406007,85.465645,46.676435,57.403574,66.385077,83.755009,60.222991,81.731340,54.146807,72.026821,...,58.654447,55.586006,59.621294,61.886111,90.600231,71.045191,58.392011,72.109779,54.770557,61.238352
1,64.351704,73.971619,49.717074,71.733702,72.604477,74.323361,71.642854,81.550451,54.828538,74.455141,...,56.141836,66.074063,59.301755,74.178376,73.527994,77.744891,69.881647,76.405338,47.770099,68.878286
2,64.878892,64.809892,69.192530,70.355513,68.884789,59.777149,65.629420,94.242576,57.244828,65.010419,...,63.968113,66.679467,52.122820,61.039546,62.873698,86.699905,63.250734,78.284037,55.390484,66.183183
3,63.316636,80.498511,64.441418,56.912369,66.358069,86.564540,76.867275,76.334062,67.969230,76.411697,...,57.043472,63.030395,59.615085,56.388748,64.602431,64.466087,72.581645,66.845638,58.829371,75.603256
4,69.911923,68.179991,67.936123,68.450759,70.633028,70.152683,68.569243,70.124111,51.508900,63.318079,...,59.409446,62.687461,51.773093,60.071736,72.803066,88.221204,64.157324,72.880851,49.007566,70.516981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,75.420924,72.983297,72.293340,70.574890,89.053725,84.569350,66.739765,72.234099,81.076902,80.482844,...,83.150568,65.953377,48.117080,49.682031,81.110885,58.450963,79.666812,77.889462,64.789617,52.903472
2439,72.586272,59.022907,72.990713,58.263311,80.833146,77.615216,67.822218,78.501928,68.473403,66.975001,...,67.039936,62.654153,53.132274,52.359962,60.410200,66.332568,61.709596,65.257602,75.843347,61.268631
2440,56.283441,73.072358,66.997185,62.548293,65.700286,61.067226,61.145387,75.482207,65.980870,59.776324,...,66.367211,71.064424,64.243497,46.093524,64.877998,79.549095,72.639319,74.272992,66.682511,64.059545
2441,77.908145,72.319050,76.136647,48.914493,67.858274,81.550251,74.442318,55.323266,60.177985,59.097731,...,71.733504,71.091485,67.318279,60.271055,80.732961,65.210486,67.417776,68.806994,66.393003,56.498697
2442,72.498225,64.546306,67.043324,53.831131,80.916082,69.252684,74.697408,71.993410,88.466893,74.215926,...,55.230278,68.590599,67.672809,57.354662,58.927945,71.631605,69.682465,78.281842,51.802674,62.521953

In [4]:
position_data = pd.read_excel('real_positions_iReg3.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,77.406007,85.465645,46.676435,57.403574,66.385077,83.755009,60.222991,81.731340,54.146807,72.026821,...,58.654447,55.586006,59.621294,61.886111,90.600231,71.045191,58.392011,72.109779,54.770557,61.238352
1,64.351704,73.971619,49.717074,71.733702,72.604477,74.323361,71.642854,81.550451,54.828538,74.455141,...,56.141836,66.074063,59.301755,74.178376,73.527994,77.744891,69.881647,76.405338,47.770099,68.878286
2,64.878892,64.809892,69.192530,70.355513,68.884789,59.777149,65.629420,94.242576,57.244828,65.010419,...,63.968113,66.679467,52.122820,61.039546,62.873698,86.699905,63.250734,78.284037,55.390484,66.183183
3,63.316636,80.498511,64.441418,56.912369,66.358069,86.564540,76.867275,76.334062,67.969230,76.411697,...,57.043472,63.030395,59.615085,56.388748,64.602431,64.466087,72.581645,66.845638,58.829371,75.603256
4,69.911923,68.179991,67.936123,68.450759,70.633028,70.152683,68.569243,70.124111,51.508900,63.318079,...,59.409446,62.687461,51.773093,60.071736,72.803066,88.221204,64.157324,72.880851,49.007566,70.516981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,75.420924,72.983297,72.293340,70.574890,89.053725,84.569350,66.739765,72.234099,81.076902,80.482844,...,83.150568,65.953377,48.117080,49.682031,81.110885,58.450963,79.666812,77.889462,64.789617,52.903472
2439,72.586272,59.022907,72.990713,58.263311,80.833146,77.615216,67.822218,78.501928,68.473403,66.975001,...,67.039936,62.654153,53.132274,52.359962,60.410200,66.332568,61.709596,65.257602,75.843347,61.268631
2440,56.283441,73.072358,66.997185,62.548293,65.700286,61.067226,61.145387,75.482207,65.980870,59.776324,...,66.367211,71.064424,64.243497,46.093524,64.877998,79.549095,72.639319,74.272992,66.682511,64.059545
2441,77.908145,72.319050,76.136647,48.914493,67.858274,81.550251,74.442318,55.323266,60.177985,59.097731,...,71.733504,71.091485,67.318279,60.271055,80.732961,65.210486,67.417776,68.806994,66.393003,56.498697
2442,72.498225,64.546306,67.043324,53.831131,80.916082,69.252684,74.697408,71.993410,88.466893,74.215926,...,55.230278,68.590599,67.672809,57.354662,58.927945,71.631605,69.682465,78.281842,51.802674,62.521953

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 132.08
Fold 1 - Mean Absolute Error (MAE): 9.27
Fold 1 - Root Mean Squared Error (RMSE): 11.49
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 125.33
Fold 2 - Mean Absolute Error (MAE): 8.86
Fold 2 - Root Mean Squared Error (RMSE): 11.19
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 132.76
Fold 3 - Mean Absolute Error (MAE): 9.20
Fold 3 - Root Mean Squared Error (RMSE): 11.52
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 139.48
Fold 4 - Mean Absolute Error (MAE): 9.40
Fold 4 - Root Mean Squared Error (RMSE): 11.81
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 139.79
Fold 5 - Mean Absolute Error (MAE): 9.38
Fold 5 - Root Mean Squared Error (RMSE): 11.82
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 133.89
Mean - Mean Absolute Error (MAE): 9.22
Mean - Root Mean Squared Error (RMSE): 11.57
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 526.57
Fold 1 - Mean Absolute Error (MAE): 16.10
Fold 1 - Root Mean Squared Error (RMSE): 22.95
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 484.85
Fold 2 - Mean Absolute Error (MAE): 15.42
Fold 2 - Root Mean Squared Error (RMSE): 22.02
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 522.41
Fold 3 - Mean Absolute Error (MAE): 16.73
Fold 3 - Root Mean Squared Error (RMSE): 22.86
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 551.53
Fold 4 - Mean Absolute Error (MAE): 16.89
Fold 4 - Root Mean Squared Error (RMSE): 23.48
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 508.95
Fold 5 - Mean Absolute Error (MAE): 16.75
Fold 5 - Root Mean Squared Error (RMSE): 22.56
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 518.86
Mean - Mean Absolute Error (MAE): 16.38
Mean - Root Mean Squared Error (RMSE): 22.77
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 189.68
Fold 1 - Mean Absolute Error (MAE): 11.25
Fold 1 - Root Mean Squared Error (RMSE): 13.77
Fold 1 - Time taken: 2.83 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 194.04
Fold 2 - Mean Absolute Error (MAE): 11.33
Fold 2 - Root Mean Squared Error (RMSE): 13.93
Fold 2 - Time taken: 3.44 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 195.84
Fold 3 - Mean Absolute Error (MAE): 11.43
Fold 3 - Root Mean Squared Error (RMSE): 13.99
Fold 3 - Time taken: 4.23 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 205.27
Fold 4 - Mean Absolute Error (MAE): 11.45
Fold 4 - Root Mean Squared Error (RMSE): 14.33
Fold 4 - Time taken: 4.24 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 190.76
Fold 5 - Mean Absolute Error (MAE): 11.15
Fold 5 - Root Mean Squared Error (RMSE): 13.81
Fold 5 - Time taken: 4.30 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 195.12
Mean - Mean Absolute Error (MAE): 11.32
Mean - Root Mean Squared Error (RMSE): 13.97
Mean - Time taken: 3.81 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 154.47
Fold 1 - Mean Absolute Error (MAE): 9.83
Fold 1 - Root Mean Squared Error (RMSE): 12.43
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 149.37
Fold 2 - Mean Absolute Error (MAE): 9.73
Fold 2 - Root Mean Squared Error (RMSE): 12.22
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 149.95
Fold 3 - Mean Absolute Error (MAE): 9.82
Fold 3 - Root Mean Squared Error (RMSE): 12.25
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 153.94
Fold 4 - Mean Absolute Error (MAE): 9.75
Fold 4 - Root Mean Squared Error (RMSE): 12.41
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 162.28
Fold 5 - Mean Absolute Error (MAE): 10.03
Fold 5 - Root Mean Squared Error (RMSE): 12.74
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 154.00
Mean - Mean Absolute Error (MAE): 9.83
Mean - Root Mean Squared Error (RMSE): 12.41
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 177.10
Fold 1 - Mean Absolute Error (MAE): 10.33
Fold 1 - Root Mean Squared Error (RMSE): 13.31
Fold 1 - Time taken: 2.02 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 171.37
Fold 2 - Mean Absolute Error (MAE): 10.12
Fold 2 - Root Mean Squared Error (RMSE): 13.09
Fold 2 - Time taken: 2.46 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 185.05
Fold 3 - Mean Absolute Error (MAE): 10.50
Fold 3 - Root Mean Squared Error (RMSE): 13.60
Fold 3 - Time taken: 2.56 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 187.42
Fold 4 - Mean Absolute Error (MAE): 10.59
Fold 4 - Root Mean Squared Error (RMSE): 13.69
Fold 4 - Time taken: 2.60 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 173.58
Fold 5 - Mean Absolute Error (MAE): 10.25
Fold 5 - Root Mean Squared Error (RMSE): 13.17
Fold 5 - Time taken: 2.56 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 178.90
Mean - Mean Absolute Error (MAE): 10.36
Mean - Root Mean Squared Error (RMSE): 13.37
Mean - Time taken: 2.44 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_Scattered_iReg3.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_Scattered_iReg3.xlsx file")

Results saved to Results__PL_model_2_Scattered_iReg3.xlsx file