# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_Scattered_iReg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,102.231018,135.990048,73.812850,116.565753,111.202044,150.683231,96.365961,140.487517,98.601409,122.434043,...,102.968721,99.793607,113.612186,93.814743,133.796040,115.481976,97.418861,128.707790,79.548665,105.116029
1,97.982824,132.698591,66.708073,119.324478,110.545978,159.182450,92.510440,137.776596,98.957108,120.181743,...,100.362621,96.042977,118.225569,90.051274,130.252433,114.887874,103.697799,131.616582,81.541012,118.379456
2,98.647256,132.894051,79.772103,119.193717,108.931531,144.295225,93.257609,138.369694,98.916524,117.487378,...,102.203220,97.648605,108.903664,84.676865,135.995802,115.277959,105.767493,128.916635,81.201988,127.015099
3,102.408847,137.897951,78.600724,119.805461,104.463347,146.472303,97.567124,143.816454,95.281408,114.334039,...,104.193701,99.854129,105.911154,86.590783,129.870221,116.885735,103.633455,135.289599,72.602587,127.191117
4,89.050598,132.602282,76.344348,121.248362,101.927318,147.948277,94.943440,132.829582,104.079073,119.046085,...,102.461276,111.986689,102.766401,85.652488,130.456267,114.177089,99.070753,129.041043,78.945627,125.678009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.927621,116.976126,108.365874,74.711485,136.466529,142.015998,119.494517,114.619207,116.602944,102.356248,...,102.905878,121.904301,102.722820,69.725346,131.398464,110.109527,122.433555,116.866119,100.253042,79.928472
2439,132.437227,116.526200,100.958719,78.286498,138.294416,138.545624,118.406671,116.120037,113.637022,109.682090,...,103.234230,116.043139,113.696643,72.265190,133.957243,110.322801,133.911830,122.512862,111.478191,85.075418
2440,131.646685,109.815138,111.500715,74.918044,134.603560,135.197152,127.698452,116.174766,113.793795,98.275470,...,108.710860,111.851328,114.362172,73.286779,129.137231,104.560735,135.577954,114.757617,104.005333,78.418613
2441,127.597644,111.700621,100.211530,73.055509,139.530111,137.331946,126.245267,116.647265,115.424463,113.904445,...,115.436590,120.701386,114.366826,67.237726,137.155432,112.342257,133.556849,106.291608,109.976440,86.684908
2442,131.163422,113.692855,96.896797,77.429026,142.659636,135.393288,128.696714,115.135426,120.884023,111.474914,...,95.556483,120.765600,114.385512,61.679567,128.229454,111.577177,133.320107,116.000496,107.965357,83.794705

In [4]:
position_data = pd.read_excel('real_positions_iReg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,102.231018,135.990048,73.812850,116.565753,111.202044,150.683231,96.365961,140.487517,98.601409,122.434043,...,102.968721,99.793607,113.612186,93.814743,133.796040,115.481976,97.418861,128.707790,79.548665,105.116029
1,97.982824,132.698591,66.708073,119.324478,110.545978,159.182450,92.510440,137.776596,98.957108,120.181743,...,100.362621,96.042977,118.225569,90.051274,130.252433,114.887874,103.697799,131.616582,81.541012,118.379456
2,98.647256,132.894051,79.772103,119.193717,108.931531,144.295225,93.257609,138.369694,98.916524,117.487378,...,102.203220,97.648605,108.903664,84.676865,135.995802,115.277959,105.767493,128.916635,81.201988,127.015099
3,102.408847,137.897951,78.600724,119.805461,104.463347,146.472303,97.567124,143.816454,95.281408,114.334039,...,104.193701,99.854129,105.911154,86.590783,129.870221,116.885735,103.633455,135.289599,72.602587,127.191117
4,89.050598,132.602282,76.344348,121.248362,101.927318,147.948277,94.943440,132.829582,104.079073,119.046085,...,102.461276,111.986689,102.766401,85.652488,130.456267,114.177089,99.070753,129.041043,78.945627,125.678009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.927621,116.976126,108.365874,74.711485,136.466529,142.015998,119.494517,114.619207,116.602944,102.356248,...,102.905878,121.904301,102.722820,69.725346,131.398464,110.109527,122.433555,116.866119,100.253042,79.928472
2439,132.437227,116.526200,100.958719,78.286498,138.294416,138.545624,118.406671,116.120037,113.637022,109.682090,...,103.234230,116.043139,113.696643,72.265190,133.957243,110.322801,133.911830,122.512862,111.478191,85.075418
2440,131.646685,109.815138,111.500715,74.918044,134.603560,135.197152,127.698452,116.174766,113.793795,98.275470,...,108.710860,111.851328,114.362172,73.286779,129.137231,104.560735,135.577954,114.757617,104.005333,78.418613
2441,127.597644,111.700621,100.211530,73.055509,139.530111,137.331946,126.245267,116.647265,115.424463,113.904445,...,115.436590,120.701386,114.366826,67.237726,137.155432,112.342257,133.556849,106.291608,109.976440,86.684908
2442,131.163422,113.692855,96.896797,77.429026,142.659636,135.393288,128.696714,115.135426,120.884023,111.474914,...,95.556483,120.765600,114.385512,61.679567,128.229454,111.577177,133.320107,116.000496,107.965357,83.794705

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 10.58
Fold 1 - Mean Absolute Error (MAE): 2.54
Fold 1 - Root Mean Squared Error (RMSE): 3.25
Fold 1 - Time taken: 0.02 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 10.21
Fold 2 - Mean Absolute Error (MAE): 2.50
Fold 2 - Root Mean Squared Error (RMSE): 3.20
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 10.35
Fold 3 - Mean Absolute Error (MAE): 2.51
Fold 3 - Root Mean Squared Error (RMSE): 3.22
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 10.81
Fold 4 - Mean Absolute Error (MAE): 2.54
Fold 4 - Root Mean Squared Error (RMSE): 3.29
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 10.17
Fold 5 - Mean Absolute Error (MAE): 2.47
Fold 5 - Root Mean Squared Error (RMSE): 3.19
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 10.42
Mean - Mean Absolute Error (MAE): 2.51
Mean - Root Mean Squared Error (RMSE): 3.23
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 91.09
Fold 1 - Mean Absolute Error (MAE): 5.96
Fold 1 - Root Mean Squared Error (RMSE): 9.54
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 88.26
Fold 2 - Mean Absolute Error (MAE): 5.86
Fold 2 - Root Mean Squared Error (RMSE): 9.39
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 101.64
Fold 3 - Mean Absolute Error (MAE): 6.36
Fold 3 - Root Mean Squared Error (RMSE): 10.08
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 96.34
Fold 4 - Mean Absolute Error (MAE): 6.16
Fold 4 - Root Mean Squared Error (RMSE): 9.82
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 93.22
Fold 5 - Mean Absolute Error (MAE): 5.89
Fold 5 - Root Mean Squared Error (RMSE): 9.65
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 94.11
Mean - Mean Absolute Error (MAE): 6.05
Mean - Root Mean Squared Error (RMSE): 9.70
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 19.33
Fold 1 - Mean Absolute Error (MAE): 3.47
Fold 1 - Root Mean Squared Error (RMSE): 4.40
Fold 1 - Time taken: 2.46 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 19.75
Fold 2 - Mean Absolute Error (MAE): 3.46
Fold 2 - Root Mean Squared Error (RMSE): 4.44
Fold 2 - Time taken: 2.84 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 22.67
Fold 3 - Mean Absolute Error (MAE): 3.67
Fold 3 - Root Mean Squared Error (RMSE): 4.76
Fold 3 - Time taken: 3.92 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 18.39
Fold 4 - Mean Absolute Error (MAE): 3.34
Fold 4 - Root Mean Squared Error (RMSE): 4.29
Fold 4 - Time taken: 3.81 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 18.42
Fold 5 - Mean Absolute Error (MAE): 3.37
Fold 5 - Root Mean Squared Error (RMSE): 4.29
Fold 5 - Time taken: 3.87 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 19.71
Mean - Mean Absolute Error (MAE): 3.46
Mean - Root Mean Squared Error (RMSE): 4.44
Mean - Time taken: 3.38 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 5.48
Fold 1 - Mean Absolute Error (MAE): 1.50
Fold 1 - Root Mean Squared Error (RMSE): 2.34
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 5.56
Fold 2 - Mean Absolute Error (MAE): 1.54
Fold 2 - Root Mean Squared Error (RMSE): 2.36
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 5.69
Fold 3 - Mean Absolute Error (MAE): 1.54
Fold 3 - Root Mean Squared Error (RMSE): 2.38
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 5.67
Fold 4 - Mean Absolute Error (MAE): 1.55
Fold 4 - Root Mean Squared Error (RMSE): 2.38
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 5.83
Fold 5 - Mean Absolute Error (MAE): 1.55
Fold 5 - Root Mean Squared Error (RMSE): 2.41
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 5.65
Mean - Mean Absolute Error (MAE): 1.53
Mean - Root Mean Squared Error (RMSE): 2.38
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 21.32
Fold 1 - Mean Absolute Error (MAE): 3.33
Fold 1 - Root Mean Squared Error (RMSE): 4.62
Fold 1 - Time taken: 1.99 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 24.04
Fold 2 - Mean Absolute Error (MAE): 3.54
Fold 2 - Root Mean Squared Error (RMSE): 4.90
Fold 2 - Time taken: 1.96 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 21.97
Fold 3 - Mean Absolute Error (MAE): 3.43
Fold 3 - Root Mean Squared Error (RMSE): 4.69
Fold 3 - Time taken: 1.96 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 21.79
Fold 4 - Mean Absolute Error (MAE): 3.40
Fold 4 - Root Mean Squared Error (RMSE): 4.67
Fold 4 - Time taken: 1.97 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 20.45
Fold 5 - Mean Absolute Error (MAE): 3.30
Fold 5 - Root Mean Squared Error (RMSE): 4.52
Fold 5 - Time taken: 1.97 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 21.92
Mean - Mean Absolute Error (MAE): 3.40
Mean - Root Mean Squared Error (RMSE): 4.68
Mean - Time taken: 1.97 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_1_Scattered_iReg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_1_Scattered_iReg1.xlsx file")

Results saved to Results__PL_model_1_Scattered_iReg1.xlsx file