# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_smoothing2_iReg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,98.393321,131.482648,75.867605,118.027106,109.179756,148.109739,93.594916,138.074036,96.714982,116.097312,...,102.288600,102.024633,109.631943,87.336817,130.308117,116.718101,101.385338,132.561883,79.467877,122.257211
1,98.444564,131.517999,75.857379,118.140478,109.199307,148.052101,93.426541,137.910340,96.717521,116.145272,...,102.303438,101.959564,109.567715,87.357837,129.987257,116.473173,101.354453,132.432691,79.463168,121.951350
2,98.496392,131.556557,75.846459,118.255607,109.217329,147.996507,93.259770,137.746950,96.723765,116.197105,...,102.319948,101.889840,109.504850,87.381066,129.669041,116.225754,101.325368,132.302835,79.456790,121.648947
3,98.548600,131.598188,75.835125,118.372584,109.233507,147.942720,93.094556,137.583737,96.733722,116.252596,...,102.338334,101.815645,109.442957,87.406197,129.353349,115.975813,101.298271,132.172689,79.448508,121.350429
4,98.600937,131.642641,75.823564,118.491430,109.247546,147.890592,92.930820,137.420504,96.747305,116.311454,...,102.358817,101.737400,109.381630,87.432975,129.039860,115.723360,101.273173,132.042762,79.438047,121.056043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.170629,112.709413,102.666220,77.832714,138.953882,137.326696,120.699020,115.960773,115.254573,107.317476,...,109.068883,120.931835,111.945486,69.955247,135.620435,112.091033,131.888219,115.087875,109.236992,81.424445
2439,130.065330,112.559432,102.687482,77.821625,138.782748,137.200898,120.887947,115.983107,115.145227,107.101800,...,109.008274,120.877149,111.878484,69.948866,135.520239,112.090699,131.766365,114.996477,109.324806,81.497899
2440,129.959821,112.412567,102.708866,77.808584,138.611096,137.077377,121.080106,116.005755,115.036637,106.886227,...,108.946650,120.821609,111.812302,69.941445,135.415894,112.087179,131.645762,114.906495,109.410510,81.575038
2441,129.854167,112.268582,102.730146,77.793310,138.439092,136.955880,121.276125,116.028738,114.929015,106.671157,...,108.884007,120.764911,111.747357,69.932744,135.307149,112.080416,131.526782,114.817679,109.493979,81.655921
2442,129.748379,112.127315,102.750962,77.775670,138.267024,136.836204,121.476392,116.052059,114.822610,106.457087,...,108.820363,120.706983,111.683916,69.922432,135.193956,112.070547,131.409610,114.729800,109.575239,81.740630

In [4]:
position_data = pd.read_excel('real_positions_iReg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,98.393321,131.482648,75.867605,118.027106,109.179756,148.109739,93.594916,138.074036,96.714982,116.097312,...,102.288600,102.024633,109.631943,87.336817,130.308117,116.718101,101.385338,132.561883,79.467877,122.257211
1,98.444564,131.517999,75.857379,118.140478,109.199307,148.052101,93.426541,137.910340,96.717521,116.145272,...,102.303438,101.959564,109.567715,87.357837,129.987257,116.473173,101.354453,132.432691,79.463168,121.951350
2,98.496392,131.556557,75.846459,118.255607,109.217329,147.996507,93.259770,137.746950,96.723765,116.197105,...,102.319948,101.889840,109.504850,87.381066,129.669041,116.225754,101.325368,132.302835,79.456790,121.648947
3,98.548600,131.598188,75.835125,118.372584,109.233507,147.942720,93.094556,137.583737,96.733722,116.252596,...,102.338334,101.815645,109.442957,87.406197,129.353349,115.975813,101.298271,132.172689,79.448508,121.350429
4,98.600937,131.642641,75.823564,118.491430,109.247546,147.890592,92.930820,137.420504,96.747305,116.311454,...,102.358817,101.737400,109.381630,87.432975,129.039860,115.723360,101.273173,132.042762,79.438047,121.056043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.170629,112.709413,102.666220,77.832714,138.953882,137.326696,120.699020,115.960773,115.254573,107.317476,...,109.068883,120.931835,111.945486,69.955247,135.620435,112.091033,131.888219,115.087875,109.236992,81.424445
2439,130.065330,112.559432,102.687482,77.821625,138.782748,137.200898,120.887947,115.983107,115.145227,107.101800,...,109.008274,120.877149,111.878484,69.948866,135.520239,112.090699,131.766365,114.996477,109.324806,81.497899
2440,129.959821,112.412567,102.708866,77.808584,138.611096,137.077377,121.080106,116.005755,115.036637,106.886227,...,108.946650,120.821609,111.812302,69.941445,135.415894,112.087179,131.645762,114.906495,109.410510,81.575038
2441,129.854167,112.268582,102.730146,77.793310,138.439092,136.955880,121.276125,116.028738,114.929015,106.671157,...,108.884007,120.764911,111.747357,69.932744,135.307149,112.080416,131.526782,114.817679,109.493979,81.655921
2442,129.748379,112.127315,102.750962,77.775670,138.267024,136.836204,121.476392,116.052059,114.822610,106.457087,...,108.820363,120.706983,111.683916,69.922432,135.193956,112.070547,131.409610,114.729800,109.575239,81.740630

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.29
Fold 1 - Mean Absolute Error (MAE): 0.41
Fold 1 - Root Mean Squared Error (RMSE): 0.54
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.29
Fold 2 - Mean Absolute Error (MAE): 0.41
Fold 2 - Root Mean Squared Error (RMSE): 0.54
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.29
Fold 3 - Mean Absolute Error (MAE): 0.41
Fold 3 - Root Mean Squared Error (RMSE): 0.54
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.30
Fold 4 - Mean Absolute Error (MAE): 0.41
Fold 4 - Root Mean Squared Error (RMSE): 0.55
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.26
Fold 5 - Mean Absolute Error (MAE): 0.40
Fold 5 - Root Mean Squared Error (RMSE): 0.51
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.29
Mean - Mean Absolute Error (MAE): 0.41
Mean - Root Mean Squared Error (RMSE): 0.54
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 0.91
Fold 1 - Mean Absolute Error (MAE): 0.32
Fold 1 - Root Mean Squared Error (RMSE): 0.96
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 1.32
Fold 2 - Mean Absolute Error (MAE): 0.36
Fold 2 - Root Mean Squared Error (RMSE): 1.15
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 1.75
Fold 3 - Mean Absolute Error (MAE): 0.36
Fold 3 - Root Mean Squared Error (RMSE): 1.32
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 0.16
Fold 4 - Mean Absolute Error (MAE): 0.26
Fold 4 - Root Mean Squared Error (RMSE): 0.41
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 0.27
Fold 5 - Mean Absolute Error (MAE): 0.28
Fold 5 - Root Mean Squared Error (RMSE): 0.52
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 0.88
Mean - Mean Absolute Error (MAE): 0.32
Mean - Root Mean Squared Error (RMSE): 0.87
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.11
Fold 1 - Mean Absolute Error (MAE): 0.15
Fold 1 - Root Mean Squared Error (RMSE): 0.34
Fold 1 - Time taken: 2.05 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.06
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.25
Fold 2 - Time taken: 2.05 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.08
Fold 3 - Mean Absolute Error (MAE): 0.15
Fold 3 - Root Mean Squared Error (RMSE): 0.28
Fold 3 - Time taken: 2.74 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.06
Fold 4 - Mean Absolute Error (MAE): 0.14
Fold 4 - Root Mean Squared Error (RMSE): 0.25
Fold 4 - Time taken: 3.26 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.06
Fold 5 - Mean Absolute Error (MAE): 0.13
Fold 5 - Root Mean Squared Error (RMSE): 0.24
Fold 5 - Time taken: 3.16 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.08
Mean - Mean Absolute Error (MAE): 0.14
Mean - Root Mean Squared Error (RMSE): 0.27
Mean - Time taken: 2.65 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.04
Fold 1 - Mean Absolute Error (MAE): 0.13
Fold 1 - Root Mean Squared Error (RMSE): 0.20
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.05
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.22
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.04
Fold 3 - Mean Absolute Error (MAE): 0.13
Fold 3 - Root Mean Squared Error (RMSE): 0.21
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.05
Fold 4 - Mean Absolute Error (MAE): 0.14
Fold 4 - Root Mean Squared Error (RMSE): 0.23
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.05
Fold 5 - Mean Absolute Error (MAE): 0.14
Fold 5 - Root Mean Squared Error (RMSE): 0.23
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.05
Mean - Mean Absolute Error (MAE): 0.14
Mean - Root Mean Squared Error (RMSE): 0.22
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.44
Fold 1 - Mean Absolute Error (MAE): 0.33
Fold 1 - Root Mean Squared Error (RMSE): 0.67
Fold 1 - Time taken: 1.78 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.39
Fold 2 - Mean Absolute Error (MAE): 0.34
Fold 2 - Root Mean Squared Error (RMSE): 0.62
Fold 2 - Time taken: 1.78 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 0.32
Fold 3 - Mean Absolute Error (MAE): 0.33
Fold 3 - Root Mean Squared Error (RMSE): 0.57
Fold 3 - Time taken: 1.87 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.29
Fold 4 - Mean Absolute Error (MAE): 0.34
Fold 4 - Root Mean Squared Error (RMSE): 0.54
Fold 4 - Time taken: 1.76 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 0.50
Fold 5 - Mean Absolute Error (MAE): 0.36
Fold 5 - Root Mean Squared Error (RMSE): 0.71
Fold 5 - Time taken: 1.81 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 0.39
Mean - Mean Absolute Error (MAE): 0.34
Mean - Root Mean Squared Error (RMSE): 0.62
Mean - Time taken: 1.80 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_1_smoothing2_iReg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_1_smoothing2_iReg1.xlsx file")

Results saved to Results__PL_model_1_smoothing2_iReg1.xlsx file