# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_smoothing1_iReg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,97.433731,131.489141,75.550244,120.730464,108.870006,148.417016,92.553757,137.076620,96.175487,115.668058,...,103.020567,101.579258,108.559300,87.519581,128.823213,114.831255,100.844699,132.488587,78.336632,119.627746
1,97.240187,131.473700,75.401350,120.209685,109.800831,148.524856,92.072317,137.348126,96.963848,116.134125,...,102.588974,101.408675,108.774191,87.387659,129.193481,114.831617,100.570094,132.924453,78.533185,119.986827
2,98.003290,131.742747,75.088813,119.922244,109.306371,148.188835,92.496386,137.485409,96.022120,116.352910,...,102.469130,101.532517,109.020098,87.060041,128.786894,114.973636,100.812596,133.397115,78.730380,119.532227
3,98.046935,131.290847,75.225717,119.946229,109.521729,147.971045,91.757153,137.435285,96.387406,116.516383,...,102.026515,101.986223,109.205699,87.187182,128.284088,114.754104,100.932400,133.059043,78.902066,119.064118
4,98.133301,131.506904,75.901920,119.708272,109.123839,147.929294,91.944349,136.859435,95.959483,116.681787,...,102.245508,101.988916,109.080188,87.179725,127.974152,115.194385,101.882940,132.545034,78.998331,118.523430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.479575,112.965298,102.578391,78.183365,140.172230,137.744388,120.320110,115.778987,115.893869,107.733290,...,109.485098,121.453508,111.851747,69.508815,136.445569,111.779774,131.969866,115.021237,109.431460,80.861654
2439,130.432334,112.852207,102.829772,77.972121,140.039397,138.189379,119.903600,115.459726,116.167147,107.300380,...,108.857818,121.208155,111.756187,69.483069,136.438401,112.083692,132.046924,115.046757,109.188723,80.834567
2440,130.503367,112.979964,102.795605,77.862794,139.296908,138.830793,120.358156,115.730020,115.341689,107.321547,...,108.746336,121.062785,111.023348,69.603886,136.423147,112.355650,132.029084,115.133055,108.742299,81.232196
2441,130.513498,113.061232,103.181578,77.967009,139.536932,139.166945,120.498013,116.256154,115.701838,107.157517,...,108.463752,120.919259,111.159839,69.398211,136.262915,112.158057,132.484487,115.087609,108.718408,81.188386
2442,129.859837,113.287115,103.130120,78.118402,139.123625,139.119508,120.731207,115.909930,115.662331,106.933251,...,108.482156,121.083322,110.975371,68.776262,136.760843,112.103685,132.293125,115.483845,108.504795,81.765553

In [4]:
position_data = pd.read_excel('real_positions_iReg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,97.433731,131.489141,75.550244,120.730464,108.870006,148.417016,92.553757,137.076620,96.175487,115.668058,...,103.020567,101.579258,108.559300,87.519581,128.823213,114.831255,100.844699,132.488587,78.336632,119.627746
1,97.240187,131.473700,75.401350,120.209685,109.800831,148.524856,92.072317,137.348126,96.963848,116.134125,...,102.588974,101.408675,108.774191,87.387659,129.193481,114.831617,100.570094,132.924453,78.533185,119.986827
2,98.003290,131.742747,75.088813,119.922244,109.306371,148.188835,92.496386,137.485409,96.022120,116.352910,...,102.469130,101.532517,109.020098,87.060041,128.786894,114.973636,100.812596,133.397115,78.730380,119.532227
3,98.046935,131.290847,75.225717,119.946229,109.521729,147.971045,91.757153,137.435285,96.387406,116.516383,...,102.026515,101.986223,109.205699,87.187182,128.284088,114.754104,100.932400,133.059043,78.902066,119.064118
4,98.133301,131.506904,75.901920,119.708272,109.123839,147.929294,91.944349,136.859435,95.959483,116.681787,...,102.245508,101.988916,109.080188,87.179725,127.974152,115.194385,101.882940,132.545034,78.998331,118.523430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.479575,112.965298,102.578391,78.183365,140.172230,137.744388,120.320110,115.778987,115.893869,107.733290,...,109.485098,121.453508,111.851747,69.508815,136.445569,111.779774,131.969866,115.021237,109.431460,80.861654
2439,130.432334,112.852207,102.829772,77.972121,140.039397,138.189379,119.903600,115.459726,116.167147,107.300380,...,108.857818,121.208155,111.756187,69.483069,136.438401,112.083692,132.046924,115.046757,109.188723,80.834567
2440,130.503367,112.979964,102.795605,77.862794,139.296908,138.830793,120.358156,115.730020,115.341689,107.321547,...,108.746336,121.062785,111.023348,69.603886,136.423147,112.355650,132.029084,115.133055,108.742299,81.232196
2441,130.513498,113.061232,103.181578,77.967009,139.536932,139.166945,120.498013,116.256154,115.701838,107.157517,...,108.463752,120.919259,111.159839,69.398211,136.262915,112.158057,132.484487,115.087609,108.718408,81.188386
2442,129.859837,113.287115,103.130120,78.118402,139.123625,139.119508,120.731207,115.909930,115.662331,106.933251,...,108.482156,121.083322,110.975371,68.776262,136.760843,112.103685,132.293125,115.483845,108.504795,81.765553

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.49
Fold 1 - Mean Absolute Error (MAE): 0.53
Fold 1 - Root Mean Squared Error (RMSE): 0.70
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.49
Fold 2 - Mean Absolute Error (MAE): 0.53
Fold 2 - Root Mean Squared Error (RMSE): 0.70
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.50
Fold 3 - Mean Absolute Error (MAE): 0.54
Fold 3 - Root Mean Squared Error (RMSE): 0.71
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.50
Fold 4 - Mean Absolute Error (MAE): 0.54
Fold 4 - Root Mean Squared Error (RMSE): 0.71
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.45
Fold 5 - Mean Absolute Error (MAE): 0.52
Fold 5 - Root Mean Squared Error (RMSE): 0.67
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.49
Mean - Mean Absolute Error (MAE): 0.53
Mean - Root Mean Squared Error (RMSE): 0.70
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 0.63
Fold 1 - Mean Absolute Error (MAE): 0.45
Fold 1 - Root Mean Squared Error (RMSE): 0.79
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 2.65
Fold 2 - Mean Absolute Error (MAE): 0.56
Fold 2 - Root Mean Squared Error (RMSE): 1.63
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 2.59
Fold 3 - Mean Absolute Error (MAE): 0.56
Fold 3 - Root Mean Squared Error (RMSE): 1.61
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 1.16
Fold 4 - Mean Absolute Error (MAE): 0.50
Fold 4 - Root Mean Squared Error (RMSE): 1.08
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 0.77
Fold 5 - Mean Absolute Error (MAE): 0.50
Fold 5 - Root Mean Squared Error (RMSE): 0.87
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 1.56
Mean - Mean Absolute Error (MAE): 0.51
Mean - Root Mean Squared Error (RMSE): 1.20
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.13
Fold 1 - Mean Absolute Error (MAE): 0.19
Fold 1 - Root Mean Squared Error (RMSE): 0.36
Fold 1 - Time taken: 2.20 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.11
Fold 2 - Mean Absolute Error (MAE): 0.19
Fold 2 - Root Mean Squared Error (RMSE): 0.33
Fold 2 - Time taken: 2.22 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.12
Fold 3 - Mean Absolute Error (MAE): 0.20
Fold 3 - Root Mean Squared Error (RMSE): 0.34
Fold 3 - Time taken: 3.10 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.10
Fold 4 - Mean Absolute Error (MAE): 0.19
Fold 4 - Root Mean Squared Error (RMSE): 0.32
Fold 4 - Time taken: 3.38 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.09
Fold 5 - Mean Absolute Error (MAE): 0.18
Fold 5 - Root Mean Squared Error (RMSE): 0.31
Fold 5 - Time taken: 3.41 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.11
Mean - Mean Absolute Error (MAE): 0.19
Mean - Root Mean Squared Error (RMSE): 0.33
Mean - Time taken: 2.86 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.05
Fold 1 - Mean Absolute Error (MAE): 0.14
Fold 1 - Root Mean Squared Error (RMSE): 0.22
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.06
Fold 2 - Mean Absolute Error (MAE): 0.15
Fold 2 - Root Mean Squared Error (RMSE): 0.24
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.06
Fold 3 - Mean Absolute Error (MAE): 0.16
Fold 3 - Root Mean Squared Error (RMSE): 0.25
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.06
Fold 4 - Mean Absolute Error (MAE): 0.16
Fold 4 - Root Mean Squared Error (RMSE): 0.25
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.06
Fold 5 - Mean Absolute Error (MAE): 0.16
Fold 5 - Root Mean Squared Error (RMSE): 0.25
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.06
Mean - Mean Absolute Error (MAE): 0.15
Mean - Root Mean Squared Error (RMSE): 0.24
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.73
Fold 1 - Mean Absolute Error (MAE): 0.49
Fold 1 - Root Mean Squared Error (RMSE): 0.85
Fold 1 - Time taken: 1.83 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.92
Fold 2 - Mean Absolute Error (MAE): 0.51
Fold 2 - Root Mean Squared Error (RMSE): 0.96
Fold 2 - Time taken: 1.80 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 0.79
Fold 3 - Mean Absolute Error (MAE): 0.49
Fold 3 - Root Mean Squared Error (RMSE): 0.89
Fold 3 - Time taken: 1.83 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.64
Fold 4 - Mean Absolute Error (MAE): 0.49
Fold 4 - Root Mean Squared Error (RMSE): 0.80
Fold 4 - Time taken: 1.80 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 0.56
Fold 5 - Mean Absolute Error (MAE): 0.47
Fold 5 - Root Mean Squared Error (RMSE): 0.75
Fold 5 - Time taken: 1.79 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 0.73
Mean - Mean Absolute Error (MAE): 0.49
Mean - Root Mean Squared Error (RMSE): 0.85
Mean - Time taken: 1.81 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_1_smoothing1_iReg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_1_smoothing1_iReg1.xlsx file")

Results saved to Results__PL_model_1_smoothing1_iReg1.xlsx file