# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing1_iReg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,66.688172,75.068976,53.182245,73.056056,67.788374,77.307746,64.890843,75.586844,65.825203,73.750217,...,65.641960,64.913049,67.489230,61.863921,73.196529,69.036914,66.517303,73.343097,56.099580,68.936672
1,66.741575,74.852983,53.287063,73.291005,67.879123,77.277822,64.998305,75.894647,66.070266,73.434938,...,65.995269,64.553965,67.092193,61.662246,73.190589,69.409883,66.963501,73.640620,56.101424,69.166934
2,66.902161,74.750946,53.276011,73.398566,67.235056,76.899440,65.378149,75.795359,66.176260,73.631114,...,65.851832,64.910066,67.113507,61.763219,73.246307,69.593262,67.249022,73.646839,56.045839,69.264804
3,66.712568,74.934167,53.441750,73.951559,67.316971,76.880769,65.397431,75.884644,66.344779,73.705960,...,65.883031,65.047979,67.115175,61.869284,73.479001,69.935027,66.894782,73.436827,56.063902,69.426318
4,66.849212,75.073840,53.480414,73.986774,67.786446,76.331166,65.573633,75.453876,66.479890,73.907966,...,66.048597,64.861277,66.910935,61.494472,73.407203,69.703624,66.946025,73.468748,56.192506,69.656221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,74.022771,69.859006,68.104244,55.786407,75.416335,75.252425,71.172560,70.816530,69.281710,71.751092,...,69.640044,71.946631,70.830263,51.371782,75.573297,71.886458,75.412012,71.046695,68.903396,59.527795
2439,73.718520,69.983595,68.241223,55.586233,75.442321,75.276326,71.527905,70.725752,69.197235,72.252812,...,69.490911,72.092646,70.595646,51.416029,75.309504,72.263938,74.929400,70.858360,68.992668,59.035186
2440,73.520505,70.001043,68.391672,55.503485,75.581935,75.252578,71.400468,71.145787,69.173370,72.278263,...,69.455884,71.620440,70.538738,51.323300,74.784932,72.208313,74.463163,70.843516,69.014103,59.514434
2441,73.625925,70.287901,68.781436,55.656132,75.932444,74.983252,71.632744,70.794146,69.656892,72.117630,...,69.535229,71.710074,70.656466,51.311166,74.499012,71.741447,74.207398,70.931823,69.044679,59.117456
2442,73.506245,70.343888,68.539036,55.816792,75.985275,75.006779,71.991957,70.531146,69.871509,72.530334,...,69.498228,71.839448,69.935687,51.237748,74.357875,71.435749,74.041560,70.873168,68.916155,59.113883

In [4]:
position_data = pd.read_excel('real_positions_iReg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,66.688172,75.068976,53.182245,73.056056,67.788374,77.307746,64.890843,75.586844,65.825203,73.750217,...,65.641960,64.913049,67.489230,61.863921,73.196529,69.036914,66.517303,73.343097,56.099580,68.936672
1,66.741575,74.852983,53.287063,73.291005,67.879123,77.277822,64.998305,75.894647,66.070266,73.434938,...,65.995269,64.553965,67.092193,61.662246,73.190589,69.409883,66.963501,73.640620,56.101424,69.166934
2,66.902161,74.750946,53.276011,73.398566,67.235056,76.899440,65.378149,75.795359,66.176260,73.631114,...,65.851832,64.910066,67.113507,61.763219,73.246307,69.593262,67.249022,73.646839,56.045839,69.264804
3,66.712568,74.934167,53.441750,73.951559,67.316971,76.880769,65.397431,75.884644,66.344779,73.705960,...,65.883031,65.047979,67.115175,61.869284,73.479001,69.935027,66.894782,73.436827,56.063902,69.426318
4,66.849212,75.073840,53.480414,73.986774,67.786446,76.331166,65.573633,75.453876,66.479890,73.907966,...,66.048597,64.861277,66.910935,61.494472,73.407203,69.703624,66.946025,73.468748,56.192506,69.656221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,74.022771,69.859006,68.104244,55.786407,75.416335,75.252425,71.172560,70.816530,69.281710,71.751092,...,69.640044,71.946631,70.830263,51.371782,75.573297,71.886458,75.412012,71.046695,68.903396,59.527795
2439,73.718520,69.983595,68.241223,55.586233,75.442321,75.276326,71.527905,70.725752,69.197235,72.252812,...,69.490911,72.092646,70.595646,51.416029,75.309504,72.263938,74.929400,70.858360,68.992668,59.035186
2440,73.520505,70.001043,68.391672,55.503485,75.581935,75.252578,71.400468,71.145787,69.173370,72.278263,...,69.455884,71.620440,70.538738,51.323300,74.784932,72.208313,74.463163,70.843516,69.014103,59.514434
2441,73.625925,70.287901,68.781436,55.656132,75.932444,74.983252,71.632744,70.794146,69.656892,72.117630,...,69.535229,71.710074,70.656466,51.311166,74.499012,71.741447,74.207398,70.931823,69.044679,59.117456
2442,73.506245,70.343888,68.539036,55.816792,75.985275,75.006779,71.991957,70.531146,69.871509,72.530334,...,69.498228,71.839448,69.935687,51.237748,74.357875,71.435749,74.041560,70.873168,68.916155,59.113883

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 2.46
Fold 1 - Mean Absolute Error (MAE): 1.22
Fold 1 - Root Mean Squared Error (RMSE): 1.57
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 2.57
Fold 2 - Mean Absolute Error (MAE): 1.25
Fold 2 - Root Mean Squared Error (RMSE): 1.60
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 2.40
Fold 3 - Mean Absolute Error (MAE): 1.19
Fold 3 - Root Mean Squared Error (RMSE): 1.55
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 2.58
Fold 4 - Mean Absolute Error (MAE): 1.25
Fold 4 - Root Mean Squared Error (RMSE): 1.61
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 2.61
Fold 5 - Mean Absolute Error (MAE): 1.25
Fold 5 - Root Mean Squared Error (RMSE): 1.62
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 2.52
Mean - Mean Absolute Error (MAE): 1.23
Mean - Root Mean Squared Error (RMSE): 1.59
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 4.84
Fold 1 - Mean Absolute Error (MAE): 0.72
Fold 1 - Root Mean Squared Error (RMSE): 2.20
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 3.73
Fold 2 - Mean Absolute Error (MAE): 0.67
Fold 2 - Root Mean Squared Error (RMSE): 1.93
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 3.16
Fold 3 - Mean Absolute Error (MAE): 0.70
Fold 3 - Root Mean Squared Error (RMSE): 1.78
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 2.62
Fold 4 - Mean Absolute Error (MAE): 0.66
Fold 4 - Root Mean Squared Error (RMSE): 1.62
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 2.69
Fold 5 - Mean Absolute Error (MAE): 0.66
Fold 5 - Root Mean Squared Error (RMSE): 1.64
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 3.41
Mean - Mean Absolute Error (MAE): 0.68
Mean - Root Mean Squared Error (RMSE): 1.83
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.70
Fold 1 - Mean Absolute Error (MAE): 0.33
Fold 1 - Root Mean Squared Error (RMSE): 0.84
Fold 1 - Time taken: 2.33 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.31
Fold 2 - Mean Absolute Error (MAE): 0.30
Fold 2 - Root Mean Squared Error (RMSE): 0.55
Fold 2 - Time taken: 2.29 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.35
Fold 3 - Mean Absolute Error (MAE): 0.31
Fold 3 - Root Mean Squared Error (RMSE): 0.59
Fold 3 - Time taken: 3.77 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.54
Fold 4 - Mean Absolute Error (MAE): 0.35
Fold 4 - Root Mean Squared Error (RMSE): 0.74
Fold 4 - Time taken: 3.87 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.62
Fold 5 - Mean Absolute Error (MAE): 0.36
Fold 5 - Root Mean Squared Error (RMSE): 0.79
Fold 5 - Time taken: 3.66 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.51
Mean - Mean Absolute Error (MAE): 0.33
Mean - Root Mean Squared Error (RMSE): 0.70
Mean - Time taken: 3.18 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.05
Fold 1 - Mean Absolute Error (MAE): 0.14
Fold 1 - Root Mean Squared Error (RMSE): 0.22
Fold 1 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.07
Fold 2 - Mean Absolute Error (MAE): 0.16
Fold 2 - Root Mean Squared Error (RMSE): 0.26
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.07
Fold 3 - Mean Absolute Error (MAE): 0.16
Fold 3 - Root Mean Squared Error (RMSE): 0.26
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.07
Fold 4 - Mean Absolute Error (MAE): 0.17
Fold 4 - Root Mean Squared Error (RMSE): 0.26
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.07
Fold 5 - Mean Absolute Error (MAE): 0.17
Fold 5 - Root Mean Squared Error (RMSE): 0.27
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.06
Mean - Mean Absolute Error (MAE): 0.16
Mean - Root Mean Squared Error (RMSE): 0.25
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.21
Fold 1 - Mean Absolute Error (MAE): 0.65
Fold 1 - Root Mean Squared Error (RMSE): 1.10
Fold 1 - Time taken: 1.99 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 1.19
Fold 2 - Mean Absolute Error (MAE): 0.66
Fold 2 - Root Mean Squared Error (RMSE): 1.09
Fold 2 - Time taken: 2.06 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.14
Fold 3 - Mean Absolute Error (MAE): 0.65
Fold 3 - Root Mean Squared Error (RMSE): 1.07
Fold 3 - Time taken: 2.00 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1.73
Fold 4 - Mean Absolute Error (MAE): 0.71
Fold 4 - Root Mean Squared Error (RMSE): 1.32
Fold 4 - Time taken: 1.91 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.83
Fold 5 - Mean Absolute Error (MAE): 0.72
Fold 5 - Root Mean Squared Error (RMSE): 1.35
Fold 5 - Time taken: 1.88 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1.42
Mean - Mean Absolute Error (MAE): 0.68
Mean - Root Mean Squared Error (RMSE): 1.18
Mean - Time taken: 1.97 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing1_iReg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing1_iReg1.xlsx file")

Results saved to Results__PL_model_2_smoothing1_iReg1.xlsx file