# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_Scattered_iReg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,70.443954,80.320483,51.723996,72.417731,67.463699,67.057389,69.587124,72.913178,70.652900,84.556354,...,62.287991,70.409509,75.889064,79.359663,87.407966,58.490649,71.586574,89.161412,59.743878,68.265058
1,47.383001,86.093884,58.756351,70.625885,74.687611,89.397648,76.618619,66.967751,66.247344,63.521696,...,57.774963,67.900129,61.513117,72.211501,80.248461,71.773958,64.311307,59.382326,52.505665,63.817429
2,82.448844,73.032153,40.878287,69.425909,71.080492,75.654272,50.825690,74.525058,66.476023,76.322215,...,63.919342,57.112439,75.214351,66.227123,82.116202,67.990811,64.848385,70.790450,49.900421,45.926255
3,67.831431,61.749993,48.220351,76.876457,64.454453,66.437099,90.137377,78.529441,59.585598,72.508990,...,63.787700,71.221900,63.378131,58.152325,75.467650,78.233603,61.719051,85.704475,52.339192,79.680847
4,75.798687,77.325007,57.205510,76.926102,63.344181,78.037612,74.452727,78.714832,61.641829,80.154880,...,63.733879,71.988598,72.918222,57.981054,70.899572,70.046746,71.609719,85.270214,40.534984,68.161487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,69.473512,67.904407,77.088259,36.771922,68.662086,70.503371,77.620956,79.420051,63.684186,77.535718,...,77.913835,77.582757,68.116143,58.434005,54.058099,75.388570,65.455568,81.110409,67.648867,65.265396
2439,63.217049,62.894416,69.741817,68.821579,64.808422,78.290743,62.016056,73.171317,65.585279,85.082201,...,72.514851,79.469923,77.179203,66.535595,72.343566,61.607351,82.394570,88.734805,68.304711,59.804737
2440,70.341075,64.888481,69.023895,44.777475,78.864616,77.820509,70.349917,61.912433,67.903595,77.928597,...,79.457903,75.662321,72.256087,46.236286,64.694190,62.678831,85.239980,61.598902,73.665931,67.762866
2441,63.072439,47.354345,79.164223,56.292435,73.706493,87.907443,82.855155,62.150347,74.015714,77.342385,...,57.059775,82.640275,67.843985,54.008337,83.770642,65.512264,76.460540,68.489790,73.596747,52.431244
2442,77.464832,84.677537,65.686028,50.662071,87.028456,83.942289,70.439818,65.447778,53.918062,70.806675,...,63.244041,81.839194,78.329396,46.116316,57.828163,83.311491,82.465452,71.309128,81.041892,57.114542

In [4]:
position_data = pd.read_excel('real_positions_iReg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,70.443954,80.320483,51.723996,72.417731,67.463699,67.057389,69.587124,72.913178,70.652900,84.556354,...,62.287991,70.409509,75.889064,79.359663,87.407966,58.490649,71.586574,89.161412,59.743878,68.265058
1,47.383001,86.093884,58.756351,70.625885,74.687611,89.397648,76.618619,66.967751,66.247344,63.521696,...,57.774963,67.900129,61.513117,72.211501,80.248461,71.773958,64.311307,59.382326,52.505665,63.817429
2,82.448844,73.032153,40.878287,69.425909,71.080492,75.654272,50.825690,74.525058,66.476023,76.322215,...,63.919342,57.112439,75.214351,66.227123,82.116202,67.990811,64.848385,70.790450,49.900421,45.926255
3,67.831431,61.749993,48.220351,76.876457,64.454453,66.437099,90.137377,78.529441,59.585598,72.508990,...,63.787700,71.221900,63.378131,58.152325,75.467650,78.233603,61.719051,85.704475,52.339192,79.680847
4,75.798687,77.325007,57.205510,76.926102,63.344181,78.037612,74.452727,78.714832,61.641829,80.154880,...,63.733879,71.988598,72.918222,57.981054,70.899572,70.046746,71.609719,85.270214,40.534984,68.161487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,69.473512,67.904407,77.088259,36.771922,68.662086,70.503371,77.620956,79.420051,63.684186,77.535718,...,77.913835,77.582757,68.116143,58.434005,54.058099,75.388570,65.455568,81.110409,67.648867,65.265396
2439,63.217049,62.894416,69.741817,68.821579,64.808422,78.290743,62.016056,73.171317,65.585279,85.082201,...,72.514851,79.469923,77.179203,66.535595,72.343566,61.607351,82.394570,88.734805,68.304711,59.804737
2440,70.341075,64.888481,69.023895,44.777475,78.864616,77.820509,70.349917,61.912433,67.903595,77.928597,...,79.457903,75.662321,72.256087,46.236286,64.694190,62.678831,85.239980,61.598902,73.665931,67.762866
2441,63.072439,47.354345,79.164223,56.292435,73.706493,87.907443,82.855155,62.150347,74.015714,77.342385,...,57.059775,82.640275,67.843985,54.008337,83.770642,65.512264,76.460540,68.489790,73.596747,52.431244
2442,77.464832,84.677537,65.686028,50.662071,87.028456,83.942289,70.439818,65.447778,53.918062,70.806675,...,63.244041,81.839194,78.329396,46.116316,57.828163,83.311491,82.465452,71.309128,81.041892,57.114542

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 186.36
Fold 1 - Mean Absolute Error (MAE): 10.55
Fold 1 - Root Mean Squared Error (RMSE): 13.65
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 196.51
Fold 2 - Mean Absolute Error (MAE): 10.84
Fold 2 - Root Mean Squared Error (RMSE): 14.02
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 176.95
Fold 3 - Mean Absolute Error (MAE): 10.35
Fold 3 - Root Mean Squared Error (RMSE): 13.30
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 184.51
Fold 4 - Mean Absolute Error (MAE): 10.41
Fold 4 - Root Mean Squared Error (RMSE): 13.58
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 184.08
Fold 5 - Mean Absolute Error (MAE): 10.58
Fold 5 - Root Mean Squared Error (RMSE): 13.57
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 185.68
Mean - Mean Absolute Error (MAE): 10.55
Mean - Root Mean Squared Error (RMSE): 13.62
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 710.40
Fold 1 - Mean Absolute Error (MAE): 19.32
Fold 1 - Root Mean Squared Error (RMSE): 26.65
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 736.41
Fold 2 - Mean Absolute Error (MAE): 19.46
Fold 2 - Root Mean Squared Error (RMSE): 27.14
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 740.73
Fold 3 - Mean Absolute Error (MAE): 20.24
Fold 3 - Root Mean Squared Error (RMSE): 27.22
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 731.80
Fold 4 - Mean Absolute Error (MAE): 19.73
Fold 4 - Root Mean Squared Error (RMSE): 27.05
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 688.20
Fold 5 - Mean Absolute Error (MAE): 19.24
Fold 5 - Root Mean Squared Error (RMSE): 26.23
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 721.51
Mean - Mean Absolute Error (MAE): 19.60
Mean - Root Mean Squared Error (RMSE): 26.86
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 273.85
Fold 1 - Mean Absolute Error (MAE): 13.49
Fold 1 - Root Mean Squared Error (RMSE): 16.55
Fold 1 - Time taken: 2.69 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 304.01
Fold 2 - Mean Absolute Error (MAE): 14.23
Fold 2 - Root Mean Squared Error (RMSE): 17.44
Fold 2 - Time taken: 2.83 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 274.08
Fold 3 - Mean Absolute Error (MAE): 13.38
Fold 3 - Root Mean Squared Error (RMSE): 16.56
Fold 3 - Time taken: 4.08 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 277.60
Fold 4 - Mean Absolute Error (MAE): 13.52
Fold 4 - Root Mean Squared Error (RMSE): 16.66
Fold 4 - Time taken: 4.04 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 269.50
Fold 5 - Mean Absolute Error (MAE): 13.51
Fold 5 - Root Mean Squared Error (RMSE): 16.42
Fold 5 - Time taken: 4.17 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 279.81
Mean - Mean Absolute Error (MAE): 13.63
Mean - Root Mean Squared Error (RMSE): 16.72
Mean - Time taken: 3.56 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 227.43
Fold 1 - Mean Absolute Error (MAE): 11.69
Fold 1 - Root Mean Squared Error (RMSE): 15.08
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 260.18
Fold 2 - Mean Absolute Error (MAE): 12.42
Fold 2 - Root Mean Squared Error (RMSE): 16.13
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 234.28
Fold 3 - Mean Absolute Error (MAE): 11.90
Fold 3 - Root Mean Squared Error (RMSE): 15.31
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 240.66
Fold 4 - Mean Absolute Error (MAE): 12.02
Fold 4 - Root Mean Squared Error (RMSE): 15.51
Fold 4 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 225.14
Fold 5 - Mean Absolute Error (MAE): 11.68
Fold 5 - Root Mean Squared Error (RMSE): 15.00
Fold 5 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 237.54
Mean - Mean Absolute Error (MAE): 11.94
Mean - Root Mean Squared Error (RMSE): 15.41
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 245.82
Fold 1 - Mean Absolute Error (MAE): 11.90
Fold 1 - Root Mean Squared Error (RMSE): 15.68
Fold 1 - Time taken: 2.16 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 267.06
Fold 2 - Mean Absolute Error (MAE): 12.44
Fold 2 - Root Mean Squared Error (RMSE): 16.34
Fold 2 - Time taken: 2.17 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 248.49
Fold 3 - Mean Absolute Error (MAE): 12.16
Fold 3 - Root Mean Squared Error (RMSE): 15.76
Fold 3 - Time taken: 2.10 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 250.17
Fold 4 - Mean Absolute Error (MAE): 12.11
Fold 4 - Root Mean Squared Error (RMSE): 15.82
Fold 4 - Time taken: 2.10 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 251.05
Fold 5 - Mean Absolute Error (MAE): 12.16
Fold 5 - Root Mean Squared Error (RMSE): 15.84
Fold 5 - Time taken: 2.08 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 252.52
Mean - Mean Absolute Error (MAE): 12.15
Mean - Root Mean Squared Error (RMSE): 15.89
Mean - Time taken: 2.12 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_Scattered_iReg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_Scattered_iReg1.xlsx file")

Results saved to Results__PL_model_2_Scattered_iReg1.xlsx file