# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing2_iReg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,72.033389,75.510500,52.228026,70.715550,67.742815,73.508353,63.811741,74.765067,67.332049,74.563436,...,63.307131,64.706944,67.406712,66.646165,74.159242,68.597226,66.168497,73.230844,52.870421,70.180480
1,71.744390,75.457685,52.277407,70.893738,67.754051,73.709107,63.815575,74.773595,67.326523,74.519953,...,63.520109,64.695513,67.372596,66.367791,74.048053,68.664635,66.201155,73.189735,53.115785,70.152712
2,71.457271,75.408663,52.327813,71.070965,67.767235,73.909717,63.825089,74.783528,67.317708,74.478985,...,63.730589,64.687253,67.342108,66.091550,73.943120,68.731134,66.236692,73.153609,53.356063,70.124189
3,71.172381,75.362976,52.379193,71.247000,67.782225,74.109960,63.839821,74.795542,67.305273,74.440630,...,63.938680,64.681923,67.315252,65.816744,73.843825,68.797008,66.275143,73.122729,53.590438,70.095460
4,70.889809,75.320215,52.431779,71.421615,67.798734,74.309495,63.859533,74.810389,67.288984,74.405021,...,64.144538,64.679423,67.291864,65.542657,73.749173,68.862479,66.316647,73.097466,53.818188,70.067226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,70.944519,70.181655,67.954250,51.721624,74.388500,75.042963,74.450091,70.001308,66.759282,75.113377,...,70.670557,75.823022,70.567682,51.962743,70.537256,73.935762,73.500594,71.001983,70.261137,61.524840
2439,70.696559,70.172216,67.945971,51.409638,74.291528,75.089736,74.654781,69.843373,66.511747,75.260886,...,70.786417,76.122671,70.626385,52.039301,70.146630,74.108896,73.452843,71.000850,70.340789,61.702800
2440,70.447378,70.159652,67.938917,51.095632,74.194176,75.141064,74.854950,69.682557,66.261394,75.407170,...,70.905125,76.428664,70.689864,52.119157,69.750582,74.279537,73.410888,71.000949,70.423744,61.882606
2441,70.197063,70.144052,67.933613,50.779936,74.097177,75.197822,75.050694,69.518143,66.008496,75.552455,...,71.025759,76.741121,70.758294,52.201677,69.349239,74.447187,73.375562,71.001806,70.510560,62.063462
2442,69.945810,70.125824,67.930403,50.462956,74.001134,75.260637,75.242283,69.349733,65.753182,75.696771,...,71.147256,77.060102,70.831739,52.286353,68.942799,74.611860,73.347238,71.003204,70.601645,62.244524

In [4]:
position_data = pd.read_excel('real_positions_iReg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,72.033389,75.510500,52.228026,70.715550,67.742815,73.508353,63.811741,74.765067,67.332049,74.563436,...,63.307131,64.706944,67.406712,66.646165,74.159242,68.597226,66.168497,73.230844,52.870421,70.180480
1,71.744390,75.457685,52.277407,70.893738,67.754051,73.709107,63.815575,74.773595,67.326523,74.519953,...,63.520109,64.695513,67.372596,66.367791,74.048053,68.664635,66.201155,73.189735,53.115785,70.152712
2,71.457271,75.408663,52.327813,71.070965,67.767235,73.909717,63.825089,74.783528,67.317708,74.478985,...,63.730589,64.687253,67.342108,66.091550,73.943120,68.731134,66.236692,73.153609,53.356063,70.124189
3,71.172381,75.362976,52.379193,71.247000,67.782225,74.109960,63.839821,74.795542,67.305273,74.440630,...,63.938680,64.681923,67.315252,65.816744,73.843825,68.797008,66.275143,73.122729,53.590438,70.095460
4,70.889809,75.320215,52.431779,71.421615,67.798734,74.309495,63.859533,74.810389,67.288984,74.405021,...,64.144538,64.679423,67.291864,65.542657,73.749173,68.862479,66.316647,73.097466,53.818188,70.067226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,70.944519,70.181655,67.954250,51.721624,74.388500,75.042963,74.450091,70.001308,66.759282,75.113377,...,70.670557,75.823022,70.567682,51.962743,70.537256,73.935762,73.500594,71.001983,70.261137,61.524840
2439,70.696559,70.172216,67.945971,51.409638,74.291528,75.089736,74.654781,69.843373,66.511747,75.260886,...,70.786417,76.122671,70.626385,52.039301,70.146630,74.108896,73.452843,71.000850,70.340789,61.702800
2440,70.447378,70.159652,67.938917,51.095632,74.194176,75.141064,74.854950,69.682557,66.261394,75.407170,...,70.905125,76.428664,70.689864,52.119157,69.750582,74.279537,73.410888,71.000949,70.423744,61.882606
2441,70.197063,70.144052,67.933613,50.779936,74.097177,75.197822,75.050694,69.518143,66.008496,75.552455,...,71.025759,76.741121,70.758294,52.201677,69.349239,74.447187,73.375562,71.001806,70.510560,62.063462
2442,69.945810,70.125824,67.930403,50.462956,74.001134,75.260637,75.242283,69.349733,65.753182,75.696771,...,71.147256,77.060102,70.831739,52.286353,68.942799,74.611860,73.347238,71.003204,70.601645,62.244524

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 7.91
Fold 1 - Mean Absolute Error (MAE): 2.15
Fold 1 - Root Mean Squared Error (RMSE): 2.81
Fold 1 - Time taken: 0.02 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 8.31
Fold 2 - Mean Absolute Error (MAE): 2.18
Fold 2 - Root Mean Squared Error (RMSE): 2.88
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 7.48
Fold 3 - Mean Absolute Error (MAE): 2.06
Fold 3 - Root Mean Squared Error (RMSE): 2.73
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 7.98
Fold 4 - Mean Absolute Error (MAE): 2.11
Fold 4 - Root Mean Squared Error (RMSE): 2.83
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 8.92
Fold 5 - Mean Absolute Error (MAE): 2.27
Fold 5 - Root Mean Squared Error (RMSE): 2.99
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 8.12
Mean - Mean Absolute Error (MAE): 2.15
Mean - Root Mean Squared Error (RMSE): 2.85
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 1.58
Fold 1 - Mean Absolute Error (MAE): 0.41
Fold 1 - Root Mean Squared Error (RMSE): 1.26
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 2.28
Fold 2 - Mean Absolute Error (MAE): 0.43
Fold 2 - Root Mean Squared Error (RMSE): 1.51
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 6.77
Fold 3 - Mean Absolute Error (MAE): 0.55
Fold 3 - Root Mean Squared Error (RMSE): 2.60
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 2.70
Fold 4 - Mean Absolute Error (MAE): 0.44
Fold 4 - Root Mean Squared Error (RMSE): 1.64
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 3.83
Fold 5 - Mean Absolute Error (MAE): 0.48
Fold 5 - Root Mean Squared Error (RMSE): 1.96
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 3.43
Mean - Mean Absolute Error (MAE): 0.46
Mean - Root Mean Squared Error (RMSE): 1.79
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.19
Fold 1 - Mean Absolute Error (MAE): 0.24
Fold 1 - Root Mean Squared Error (RMSE): 0.43
Fold 1 - Time taken: 2.35 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.29
Fold 2 - Mean Absolute Error (MAE): 0.26
Fold 2 - Root Mean Squared Error (RMSE): 0.54
Fold 2 - Time taken: 2.63 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.50
Fold 3 - Mean Absolute Error (MAE): 0.28
Fold 3 - Root Mean Squared Error (RMSE): 0.70
Fold 3 - Time taken: 3.55 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.36
Fold 4 - Mean Absolute Error (MAE): 0.24
Fold 4 - Root Mean Squared Error (RMSE): 0.60
Fold 4 - Time taken: 3.54 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.24
Fold 5 - Mean Absolute Error (MAE): 0.25
Fold 5 - Root Mean Squared Error (RMSE): 0.49
Fold 5 - Time taken: 3.73 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.32
Mean - Mean Absolute Error (MAE): 0.25
Mean - Root Mean Squared Error (RMSE): 0.55
Mean - Time taken: 3.16 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.04
Fold 1 - Mean Absolute Error (MAE): 0.13
Fold 1 - Root Mean Squared Error (RMSE): 0.20
Fold 1 - Time taken: 0.09 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.05
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.22
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.06
Fold 3 - Mean Absolute Error (MAE): 0.15
Fold 3 - Root Mean Squared Error (RMSE): 0.24
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.05
Fold 4 - Mean Absolute Error (MAE): 0.14
Fold 4 - Root Mean Squared Error (RMSE): 0.22
Fold 4 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.05
Fold 5 - Mean Absolute Error (MAE): 0.14
Fold 5 - Root Mean Squared Error (RMSE): 0.23
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.05
Mean - Mean Absolute Error (MAE): 0.14
Mean - Root Mean Squared Error (RMSE): 0.22
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.97
Fold 1 - Mean Absolute Error (MAE): 0.47
Fold 1 - Root Mean Squared Error (RMSE): 0.98
Fold 1 - Time taken: 1.93 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 1.04
Fold 2 - Mean Absolute Error (MAE): 0.49
Fold 2 - Root Mean Squared Error (RMSE): 1.02
Fold 2 - Time taken: 1.92 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 0.89
Fold 3 - Mean Absolute Error (MAE): 0.47
Fold 3 - Root Mean Squared Error (RMSE): 0.94
Fold 3 - Time taken: 2.25 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.81
Fold 4 - Mean Absolute Error (MAE): 0.47
Fold 4 - Root Mean Squared Error (RMSE): 0.90
Fold 4 - Time taken: 2.60 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 0.82
Fold 5 - Mean Absolute Error (MAE): 0.47
Fold 5 - Root Mean Squared Error (RMSE): 0.91
Fold 5 - Time taken: 2.50 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 0.91
Mean - Mean Absolute Error (MAE): 0.47
Mean - Root Mean Squared Error (RMSE): 0.95
Mean - Time taken: 2.24 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing2_iReg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing2_iReg1.xlsx file")

Results saved to Results__PL_model_2_smoothing2_iReg1.xlsx file