# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_Scattered_Reg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,64.966458,76.691794,68.124658,69.178081,64.534165,76.817590,82.036444,63.012904,76.124602,66.512576,...,70.362393,59.270961,60.621590,54.192753,83.544496,57.301764,63.951668,83.072964,60.473752,72.292435
1,73.692700,63.680076,63.407868,64.440492,69.481736,65.529803,64.520032,74.239935,65.563082,73.345285,...,75.015437,73.007565,59.834268,63.443141,81.114206,78.928829,64.997488,70.986068,67.150721,49.406450
2,77.423386,68.207059,65.416411,81.006436,70.308422,93.886350,77.208542,79.014001,71.285041,64.713052,...,70.215749,66.022268,55.280539,71.956223,72.425614,58.764071,76.240297,89.828820,71.746000,73.450073
3,79.604227,60.100769,78.108050,71.702062,76.073666,85.096470,64.170158,78.554347,61.627531,63.580600,...,56.684107,63.206736,75.628206,61.889875,70.740295,66.647134,70.709824,76.945843,58.398246,76.749932
4,68.911221,67.146110,52.263216,77.054846,78.253807,78.206904,62.812263,66.284075,67.920070,74.997227,...,69.078210,65.429437,68.308554,64.388971,64.508250,61.106363,60.320194,63.822647,59.836285,68.951026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,77.635861,74.631760,58.895053,58.303407,79.082038,88.117920,72.722073,74.539170,76.658832,62.204263,...,61.566679,72.852155,55.812086,48.624382,69.453316,61.341108,79.265735,73.592422,82.282273,65.717778
2439,62.823602,72.690260,69.706508,56.995139,77.503766,74.898295,75.334289,72.963421,77.060024,80.256079,...,66.739113,61.633896,60.646570,58.331447,64.230697,75.307707,75.821711,74.601668,59.415883,67.166067
2440,81.389384,87.789650,67.253795,49.295169,63.452192,90.038200,83.933123,73.024195,70.681611,50.560766,...,50.103849,69.614166,46.320473,61.069086,78.216320,68.933371,76.296101,79.191328,78.368429,62.083876
2441,73.478893,74.239110,80.832142,57.894213,69.474806,73.222195,81.259577,52.787488,65.549878,67.340342,...,70.114742,67.666341,72.920214,48.609700,69.509795,71.538253,65.692645,72.449802,60.116178,81.836236
2442,80.366900,56.786580,78.892167,52.696707,73.300030,78.292661,57.602685,67.369970,68.721017,65.338030,...,81.834828,56.875920,70.828006,54.539941,68.782268,72.568965,79.268439,44.393526,61.642113,54.547595

In [4]:
position_data = pd.read_excel('real_positions_Reg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,64.966458,76.691794,68.124658,69.178081,64.534165,76.817590,82.036444,63.012904,76.124602,66.512576,...,70.362393,59.270961,60.621590,54.192753,83.544496,57.301764,63.951668,83.072964,60.473752,72.292435
1,73.692700,63.680076,63.407868,64.440492,69.481736,65.529803,64.520032,74.239935,65.563082,73.345285,...,75.015437,73.007565,59.834268,63.443141,81.114206,78.928829,64.997488,70.986068,67.150721,49.406450
2,77.423386,68.207059,65.416411,81.006436,70.308422,93.886350,77.208542,79.014001,71.285041,64.713052,...,70.215749,66.022268,55.280539,71.956223,72.425614,58.764071,76.240297,89.828820,71.746000,73.450073
3,79.604227,60.100769,78.108050,71.702062,76.073666,85.096470,64.170158,78.554347,61.627531,63.580600,...,56.684107,63.206736,75.628206,61.889875,70.740295,66.647134,70.709824,76.945843,58.398246,76.749932
4,68.911221,67.146110,52.263216,77.054846,78.253807,78.206904,62.812263,66.284075,67.920070,74.997227,...,69.078210,65.429437,68.308554,64.388971,64.508250,61.106363,60.320194,63.822647,59.836285,68.951026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,77.635861,74.631760,58.895053,58.303407,79.082038,88.117920,72.722073,74.539170,76.658832,62.204263,...,61.566679,72.852155,55.812086,48.624382,69.453316,61.341108,79.265735,73.592422,82.282273,65.717778
2439,62.823602,72.690260,69.706508,56.995139,77.503766,74.898295,75.334289,72.963421,77.060024,80.256079,...,66.739113,61.633896,60.646570,58.331447,64.230697,75.307707,75.821711,74.601668,59.415883,67.166067
2440,81.389384,87.789650,67.253795,49.295169,63.452192,90.038200,83.933123,73.024195,70.681611,50.560766,...,50.103849,69.614166,46.320473,61.069086,78.216320,68.933371,76.296101,79.191328,78.368429,62.083876
2441,73.478893,74.239110,80.832142,57.894213,69.474806,73.222195,81.259577,52.787488,65.549878,67.340342,...,70.114742,67.666341,72.920214,48.609700,69.509795,71.538253,65.692645,72.449802,60.116178,81.836236
2442,80.366900,56.786580,78.892167,52.696707,73.300030,78.292661,57.602685,67.369970,68.721017,65.338030,...,81.834828,56.875920,70.828006,54.539941,68.782268,72.568965,79.268439,44.393526,61.642113,54.547595

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 40

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:40]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor31,sensor32,sensor33,sensor34,sensor35,sensor36,sensor37,sensor38,sensor39,sensor40
0,64.966458,76.691794,68.124658,69.178081,64.534165,76.817590,82.036444,63.012904,76.124602,66.512576,...,72.819388,65.283534,67.837898,64.951535,62.233605,68.091168,72.010235,68.326715,70.362393,59.270961
1,73.692700,63.680076,63.407868,64.440492,69.481736,65.529803,64.520032,74.239935,65.563082,73.345285,...,78.308349,75.817764,73.423259,75.122995,46.268483,52.814638,83.712267,63.618418,75.015437,73.007565
2,77.423386,68.207059,65.416411,81.006436,70.308422,93.886350,77.208542,79.014001,71.285041,64.713052,...,62.142644,67.981826,59.795750,67.086862,59.489681,66.119881,61.566812,63.363487,70.215749,66.022268
3,79.604227,60.100769,78.108050,71.702062,76.073666,85.096470,64.170158,78.554347,61.627531,63.580600,...,60.751379,73.968482,61.090089,80.559025,65.244650,65.891106,71.283248,57.042811,56.684107,63.206736
4,68.911221,67.146110,52.263216,77.054846,78.253807,78.206904,62.812263,66.284075,67.920070,74.997227,...,75.402823,63.503100,64.069436,72.631853,62.469157,56.412746,68.164661,60.115859,69.078210,65.429437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,77.635861,74.631760,58.895053,58.303407,79.082038,88.117920,72.722073,74.539170,76.658832,62.204263,...,68.176576,78.623217,71.460574,51.353708,60.220530,79.440956,66.321048,45.056290,61.566679,72.852155
2439,62.823602,72.690260,69.706508,56.995139,77.503766,74.898295,75.334289,72.963421,77.060024,80.256079,...,53.888679,75.582977,50.341498,65.783585,61.039875,78.630457,73.590350,56.154660,66.739113,61.633896
2440,81.389384,87.789650,67.253795,49.295169,63.452192,90.038200,83.933123,73.024195,70.681611,50.560766,...,82.001608,62.923210,65.356577,62.851135,38.865473,63.893033,75.293906,40.188008,50.103849,69.614166
2441,73.478893,74.239110,80.832142,57.894213,69.474806,73.222195,81.259577,52.787488,65.549878,67.340342,...,79.815953,81.281076,62.995782,67.934085,75.060893,72.961620,65.975999,53.568909,70.114742,67.666341
2442,80.366900,56.786580,78.892167,52.696707,73.300030,78.292661,57.602685,67.369970,68.721017,65.338030,...,69.602284,84.446399,54.917359,69.973727,62.035472,49.148602,80.325773,53.695057,81.834828,56.875920

# Importing Libraries

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [15]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

In [16]:
X

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor31,sensor32,sensor33,sensor34,sensor35,sensor36,sensor37,sensor38,sensor39,sensor40
0,64.966458,76.691794,68.124658,69.178081,64.534165,76.817590,82.036444,63.012904,76.124602,66.512576,...,72.819388,65.283534,67.837898,64.951535,62.233605,68.091168,72.010235,68.326715,70.362393,59.270961
1,73.692700,63.680076,63.407868,64.440492,69.481736,65.529803,64.520032,74.239935,65.563082,73.345285,...,78.308349,75.817764,73.423259,75.122995,46.268483,52.814638,83.712267,63.618418,75.015437,73.007565
2,77.423386,68.207059,65.416411,81.006436,70.308422,93.886350,77.208542,79.014001,71.285041,64.713052,...,62.142644,67.981826,59.795750,67.086862,59.489681,66.119881,61.566812,63.363487,70.215749,66.022268
3,79.604227,60.100769,78.108050,71.702062,76.073666,85.096470,64.170158,78.554347,61.627531,63.580600,...,60.751379,73.968482,61.090089,80.559025,65.244650,65.891106,71.283248,57.042811,56.684107,63.206736
4,68.911221,67.146110,52.263216,77.054846,78.253807,78.206904,62.812263,66.284075,67.920070,74.997227,...,75.402823,63.503100,64.069436,72.631853,62.469157,56.412746,68.164661,60.115859,69.078210,65.429437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,77.635861,74.631760,58.895053,58.303407,79.082038,88.117920,72.722073,74.539170,76.658832,62.204263,...,68.176576,78.623217,71.460574,51.353708,60.220530,79.440956,66.321048,45.056290,61.566679,72.852155
2439,62.823602,72.690260,69.706508,56.995139,77.503766,74.898295,75.334289,72.963421,77.060024,80.256079,...,53.888679,75.582977,50.341498,65.783585,61.039875,78.630457,73.590350,56.154660,66.739113,61.633896
2440,81.389384,87.789650,67.253795,49.295169,63.452192,90.038200,83.933123,73.024195,70.681611,50.560766,...,82.001608,62.923210,65.356577,62.851135,38.865473,63.893033,75.293906,40.188008,50.103849,69.614166
2441,73.478893,74.239110,80.832142,57.894213,69.474806,73.222195,81.259577,52.787488,65.549878,67.340342,...,79.815953,81.281076,62.995782,67.934085,75.060893,72.961620,65.975999,53.568909,70.114742,67.666341
2442,80.366900,56.786580,78.892167,52.696707,73.300030,78.292661,57.602685,67.369970,68.721017,65.338030,...,69.602284,84.446399,54.917359,69.973727,62.035472,49.148602,80.325773,53.695057,81.834828,56.875920

In [17]:
y

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Define models

In [18]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [19]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [20]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [21]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 202.02
Fold 1 - Mean Absolute Error (MAE): 11.16
Fold 1 - Root Mean Squared Error (RMSE): 14.21
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 213.78
Fold 2 - Mean Absolute Error (MAE): 11.40
Fold 2 - Root Mean Squared Error (RMSE): 14.62
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 203.26
Fold 3 - Mean Absolute Error (MAE): 11.35
Fold 3 - Root Mean Squared Error (RMSE): 14.26
Fold 3 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 209.16
Fold 4 - Mean Absolute Error (MAE): 11.35
Fold 4 - Root Mean Squared Error (RMSE): 14.46
Fold 4 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 202.25
Fold 5 - Mean Absolute Error (MAE): 11.09
Fold 5 - Root Mean Squared Error (RMSE): 14.22
Fold 5 - Time taken: 0.00 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 206.09
Mean - Mean Absolute Error (MAE): 11.27
Mean - Root Mean Squared Error (RMSE): 14.36
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 759.54
Fold 1 - Mean Absolute Error (MAE): 20.13
Fold 1 - Root Mean Squared Error (RMSE): 27.56
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 737.56
Fold 2 - Mean Absolute Error (MAE): 20.30
Fold 2 - Root Mean Squared Error (RMSE): 27.16
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 719.88
Fold 3 - Mean Absolute Error (MAE): 19.72
Fold 3 - Root Mean Squared Error (RMSE): 26.83
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 753.28
Fold 4 - Mean Absolute Error (MAE): 20.05
Fold 4 - Root Mean Squared Error (RMSE): 27.45
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 690.10
Fold 5 - Mean Absolute Error (MAE): 19.38
Fold 5 - Root Mean Squared Error (RMSE): 26.27
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 732.07
Mean - Mean Absolute Error (MAE): 19.92
Mean - Root Mean Squared Error (RMSE): 27.05
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 293.96
Fold 1 - Mean Absolute Error (MAE): 13.95
Fold 1 - Root Mean Squared Error (RMSE): 17.15
Fold 1 - Time taken: 2.37 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 306.59
Fold 2 - Mean Absolute Error (MAE): 14.48
Fold 2 - Root Mean Squared Error (RMSE): 17.51
Fold 2 - Time taken: 2.39 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 286.99
Fold 3 - Mean Absolute Error (MAE): 13.89
Fold 3 - Root Mean Squared Error (RMSE): 16.94
Fold 3 - Time taken: 3.65 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 294.54
Fold 4 - Mean Absolute Error (MAE): 14.01
Fold 4 - Root Mean Squared Error (RMSE): 17.16
Fold 4 - Time taken: 3.65 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 288.84
Fold 5 - Mean Absolute Error (MAE): 13.88
Fold 5 - Root Mean Squared Error (RMSE): 17.00
Fold 5 - Time taken: 3.78 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 294.18
Mean - Mean Absolute Error (MAE): 14.04
Mean - Root Mean Squared Error (RMSE): 17.15
Mean - Time taken: 3.17 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 258.71
Fold 1 - Mean Absolute Error (MAE): 12.57
Fold 1 - Root Mean Squared Error (RMSE): 16.08
Fold 1 - Time taken: 0.09 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 276.15
Fold 2 - Mean Absolute Error (MAE): 13.08
Fold 2 - Root Mean Squared Error (RMSE): 16.62
Fold 2 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 258.23
Fold 3 - Mean Absolute Error (MAE): 12.58
Fold 3 - Root Mean Squared Error (RMSE): 16.07
Fold 3 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 284.06
Fold 4 - Mean Absolute Error (MAE): 13.24
Fold 4 - Root Mean Squared Error (RMSE): 16.85
Fold 4 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 249.09
Fold 5 - Mean Absolute Error (MAE): 12.40
Fold 5 - Root Mean Squared Error (RMSE): 15.78
Fold 5 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 265.25
Mean - Mean Absolute Error (MAE): 12.77
Mean - Root Mean Squared Error (RMSE): 16.28
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 279.88
Fold 1 - Mean Absolute Error (MAE): 12.73
Fold 1 - Root Mean Squared Error (RMSE): 16.73
Fold 1 - Time taken: 3.17 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 268.00
Fold 2 - Mean Absolute Error (MAE): 12.53
Fold 2 - Root Mean Squared Error (RMSE): 16.37
Fold 2 - Time taken: 0.82 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 280.18
Fold 3 - Mean Absolute Error (MAE): 13.02
Fold 3 - Root Mean Squared Error (RMSE): 16.74
Fold 3 - Time taken: 0.81 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 279.17
Fold 4 - Mean Absolute Error (MAE): 12.94
Fold 4 - Root Mean Squared Error (RMSE): 16.71
Fold 4 - Time taken: 0.81 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 278.98
Fold 5 - Mean Absolute Error (MAE): 12.84
Fold 5 - Root Mean Squared Error (RMSE): 16.70
Fold 5 - Time taken: 0.95 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 277.24
Mean - Mean Absolute Error (MAE): 12.81
Mean - Root Mean Squared Error (RMSE): 16.65
Mean - Time taken: 1.31 seconds

# Saving the Mean results to an Excel file

In [22]:
# Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

# Filter the dataframe to include only the mean values
mean_results_df = results_df[results_df["Fold"] == "Mean"]

# Save the mean results to an Excel file
mean_results_df.to_excel("(1-40) Sensors PL_model_2_Scattered_Reg1 Results.xlsx", index=False)