# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_Scattered_iReg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,101.870132,134.252574,72.801390,108.446568,130.203502,150.760073,103.508252,125.193887,89.453295,97.318384,...,81.685404,84.830110,86.513881,81.048996,114.964811,120.010616,103.909997,133.568532,57.626093,109.708209
1,101.656974,133.421922,76.037698,115.578180,124.237134,144.797812,106.645699,137.372609,92.314999,112.314087,...,81.526583,92.908051,94.438277,89.628271,114.498751,106.887589,99.505693,128.544662,67.730350,113.436964
2,102.889598,140.640194,71.553137,106.871465,123.654012,148.446127,103.789337,135.667714,99.182335,106.232463,...,75.930487,82.432658,87.572150,90.919428,116.186110,121.150696,96.193748,134.116483,68.863500,116.446807
3,100.508164,130.788193,73.179060,122.566756,128.558120,144.121205,102.460744,129.928887,86.763744,106.168512,...,79.984057,99.957787,93.313344,84.668294,111.953201,119.676628,106.414441,137.948662,69.634344,114.024685
4,104.073940,127.217426,69.730286,115.690253,120.920018,148.666096,116.786233,139.061346,83.559242,103.091764,...,75.279364,87.349475,97.655142,89.118820,126.637608,114.886056,101.361093,126.482809,66.133931,109.168340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,126.520010,110.917507,102.822108,62.853700,149.747652,127.099840,123.942335,108.196626,107.105731,96.441980,...,91.496394,121.729389,87.948166,77.602308,127.656991,114.668824,127.756278,109.362652,102.983525,78.077730
2439,122.656116,114.785269,98.718438,76.449249,152.660776,140.174139,136.835759,113.267986,104.631338,98.998328,...,92.880258,108.747017,88.541794,75.344392,125.557441,111.031434,134.494231,116.813742,112.599318,79.992646
2440,126.597748,119.491178,105.538634,75.394449,145.766322,143.595590,129.875574,120.944104,106.966013,96.617547,...,89.648431,106.485343,93.400271,71.177932,123.918015,105.789520,127.670906,109.512188,104.166149,83.022547
2441,139.564043,109.141995,106.936201,78.218026,144.561741,141.507291,125.361425,123.071554,105.897605,91.914775,...,86.126272,106.959002,88.494586,63.991014,129.409898,109.907911,126.391262,111.268189,100.508162,70.592735
2442,132.013398,115.430773,105.461899,71.804618,151.624598,143.982949,127.958184,113.784393,97.022346,99.972913,...,88.589209,107.322913,86.795897,75.659668,122.322131,117.782888,126.797409,117.722182,110.106607,76.549859

In [4]:
position_data = pd.read_excel('real_positions_iReg3.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,101.870132,134.252574,72.801390,108.446568,130.203502,150.760073,103.508252,125.193887,89.453295,97.318384,...,81.685404,84.830110,86.513881,81.048996,114.964811,120.010616,103.909997,133.568532,57.626093,109.708209
1,101.656974,133.421922,76.037698,115.578180,124.237134,144.797812,106.645699,137.372609,92.314999,112.314087,...,81.526583,92.908051,94.438277,89.628271,114.498751,106.887589,99.505693,128.544662,67.730350,113.436964
2,102.889598,140.640194,71.553137,106.871465,123.654012,148.446127,103.789337,135.667714,99.182335,106.232463,...,75.930487,82.432658,87.572150,90.919428,116.186110,121.150696,96.193748,134.116483,68.863500,116.446807
3,100.508164,130.788193,73.179060,122.566756,128.558120,144.121205,102.460744,129.928887,86.763744,106.168512,...,79.984057,99.957787,93.313344,84.668294,111.953201,119.676628,106.414441,137.948662,69.634344,114.024685
4,104.073940,127.217426,69.730286,115.690253,120.920018,148.666096,116.786233,139.061346,83.559242,103.091764,...,75.279364,87.349475,97.655142,89.118820,126.637608,114.886056,101.361093,126.482809,66.133931,109.168340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,126.520010,110.917507,102.822108,62.853700,149.747652,127.099840,123.942335,108.196626,107.105731,96.441980,...,91.496394,121.729389,87.948166,77.602308,127.656991,114.668824,127.756278,109.362652,102.983525,78.077730
2439,122.656116,114.785269,98.718438,76.449249,152.660776,140.174139,136.835759,113.267986,104.631338,98.998328,...,92.880258,108.747017,88.541794,75.344392,125.557441,111.031434,134.494231,116.813742,112.599318,79.992646
2440,126.597748,119.491178,105.538634,75.394449,145.766322,143.595590,129.875574,120.944104,106.966013,96.617547,...,89.648431,106.485343,93.400271,71.177932,123.918015,105.789520,127.670906,109.512188,104.166149,83.022547
2441,139.564043,109.141995,106.936201,78.218026,144.561741,141.507291,125.361425,123.071554,105.897605,91.914775,...,86.126272,106.959002,88.494586,63.991014,129.409898,109.907911,126.391262,111.268189,100.508162,70.592735
2442,132.013398,115.430773,105.461899,71.804618,151.624598,143.982949,127.958184,113.784393,97.022346,99.972913,...,88.589209,107.322913,86.795897,75.659668,122.322131,117.782888,126.797409,117.722182,110.106607,76.549859

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 32

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:32]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21,sensor22,sensor23,sensor24
0,101.870132,134.252574,72.801390,108.446568,130.203502,150.760073,103.508252,125.193887,89.453295,97.318384,...,107.051532,124.324976,91.735403,122.737112,59.428276,112.945303,107.048113,137.193866,82.867633,121.244903
1,101.656974,133.421922,76.037698,115.578180,124.237134,144.797812,106.645699,137.372609,92.314999,112.314087,...,113.850953,117.801200,104.299209,125.049258,56.772454,108.156125,116.168202,138.846561,87.815198,127.885537
2,102.889598,140.640194,71.553137,106.871465,123.654012,148.446127,103.789337,135.667714,99.182335,106.232463,...,101.090832,113.383786,108.974984,128.985264,58.017412,106.333965,125.125617,139.026194,79.962744,120.686542
3,100.508164,130.788193,73.179060,122.566756,128.558120,144.121205,102.460744,129.928887,86.763744,106.168512,...,109.590169,126.267858,97.167399,134.473699,53.601933,113.049890,104.513667,130.516633,89.381611,122.638217
4,104.073940,127.217426,69.730286,115.690253,120.920018,148.666096,116.786233,139.061346,83.559242,103.091764,...,101.223119,118.873622,97.616879,140.035649,55.501190,114.036270,114.494675,139.247307,85.307319,120.171501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,126.520010,110.917507,102.822108,62.853700,149.747652,127.099840,123.942335,108.196626,107.105731,96.441980,...,119.940259,103.272859,136.990878,109.946398,102.971514,65.770481,138.989434,135.979666,111.415908,83.023104
2439,122.656116,114.785269,98.718438,76.449249,152.660776,140.174139,136.835759,113.267986,104.631338,98.998328,...,117.365194,114.416527,136.976776,110.236827,90.418915,62.016384,139.955896,121.036566,120.217169,90.140067
2440,126.597748,119.491178,105.538634,75.394449,145.766322,143.595590,129.875574,120.944104,106.966013,96.617547,...,123.582865,113.049668,133.633092,112.781527,87.321252,68.554362,139.143021,125.317923,114.306234,95.384183
2441,139.564043,109.141995,106.936201,78.218026,144.561741,141.507291,125.361425,123.071554,105.897605,91.914775,...,124.604990,113.155807,127.248332,108.509153,96.605607,71.343902,140.910940,126.953390,123.237372,101.313107
2442,132.013398,115.430773,105.461899,71.804618,151.624598,143.982949,127.958184,113.784393,97.022346,99.972913,...,116.554557,109.144032,136.355528,117.016562,101.283816,63.681543,141.898885,119.674883,119.761631,88.441370

# Importing Libraries

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [15]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

In [16]:
X

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21,sensor22,sensor23,sensor24
0,101.870132,134.252574,72.801390,108.446568,130.203502,150.760073,103.508252,125.193887,89.453295,97.318384,...,107.051532,124.324976,91.735403,122.737112,59.428276,112.945303,107.048113,137.193866,82.867633,121.244903
1,101.656974,133.421922,76.037698,115.578180,124.237134,144.797812,106.645699,137.372609,92.314999,112.314087,...,113.850953,117.801200,104.299209,125.049258,56.772454,108.156125,116.168202,138.846561,87.815198,127.885537
2,102.889598,140.640194,71.553137,106.871465,123.654012,148.446127,103.789337,135.667714,99.182335,106.232463,...,101.090832,113.383786,108.974984,128.985264,58.017412,106.333965,125.125617,139.026194,79.962744,120.686542
3,100.508164,130.788193,73.179060,122.566756,128.558120,144.121205,102.460744,129.928887,86.763744,106.168512,...,109.590169,126.267858,97.167399,134.473699,53.601933,113.049890,104.513667,130.516633,89.381611,122.638217
4,104.073940,127.217426,69.730286,115.690253,120.920018,148.666096,116.786233,139.061346,83.559242,103.091764,...,101.223119,118.873622,97.616879,140.035649,55.501190,114.036270,114.494675,139.247307,85.307319,120.171501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,126.520010,110.917507,102.822108,62.853700,149.747652,127.099840,123.942335,108.196626,107.105731,96.441980,...,119.940259,103.272859,136.990878,109.946398,102.971514,65.770481,138.989434,135.979666,111.415908,83.023104
2439,122.656116,114.785269,98.718438,76.449249,152.660776,140.174139,136.835759,113.267986,104.631338,98.998328,...,117.365194,114.416527,136.976776,110.236827,90.418915,62.016384,139.955896,121.036566,120.217169,90.140067
2440,126.597748,119.491178,105.538634,75.394449,145.766322,143.595590,129.875574,120.944104,106.966013,96.617547,...,123.582865,113.049668,133.633092,112.781527,87.321252,68.554362,139.143021,125.317923,114.306234,95.384183
2441,139.564043,109.141995,106.936201,78.218026,144.561741,141.507291,125.361425,123.071554,105.897605,91.914775,...,124.604990,113.155807,127.248332,108.509153,96.605607,71.343902,140.910940,126.953390,123.237372,101.313107
2442,132.013398,115.430773,105.461899,71.804618,151.624598,143.982949,127.958184,113.784393,97.022346,99.972913,...,116.554557,109.144032,136.355528,117.016562,101.283816,63.681543,141.898885,119.674883,119.761631,88.441370

In [17]:
y

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Define models

In [18]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [19]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [20]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [21]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 16.78
Fold 1 - Mean Absolute Error (MAE): 3.22
Fold 1 - Root Mean Squared Error (RMSE): 4.10
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 17.30
Fold 2 - Mean Absolute Error (MAE): 3.32
Fold 2 - Root Mean Squared Error (RMSE): 4.16
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 16.30
Fold 3 - Mean Absolute Error (MAE): 3.17
Fold 3 - Root Mean Squared Error (RMSE): 4.04
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 15.83
Fold 4 - Mean Absolute Error (MAE): 3.16
Fold 4 - Root Mean Squared Error (RMSE): 3.98
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 16.73
Fold 5 - Mean Absolute Error (MAE): 3.27
Fold 5 - Root Mean Squared Error (RMSE): 4.09
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 16.59
Mean - Mean Absolute Error (MAE): 3.23
Mean - Root Mean Squared Error (RMSE): 4.07
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 98.09
Fold 1 - Mean Absolute Error (MAE): 6.34
Fold 1 - Root Mean Squared Error (RMSE): 9.90
Fold 1 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 92.47
Fold 2 - Mean Absolute Error (MAE): 6.12
Fold 2 - Root Mean Squared Error (RMSE): 9.62
Fold 2 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 106.36
Fold 3 - Mean Absolute Error (MAE): 6.54
Fold 3 - Root Mean Squared Error (RMSE): 10.31
Fold 3 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 91.63
Fold 4 - Mean Absolute Error (MAE): 6.09
Fold 4 - Root Mean Squared Error (RMSE): 9.57
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 89.59
Fold 5 - Mean Absolute Error (MAE): 6.03
Fold 5 - Root Mean Squared Error (RMSE): 9.47
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 95.63
Mean - Mean Absolute Error (MAE): 6.22
Mean - Root Mean Squared Error (RMSE): 9.77
Mean - Time taken: 0.03 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 25.89
Fold 1 - Mean Absolute Error (MAE): 3.87
Fold 1 - Root Mean Squared Error (RMSE): 5.09
Fold 1 - Time taken: 1.64 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 25.33
Fold 2 - Mean Absolute Error (MAE): 3.81
Fold 2 - Root Mean Squared Error (RMSE): 5.03
Fold 2 - Time taken: 1.90 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 23.41
Fold 3 - Mean Absolute Error (MAE): 3.73
Fold 3 - Root Mean Squared Error (RMSE): 4.84
Fold 3 - Time taken: 1.69 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 23.40
Fold 4 - Mean Absolute Error (MAE): 3.72
Fold 4 - Root Mean Squared Error (RMSE): 4.84
Fold 4 - Time taken: 2.09 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 23.04
Fold 5 - Mean Absolute Error (MAE): 3.73
Fold 5 - Root Mean Squared Error (RMSE): 4.80
Fold 5 - Time taken: 2.10 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 24.21
Mean - Mean Absolute Error (MAE): 3.77
Mean - Root Mean Squared Error (RMSE): 4.92
Mean - Time taken: 1.88 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 9.59
Fold 1 - Mean Absolute Error (MAE): 2.06
Fold 1 - Root Mean Squared Error (RMSE): 3.10
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 10.57
Fold 2 - Mean Absolute Error (MAE): 2.14
Fold 2 - Root Mean Squared Error (RMSE): 3.25
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 10.04
Fold 3 - Mean Absolute Error (MAE): 2.12
Fold 3 - Root Mean Squared Error (RMSE): 3.17
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 9.58
Fold 4 - Mean Absolute Error (MAE): 2.07
Fold 4 - Root Mean Squared Error (RMSE): 3.10
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 10.93
Fold 5 - Mean Absolute Error (MAE): 2.17
Fold 5 - Root Mean Squared Error (RMSE): 3.31
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 10.14
Mean - Mean Absolute Error (MAE): 2.11
Mean - Root Mean Squared Error (RMSE): 3.18
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 25.45
Fold 1 - Mean Absolute Error (MAE): 3.67
Fold 1 - Root Mean Squared Error (RMSE): 5.04
Fold 1 - Time taken: 1.25 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 24.15
Fold 2 - Mean Absolute Error (MAE): 3.59
Fold 2 - Root Mean Squared Error (RMSE): 4.91
Fold 2 - Time taken: 1.26 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 25.83
Fold 3 - Mean Absolute Error (MAE): 3.79
Fold 3 - Root Mean Squared Error (RMSE): 5.08
Fold 3 - Time taken: 1.26 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 24.20
Fold 4 - Mean Absolute Error (MAE): 3.59
Fold 4 - Root Mean Squared Error (RMSE): 4.92
Fold 4 - Time taken: 1.30 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 26.16
Fold 5 - Mean Absolute Error (MAE): 3.82
Fold 5 - Root Mean Squared Error (RMSE): 5.11
Fold 5 - Time taken: 1.29 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 25.16
Mean - Mean Absolute Error (MAE): 3.69
Mean - Root Mean Squared Error (RMSE): 5.01
Mean - Time taken: 1.27 seconds

# Saving the Mean results to an Excel file

In [22]:
# Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

# Filter the dataframe to include only the mean values
mean_results_df = results_df[results_df["Fold"] == "Mean"]

# Save the mean results to an Excel file
mean_results_df.to_excel("(1-32) Sensors PL_model_1_Scattered_iReg3 results.xlsx", index=False)