# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing1_Reg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,69.017352,73.453558,57.852208,71.719159,71.152955,76.727594,70.522482,75.499691,67.894535,69.525813,...,66.780779,65.567284,67.146507,63.124953,72.691786,69.000180,66.483648,72.756315,58.365477,70.360938
1,69.161371,73.288338,58.010893,71.854817,70.978148,77.003870,70.686867,75.217425,67.732909,69.856304,...,66.744254,65.371133,67.265487,63.241881,72.678044,68.809255,66.748595,72.547572,58.267446,70.512423
2,69.620702,73.308294,58.062578,71.785193,71.133621,77.169759,70.622298,74.713946,67.876581,69.736037,...,66.722959,65.571470,67.354904,63.377772,72.766343,68.547359,66.650188,72.722804,58.267627,70.539273
3,69.427053,73.376663,58.183241,72.034862,71.344417,77.128352,70.637501,74.679064,67.775054,70.126806,...,66.764755,65.704851,67.409487,63.843004,72.555318,68.101008,66.380381,72.924426,58.321276,70.547533
4,69.138756,73.484602,58.482826,71.838442,71.283718,76.953818,70.552840,74.752213,67.869282,70.326623,...,66.671655,65.762421,67.376241,63.817186,72.626974,68.049231,66.579266,73.528160,58.544315,70.597130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,73.671151,71.739890,67.043847,58.781450,78.587862,76.954865,73.808617,69.950606,71.262754,67.864153,...,68.451277,70.780746,67.112261,53.179880,71.606502,69.727751,71.395284,71.237080,67.507454,59.642289
2439,73.827269,71.442343,67.220348,59.220385,78.327084,77.000169,73.757889,69.969490,71.441217,68.023656,...,68.292783,70.715882,66.880112,52.876593,71.384747,69.753224,71.316355,71.398237,67.329516,59.559106
2440,73.795785,71.207819,67.166940,58.981825,78.308251,76.954473,74.140129,69.823646,71.447460,68.090855,...,67.985287,70.312869,67.117697,52.883363,71.424547,70.100304,71.626594,71.276925,67.395968,59.713216
2441,73.408911,70.978993,67.372467,59.285489,78.223221,76.772492,74.011113,69.706522,71.306958,67.989039,...,67.958237,69.732485,67.261894,53.291311,71.907965,69.717504,71.249103,71.698660,67.416192,59.442900
2442,72.988805,70.989528,67.329827,58.913158,78.289805,76.802164,74.020234,69.394885,71.518313,67.695856,...,68.270614,69.622516,67.103476,53.250051,72.354793,69.382961,71.261549,71.986845,67.612320,59.489855

In [4]:
position_data = pd.read_excel('real_positions_Reg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,69.017352,73.453558,57.852208,71.719159,71.152955,76.727594,70.522482,75.499691,67.894535,69.525813,...,66.780779,65.567284,67.146507,63.124953,72.691786,69.000180,66.483648,72.756315,58.365477,70.360938
1,69.161371,73.288338,58.010893,71.854817,70.978148,77.003870,70.686867,75.217425,67.732909,69.856304,...,66.744254,65.371133,67.265487,63.241881,72.678044,68.809255,66.748595,72.547572,58.267446,70.512423
2,69.620702,73.308294,58.062578,71.785193,71.133621,77.169759,70.622298,74.713946,67.876581,69.736037,...,66.722959,65.571470,67.354904,63.377772,72.766343,68.547359,66.650188,72.722804,58.267627,70.539273
3,69.427053,73.376663,58.183241,72.034862,71.344417,77.128352,70.637501,74.679064,67.775054,70.126806,...,66.764755,65.704851,67.409487,63.843004,72.555318,68.101008,66.380381,72.924426,58.321276,70.547533
4,69.138756,73.484602,58.482826,71.838442,71.283718,76.953818,70.552840,74.752213,67.869282,70.326623,...,66.671655,65.762421,67.376241,63.817186,72.626974,68.049231,66.579266,73.528160,58.544315,70.597130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,73.671151,71.739890,67.043847,58.781450,78.587862,76.954865,73.808617,69.950606,71.262754,67.864153,...,68.451277,70.780746,67.112261,53.179880,71.606502,69.727751,71.395284,71.237080,67.507454,59.642289
2439,73.827269,71.442343,67.220348,59.220385,78.327084,77.000169,73.757889,69.969490,71.441217,68.023656,...,68.292783,70.715882,66.880112,52.876593,71.384747,69.753224,71.316355,71.398237,67.329516,59.559106
2440,73.795785,71.207819,67.166940,58.981825,78.308251,76.954473,74.140129,69.823646,71.447460,68.090855,...,67.985287,70.312869,67.117697,52.883363,71.424547,70.100304,71.626594,71.276925,67.395968,59.713216
2441,73.408911,70.978993,67.372467,59.285489,78.223221,76.772492,74.011113,69.706522,71.306958,67.989039,...,67.958237,69.732485,67.261894,53.291311,71.907965,69.717504,71.249103,71.698660,67.416192,59.442900
2442,72.988805,70.989528,67.329827,58.913158,78.289805,76.802164,74.020234,69.394885,71.518313,67.695856,...,68.270614,69.622516,67.103476,53.250051,72.354793,69.382961,71.261549,71.986845,67.612320,59.489855

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 3.01
Fold 1 - Mean Absolute Error (MAE): 1.32
Fold 1 - Root Mean Squared Error (RMSE): 1.73
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 2.95
Fold 2 - Mean Absolute Error (MAE): 1.31
Fold 2 - Root Mean Squared Error (RMSE): 1.72
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 3.05
Fold 3 - Mean Absolute Error (MAE): 1.33
Fold 3 - Root Mean Squared Error (RMSE): 1.75
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 2.82
Fold 4 - Mean Absolute Error (MAE): 1.27
Fold 4 - Root Mean Squared Error (RMSE): 1.68
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 3.06
Fold 5 - Mean Absolute Error (MAE): 1.34
Fold 5 - Root Mean Squared Error (RMSE): 1.75
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 2.98
Mean - Mean Absolute Error (MAE): 1.31
Mean - Root Mean Squared Error (RMSE): 1.73
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 5.03
Fold 1 - Mean Absolute Error (MAE): 0.79
Fold 1 - Root Mean Squared Error (RMSE): 2.24
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 1.28
Fold 2 - Mean Absolute Error (MAE): 0.52
Fold 2 - Root Mean Squared Error (RMSE): 1.13
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 2.16
Fold 3 - Mean Absolute Error (MAE): 0.66
Fold 3 - Root Mean Squared Error (RMSE): 1.47
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 6.12
Fold 4 - Mean Absolute Error (MAE): 0.75
Fold 4 - Root Mean Squared Error (RMSE): 2.47
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 4.82
Fold 5 - Mean Absolute Error (MAE): 0.73
Fold 5 - Root Mean Squared Error (RMSE): 2.20
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 3.88
Mean - Mean Absolute Error (MAE): 0.69
Mean - Root Mean Squared Error (RMSE): 1.90
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.36
Fold 1 - Mean Absolute Error (MAE): 0.29
Fold 1 - Root Mean Squared Error (RMSE): 0.60
Fold 1 - Time taken: 2.39 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.20
Fold 2 - Mean Absolute Error (MAE): 0.27
Fold 2 - Root Mean Squared Error (RMSE): 0.45
Fold 2 - Time taken: 2.66 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.32
Fold 3 - Mean Absolute Error (MAE): 0.31
Fold 3 - Root Mean Squared Error (RMSE): 0.56
Fold 3 - Time taken: 3.72 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.57
Fold 4 - Mean Absolute Error (MAE): 0.33
Fold 4 - Root Mean Squared Error (RMSE): 0.76
Fold 4 - Time taken: 3.81 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.62
Fold 5 - Mean Absolute Error (MAE): 0.34
Fold 5 - Root Mean Squared Error (RMSE): 0.79
Fold 5 - Time taken: 3.86 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.41
Mean - Mean Absolute Error (MAE): 0.31
Mean - Root Mean Squared Error (RMSE): 0.63
Mean - Time taken: 3.29 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.05
Fold 1 - Mean Absolute Error (MAE): 0.15
Fold 1 - Root Mean Squared Error (RMSE): 0.23
Fold 1 - Time taken: 0.11 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.06
Fold 2 - Mean Absolute Error (MAE): 0.15
Fold 2 - Root Mean Squared Error (RMSE): 0.24
Fold 2 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.07
Fold 3 - Mean Absolute Error (MAE): 0.16
Fold 3 - Root Mean Squared Error (RMSE): 0.26
Fold 3 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.07
Fold 4 - Mean Absolute Error (MAE): 0.16
Fold 4 - Root Mean Squared Error (RMSE): 0.26
Fold 4 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.07
Fold 5 - Mean Absolute Error (MAE): 0.17
Fold 5 - Root Mean Squared Error (RMSE): 0.27
Fold 5 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.06
Mean - Mean Absolute Error (MAE): 0.16
Mean - Root Mean Squared Error (RMSE): 0.25
Mean - Time taken: 0.07 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.88
Fold 1 - Mean Absolute Error (MAE): 0.67
Fold 1 - Root Mean Squared Error (RMSE): 1.37
Fold 1 - Time taken: 4.66 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 1.44
Fold 2 - Mean Absolute Error (MAE): 0.69
Fold 2 - Root Mean Squared Error (RMSE): 1.20
Fold 2 - Time taken: 4.95 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.34
Fold 3 - Mean Absolute Error (MAE): 0.68
Fold 3 - Root Mean Squared Error (RMSE): 1.16
Fold 3 - Time taken: 5.10 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1.43
Fold 4 - Mean Absolute Error (MAE): 0.64
Fold 4 - Root Mean Squared Error (RMSE): 1.20
Fold 4 - Time taken: 4.40 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.20
Fold 5 - Mean Absolute Error (MAE): 0.65
Fold 5 - Root Mean Squared Error (RMSE): 1.10
Fold 5 - Time taken: 3.51 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1.46
Mean - Mean Absolute Error (MAE): 0.67
Mean - Root Mean Squared Error (RMSE): 1.20
Mean - Time taken: 4.53 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing1_Reg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing1_Reg1.xlsx file")

Results saved to Results__PL_model_2_smoothing1_Reg1.xlsx file