# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_2_smoothing2_Reg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,72.255262,71.971142,59.297033,70.168324,72.223257,78.156174,70.720922,71.671559,66.034745,68.503224,...,68.551835,66.226435,61.979756,61.124430,73.919407,69.627583,69.312761,70.642658,60.969641,71.643253
1,72.029172,72.095736,59.195081,70.251247,72.172055,78.132133,70.750461,71.889199,66.181062,68.578317,...,68.400324,66.206345,62.317160,61.257023,73.842502,69.644318,69.143555,70.733665,60.837893,71.609484
2,71.807358,72.215594,59.102536,70.334800,72.118766,78.106993,70.778609,72.106459,66.327732,68.653060,...,68.255380,66.185249,62.651930,61.392031,73.768352,69.654955,68.974929,70.827779,60.708759,71.577138
3,71.590422,72.330512,59.019202,70.419252,72.063870,78.081097,70.804871,72.323391,66.474047,68.727520,...,68.117018,66.163235,62.984053,61.529815,73.696280,69.659422,68.807551,70.924403,60.581964,71.546492
4,71.378722,72.440584,58.944518,70.504615,72.007938,78.054497,70.828614,72.539718,66.619117,68.801921,...,67.985182,66.140380,63.313694,61.670413,73.625580,69.657956,68.641912,71.022581,60.456878,71.517763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,73.098106,72.579984,70.393482,57.539933,76.493660,77.698430,73.453426,68.863653,71.662133,68.616475,...,66.113821,69.106403,65.986037,52.906771,72.026893,70.616229,71.559465,75.327743,65.497743,61.041995
2439,73.069455,72.686191,70.593724,57.422708,76.310721,77.797643,73.449306,68.746579,71.740129,68.624573,...,65.951813,69.014658,65.824532,52.921059,71.964983,70.654036,71.570827,75.516862,65.328859,61.156410
2440,73.044731,72.796004,70.796814,57.304143,76.124633,77.899235,73.448736,68.627163,71.822711,68.629821,...,65.790041,68.920597,65.658370,52.938117,71.897161,70.690490,71.585216,75.707701,65.159436,61.274501
2441,73.024322,72.909059,71.003291,57.183712,75.934742,78.003086,73.451758,68.505253,71.909019,68.631663,...,65.628825,68.823687,65.488250,52.958021,71.823691,70.725859,71.602832,75.900074,64.989387,61.396096
2442,73.008414,73.024663,71.213720,57.061155,75.740776,78.108850,73.458031,68.380598,71.998276,68.629823,...,65.468769,68.723471,65.315066,52.980600,71.744712,70.760411,71.623714,76.093722,64.818402,61.520882

In [4]:
position_data = pd.read_excel('real_positions_Reg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,72.255262,71.971142,59.297033,70.168324,72.223257,78.156174,70.720922,71.671559,66.034745,68.503224,...,68.551835,66.226435,61.979756,61.124430,73.919407,69.627583,69.312761,70.642658,60.969641,71.643253
1,72.029172,72.095736,59.195081,70.251247,72.172055,78.132133,70.750461,71.889199,66.181062,68.578317,...,68.400324,66.206345,62.317160,61.257023,73.842502,69.644318,69.143555,70.733665,60.837893,71.609484
2,71.807358,72.215594,59.102536,70.334800,72.118766,78.106993,70.778609,72.106459,66.327732,68.653060,...,68.255380,66.185249,62.651930,61.392031,73.768352,69.654955,68.974929,70.827779,60.708759,71.577138
3,71.590422,72.330512,59.019202,70.419252,72.063870,78.081097,70.804871,72.323391,66.474047,68.727520,...,68.117018,66.163235,62.984053,61.529815,73.696280,69.659422,68.807551,70.924403,60.581964,71.546492
4,71.378722,72.440584,58.944518,70.504615,72.007938,78.054497,70.828614,72.539718,66.619117,68.801921,...,67.985182,66.140380,63.313694,61.670413,73.625580,69.657956,68.641912,71.022581,60.456878,71.517763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,73.098106,72.579984,70.393482,57.539933,76.493660,77.698430,73.453426,68.863653,71.662133,68.616475,...,66.113821,69.106403,65.986037,52.906771,72.026893,70.616229,71.559465,75.327743,65.497743,61.041995
2439,73.069455,72.686191,70.593724,57.422708,76.310721,77.797643,73.449306,68.746579,71.740129,68.624573,...,65.951813,69.014658,65.824532,52.921059,71.964983,70.654036,71.570827,75.516862,65.328859,61.156410
2440,73.044731,72.796004,70.796814,57.304143,76.124633,77.899235,73.448736,68.627163,71.822711,68.629821,...,65.790041,68.920597,65.658370,52.938117,71.897161,70.690490,71.585216,75.707701,65.159436,61.274501
2441,73.024322,72.909059,71.003291,57.183712,75.934742,78.003086,73.451758,68.505253,71.909019,68.631663,...,65.628825,68.823687,65.488250,52.958021,71.823691,70.725859,71.602832,75.900074,64.989387,61.396096
2442,73.008414,73.024663,71.213720,57.061155,75.740776,78.108850,73.458031,68.380598,71.998276,68.629823,...,65.468769,68.723471,65.315066,52.980600,71.744712,70.760411,71.623714,76.093722,64.818402,61.520882

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 7.28
Fold 1 - Mean Absolute Error (MAE): 2.06
Fold 1 - Root Mean Squared Error (RMSE): 2.70
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 7.61
Fold 2 - Mean Absolute Error (MAE): 2.07
Fold 2 - Root Mean Squared Error (RMSE): 2.76
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 7.75
Fold 3 - Mean Absolute Error (MAE): 2.13
Fold 3 - Root Mean Squared Error (RMSE): 2.78
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 7.55
Fold 4 - Mean Absolute Error (MAE): 2.10
Fold 4 - Root Mean Squared Error (RMSE): 2.75
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 7.69
Fold 5 - Mean Absolute Error (MAE): 2.10
Fold 5 - Root Mean Squared Error (RMSE): 2.77
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 7.57
Mean - Mean Absolute Error (MAE): 2.09
Mean - Root Mean Squared Error (RMSE): 2.75
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 3.82
Fold 1 - Mean Absolute Error (MAE): 0.40
Fold 1 - Root Mean Squared Error (RMSE): 1.96
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 2.10
Fold 2 - Mean Absolute Error (MAE): 0.40
Fold 2 - Root Mean Squared Error (RMSE): 1.45
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 3.52
Fold 3 - Mean Absolute Error (MAE): 0.48
Fold 3 - Root Mean Squared Error (RMSE): 1.88
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 2.98
Fold 4 - Mean Absolute Error (MAE): 0.45
Fold 4 - Root Mean Squared Error (RMSE): 1.73
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 1.43
Fold 5 - Mean Absolute Error (MAE): 0.41
Fold 5 - Root Mean Squared Error (RMSE): 1.20
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 2.77
Mean - Mean Absolute Error (MAE): 0.43
Mean - Root Mean Squared Error (RMSE): 1.64
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.40
Fold 1 - Mean Absolute Error (MAE): 0.24
Fold 1 - Root Mean Squared Error (RMSE): 0.63
Fold 1 - Time taken: 2.37 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.39
Fold 2 - Mean Absolute Error (MAE): 0.25
Fold 2 - Root Mean Squared Error (RMSE): 0.62
Fold 2 - Time taken: 2.34 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.73
Fold 3 - Mean Absolute Error (MAE): 0.32
Fold 3 - Root Mean Squared Error (RMSE): 0.85
Fold 3 - Time taken: 3.49 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.28
Fold 4 - Mean Absolute Error (MAE): 0.25
Fold 4 - Root Mean Squared Error (RMSE): 0.53
Fold 4 - Time taken: 3.65 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.37
Fold 5 - Mean Absolute Error (MAE): 0.28
Fold 5 - Root Mean Squared Error (RMSE): 0.61
Fold 5 - Time taken: 3.72 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.43
Mean - Mean Absolute Error (MAE): 0.27
Mean - Root Mean Squared Error (RMSE): 0.65
Mean - Time taken: 3.11 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.04
Fold 1 - Mean Absolute Error (MAE): 0.13
Fold 1 - Root Mean Squared Error (RMSE): 0.20
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.05
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.22
Fold 2 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.06
Fold 3 - Mean Absolute Error (MAE): 0.15
Fold 3 - Root Mean Squared Error (RMSE): 0.24
Fold 3 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.05
Fold 4 - Mean Absolute Error (MAE): 0.14
Fold 4 - Root Mean Squared Error (RMSE): 0.23
Fold 4 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.05
Fold 5 - Mean Absolute Error (MAE): 0.14
Fold 5 - Root Mean Squared Error (RMSE): 0.23
Fold 5 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.05
Mean - Mean Absolute Error (MAE): 0.14
Mean - Root Mean Squared Error (RMSE): 0.22
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.01
Fold 1 - Mean Absolute Error (MAE): 0.50
Fold 1 - Root Mean Squared Error (RMSE): 1.00
Fold 1 - Time taken: 3.41 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.97
Fold 2 - Mean Absolute Error (MAE): 0.44
Fold 2 - Root Mean Squared Error (RMSE): 0.99
Fold 2 - Time taken: 3.91 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.29
Fold 3 - Mean Absolute Error (MAE): 0.51
Fold 3 - Root Mean Squared Error (RMSE): 1.13
Fold 3 - Time taken: 4.46 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1.91
Fold 4 - Mean Absolute Error (MAE): 0.51
Fold 4 - Root Mean Squared Error (RMSE): 1.38
Fold 4 - Time taken: 4.94 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 0.79
Fold 5 - Mean Absolute Error (MAE): 0.47
Fold 5 - Root Mean Squared Error (RMSE): 0.89
Fold 5 - Time taken: 5.06 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1.20
Mean - Mean Absolute Error (MAE): 0.49
Mean - Root Mean Squared Error (RMSE): 1.08
Mean - Time taken: 4.35 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_model_2_smoothing2_Reg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_model_2_smoothing2_Reg1.xlsx file")

Results saved to Results__PL_model_2_smoothing2_Reg1.xlsx file