# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_model_1_smoothing2_Reg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,102.569633,132.669774,83.130710,119.261204,126.578979,148.830041,111.311166,139.430392,99.615316,118.557826,...,101.044016,97.658267,102.844237,86.402391,128.906224,113.014998,103.942203,128.786522,77.145139,118.042869
1,102.590690,132.661834,83.202932,119.275839,126.462565,148.697946,111.148479,139.223949,99.741752,118.556519,...,101.107786,97.777283,103.059338,86.470380,128.767509,112.867564,103.812490,128.886979,77.151769,117.929142
2,102.614362,132.654377,83.275524,119.290404,126.346475,148.563611,110.985467,139.017736,99.869282,118.556061,...,101.172404,97.896426,103.277594,86.537182,128.629069,112.718192,103.682163,128.986052,77.158113,117.815084
3,102.641009,132.647443,83.348540,119.304798,126.230663,148.427340,110.822296,138.811784,99.997960,118.556686,...,101.238191,98.016139,103.498832,86.603111,128.491033,112.567106,103.551552,129.083881,77.163684,117.700897
4,102.670973,132.641270,83.422108,119.319043,126.115230,148.289453,110.658971,138.605917,100.127885,118.558828,...,101.305368,98.136740,103.722692,86.668617,128.353449,112.414828,103.421125,129.180734,77.168086,117.586815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.182404,113.040767,105.847805,78.217642,150.269492,137.927741,134.314210,115.883798,116.732585,107.086022,...,108.782340,119.546095,108.046566,68.424907,137.006882,114.335066,132.446443,116.008277,108.614011,80.271199
2439,127.864707,112.881785,105.963448,78.318383,150.043134,137.881055,134.455501,115.928398,116.563981,106.879909,...,108.681141,119.427729,107.891232,68.365363,136.918609,114.504131,132.374344,115.948280,108.700997,80.242280
2440,127.541664,112.723090,106.081989,78.418798,149.813444,137.835463,134.599156,115.974725,116.396053,106.673908,...,108.578553,119.309889,107.736048,68.304497,136.832191,114.676755,132.301638,115.889961,108.788631,80.215094
2441,127.213582,112.564486,106.203485,78.518849,149.580484,137.791058,134.745220,116.022311,116.228730,106.467758,...,108.474328,119.192398,107.581271,68.242740,136.747871,114.853115,132.228809,115.833382,108.877154,80.190119
2442,126.880923,112.405914,106.327742,78.618462,149.344480,137.747874,134.893804,116.070826,116.062017,106.261338,...,108.368265,119.075008,107.426963,68.180452,136.665841,115.033293,132.156320,115.778564,108.966672,80.167640

In [4]:
position_data = pd.read_excel('real_positions_Reg1.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,102.569633,132.669774,83.130710,119.261204,126.578979,148.830041,111.311166,139.430392,99.615316,118.557826,...,101.044016,97.658267,102.844237,86.402391,128.906224,113.014998,103.942203,128.786522,77.145139,118.042869
1,102.590690,132.661834,83.202932,119.275839,126.462565,148.697946,111.148479,139.223949,99.741752,118.556519,...,101.107786,97.777283,103.059338,86.470380,128.767509,112.867564,103.812490,128.886979,77.151769,117.929142
2,102.614362,132.654377,83.275524,119.290404,126.346475,148.563611,110.985467,139.017736,99.869282,118.556061,...,101.172404,97.896426,103.277594,86.537182,128.629069,112.718192,103.682163,128.986052,77.158113,117.815084
3,102.641009,132.647443,83.348540,119.304798,126.230663,148.427340,110.822296,138.811784,99.997960,118.556686,...,101.238191,98.016139,103.498832,86.603111,128.491033,112.567106,103.551552,129.083881,77.163684,117.700897
4,102.670973,132.641270,83.422108,119.319043,126.115230,148.289453,110.658971,138.605917,100.127885,118.558828,...,101.305368,98.136740,103.722692,86.668617,128.353449,112.414828,103.421125,129.180734,77.168086,117.586815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.182404,113.040767,105.847805,78.217642,150.269492,137.927741,134.314210,115.883798,116.732585,107.086022,...,108.782340,119.546095,108.046566,68.424907,137.006882,114.335066,132.446443,116.008277,108.614011,80.271199
2439,127.864707,112.881785,105.963448,78.318383,150.043134,137.881055,134.455501,115.928398,116.563981,106.879909,...,108.681141,119.427729,107.891232,68.365363,136.918609,114.504131,132.374344,115.948280,108.700997,80.242280
2440,127.541664,112.723090,106.081989,78.418798,149.813444,137.835463,134.599156,115.974725,116.396053,106.673908,...,108.578553,119.309889,107.736048,68.304497,136.832191,114.676755,132.301638,115.889961,108.788631,80.215094
2441,127.213582,112.564486,106.203485,78.518849,149.580484,137.791058,134.745220,116.022311,116.228730,106.467758,...,108.474328,119.192398,107.581271,68.242740,136.747871,114.853115,132.228809,115.833382,108.877154,80.190119
2442,126.880923,112.405914,106.327742,78.618462,149.344480,137.747874,134.893804,116.070826,116.062017,106.261338,...,108.368265,119.075008,107.426963,68.180452,136.665841,115.033293,132.156320,115.778564,108.966672,80.167640

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 24

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:24]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21,sensor22,sensor23,sensor24
0,102.569633,132.669774,83.130710,119.261204,126.578979,148.830041,111.311166,139.430392,99.615316,118.557826,...,109.985530,122.493300,100.052217,127.791039,76.876268,114.481688,112.185589,138.967182,93.475678,124.487047
1,102.590690,132.661834,83.202932,119.275839,126.462565,148.697946,111.148479,139.223949,99.741752,118.556519,...,109.790512,122.456806,100.000691,127.762772,76.745788,114.501456,112.097867,138.857691,93.364824,124.446560
2,102.614362,132.654377,83.275524,119.290404,126.346475,148.563611,110.985467,139.017736,99.869282,118.556061,...,109.592455,122.417392,99.949271,127.736450,76.614652,114.524421,112.012524,138.749596,93.253756,124.405166
3,102.641009,132.647443,83.348540,119.304798,126.230663,148.427340,110.822296,138.811784,99.997960,118.556686,...,109.391553,122.375185,99.897875,127.712261,76.483228,114.550365,111.929693,138.642724,93.142528,124.362983
4,102.670973,132.641270,83.422108,119.319043,126.115230,148.289453,110.658971,138.605917,100.127885,118.558828,...,109.188220,122.330185,99.846328,127.690337,76.351954,114.578905,111.849483,138.536957,93.031192,124.320064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.182404,113.040767,105.847805,78.217642,150.269492,137.927741,134.314210,115.883798,116.732585,107.086022,...,121.716794,111.989042,129.611619,111.923377,102.357914,74.030300,141.276559,122.838981,118.636678,96.576583
2439,127.864707,112.881785,105.963448,78.318383,150.043134,137.881055,134.455501,115.928398,116.563981,106.879909,...,121.795183,112.011359,129.605967,111.836164,102.425068,74.052647,141.243593,122.415397,118.761288,96.688375
2440,127.541664,112.723090,106.081989,78.418798,149.813444,137.835463,134.599156,115.974725,116.396053,106.673908,...,121.873632,112.034771,129.598424,111.750979,102.490934,74.075961,141.209070,121.988232,118.887070,96.802620
2441,127.213582,112.564486,106.203485,78.518849,149.580484,137.791058,134.745220,116.022311,116.228730,106.467758,...,121.951891,112.059291,129.588922,111.667781,102.555525,74.100158,141.173101,121.557408,119.013972,96.919590
2442,126.880923,112.405914,106.327742,78.618462,149.344480,137.747874,134.893804,116.070826,116.062017,106.261338,...,122.029925,112.084752,129.577413,111.586429,102.618832,74.125064,141.135585,121.122999,119.141848,97.039603

# Importing Libraries

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [15]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

In [16]:
X

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21,sensor22,sensor23,sensor24
0,102.569633,132.669774,83.130710,119.261204,126.578979,148.830041,111.311166,139.430392,99.615316,118.557826,...,109.985530,122.493300,100.052217,127.791039,76.876268,114.481688,112.185589,138.967182,93.475678,124.487047
1,102.590690,132.661834,83.202932,119.275839,126.462565,148.697946,111.148479,139.223949,99.741752,118.556519,...,109.790512,122.456806,100.000691,127.762772,76.745788,114.501456,112.097867,138.857691,93.364824,124.446560
2,102.614362,132.654377,83.275524,119.290404,126.346475,148.563611,110.985467,139.017736,99.869282,118.556061,...,109.592455,122.417392,99.949271,127.736450,76.614652,114.524421,112.012524,138.749596,93.253756,124.405166
3,102.641009,132.647443,83.348540,119.304798,126.230663,148.427340,110.822296,138.811784,99.997960,118.556686,...,109.391553,122.375185,99.897875,127.712261,76.483228,114.550365,111.929693,138.642724,93.142528,124.362983
4,102.670973,132.641270,83.422108,119.319043,126.115230,148.289453,110.658971,138.605917,100.127885,118.558828,...,109.188220,122.330185,99.846328,127.690337,76.351954,114.578905,111.849483,138.536957,93.031192,124.320064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.182404,113.040767,105.847805,78.217642,150.269492,137.927741,134.314210,115.883798,116.732585,107.086022,...,121.716794,111.989042,129.611619,111.923377,102.357914,74.030300,141.276559,122.838981,118.636678,96.576583
2439,127.864707,112.881785,105.963448,78.318383,150.043134,137.881055,134.455501,115.928398,116.563981,106.879909,...,121.795183,112.011359,129.605967,111.836164,102.425068,74.052647,141.243593,122.415397,118.761288,96.688375
2440,127.541664,112.723090,106.081989,78.418798,149.813444,137.835463,134.599156,115.974725,116.396053,106.673908,...,121.873632,112.034771,129.598424,111.750979,102.490934,74.075961,141.209070,121.988232,118.887070,96.802620
2441,127.213582,112.564486,106.203485,78.518849,149.580484,137.791058,134.745220,116.022311,116.228730,106.467758,...,121.951891,112.059291,129.588922,111.667781,102.555525,74.100158,141.173101,121.557408,119.013972,96.919590
2442,126.880923,112.405914,106.327742,78.618462,149.344480,137.747874,134.893804,116.070826,116.062017,106.261338,...,122.029925,112.084752,129.577413,111.586429,102.618832,74.125064,141.135585,121.122999,119.141848,97.039603

In [17]:
y

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Define models

In [18]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [19]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [20]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [21]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.43
Fold 1 - Mean Absolute Error (MAE): 0.52
Fold 1 - Root Mean Squared Error (RMSE): 0.66
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.44
Fold 2 - Mean Absolute Error (MAE): 0.52
Fold 2 - Root Mean Squared Error (RMSE): 0.66
Fold 2 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.43
Fold 3 - Mean Absolute Error (MAE): 0.52
Fold 3 - Root Mean Squared Error (RMSE): 0.65
Fold 3 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.43
Fold 4 - Mean Absolute Error (MAE): 0.52
Fold 4 - Root Mean Squared Error (RMSE): 0.66
Fold 4 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.42
Fold 5 - Mean Absolute Error (MAE): 0.51
Fold 5 - Root Mean Squared Error (RMSE): 0.65
Fold 5 - Time taken: 0.00 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.43
Mean - Mean Absolute Error (MAE): 0.52
Mean - Root Mean Squared Error (RMSE): 0.65
Mean - Time taken: 0.00 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 2.69
Fold 1 - Mean Absolute Error (MAE): 0.39
Fold 1 - Root Mean Squared Error (RMSE): 1.64
Fold 1 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 5.52
Fold 2 - Mean Absolute Error (MAE): 0.45
Fold 2 - Root Mean Squared Error (RMSE): 2.35
Fold 2 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 0.16
Fold 3 - Mean Absolute Error (MAE): 0.26
Fold 3 - Root Mean Squared Error (RMSE): 0.39
Fold 3 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 0.83
Fold 4 - Mean Absolute Error (MAE): 0.33
Fold 4 - Root Mean Squared Error (RMSE): 0.91
Fold 4 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 0.50
Fold 5 - Mean Absolute Error (MAE): 0.31
Fold 5 - Root Mean Squared Error (RMSE): 0.71
Fold 5 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 1.94
Mean - Mean Absolute Error (MAE): 0.35
Mean - Root Mean Squared Error (RMSE): 1.20
Mean - Time taken: 0.02 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.05
Fold 1 - Mean Absolute Error (MAE): 0.14
Fold 1 - Root Mean Squared Error (RMSE): 0.23
Fold 1 - Time taken: 1.13 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.06
Fold 2 - Mean Absolute Error (MAE): 0.13
Fold 2 - Root Mean Squared Error (RMSE): 0.24
Fold 2 - Time taken: 1.12 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.14
Fold 3 - Mean Absolute Error (MAE): 0.16
Fold 3 - Root Mean Squared Error (RMSE): 0.38
Fold 3 - Time taken: 1.14 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.10
Fold 4 - Mean Absolute Error (MAE): 0.15
Fold 4 - Root Mean Squared Error (RMSE): 0.32
Fold 4 - Time taken: 1.12 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.05
Fold 5 - Mean Absolute Error (MAE): 0.14
Fold 5 - Root Mean Squared Error (RMSE): 0.23
Fold 5 - Time taken: 1.47 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.08
Mean - Mean Absolute Error (MAE): 0.15
Mean - Root Mean Squared Error (RMSE): 0.28
Mean - Time taken: 1.20 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.04
Fold 1 - Mean Absolute Error (MAE): 0.13
Fold 1 - Root Mean Squared Error (RMSE): 0.19
Fold 1 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.05
Fold 2 - Mean Absolute Error (MAE): 0.14
Fold 2 - Root Mean Squared Error (RMSE): 0.22
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.06
Fold 3 - Mean Absolute Error (MAE): 0.15
Fold 3 - Root Mean Squared Error (RMSE): 0.24
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.05
Fold 4 - Mean Absolute Error (MAE): 0.14
Fold 4 - Root Mean Squared Error (RMSE): 0.22
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.05
Fold 5 - Mean Absolute Error (MAE): 0.14
Fold 5 - Root Mean Squared Error (RMSE): 0.23
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.05
Mean - Mean Absolute Error (MAE): 0.14
Mean - Root Mean Squared Error (RMSE): 0.22
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.34
Fold 1 - Mean Absolute Error (MAE): 0.35
Fold 1 - Root Mean Squared Error (RMSE): 0.58
Fold 1 - Time taken: 1.21 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.46
Fold 2 - Mean Absolute Error (MAE): 0.37
Fold 2 - Root Mean Squared Error (RMSE): 0.68
Fold 2 - Time taken: 1.20 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 0.37
Fold 3 - Mean Absolute Error (MAE): 0.36
Fold 3 - Root Mean Squared Error (RMSE): 0.61
Fold 3 - Time taken: 1.19 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.49
Fold 4 - Mean Absolute Error (MAE): 0.39
Fold 4 - Root Mean Squared Error (RMSE): 0.70
Fold 4 - Time taken: 1.36 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 0.42
Fold 5 - Mean Absolute Error (MAE): 0.37
Fold 5 - Root Mean Squared Error (RMSE): 0.65
Fold 5 - Time taken: 1.46 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 0.42
Mean - Mean Absolute Error (MAE): 0.37
Mean - Root Mean Squared Error (RMSE): 0.64
Mean - Time taken: 1.28 seconds

# Saving the Mean results to an Excel file

In [22]:
# Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

# Filter the dataframe to include only the mean values
mean_results_df = results_df[results_df["Fold"] == "Mean"]

# Save the mean results to an Excel file
mean_results_df.to_excel("(1-24) Sensors PL_model_1_smoothing2_Reg1 Results.xlsx", index=False)